args:
let
  inherit (args) namespace lib config;
  inherit (lib.${namespace}) nixosModule;
  inherit (config.${namespace}.user) host;
  value = {
    services.xserver.extraConfig =
      if host == "home" then
        # enable nvidia vsync
        ''
          # nvidia-settings: X configuration file generated by nvidia-settings
          # nvidia-settings:  version 570.144

          Section "ServerLayout"
              Identifier     "Layout0"
              Screen      0  "Screen0" 0 0
              InputDevice    "Keyboard0" "CoreKeyboard"
              InputDevice    "Mouse0" "CorePointer"
              Option         "Xinerama" "0"
          EndSection

          Section "Files"
          EndSection

          Section "InputDevice"
              # generated from default
              Identifier     "Mouse0"
              Driver         "mouse"
              Option         "Protocol" "auto"
              Option         "Device" "/dev/input/mice"
              Option         "Emulate3Buttons" "no"
              Option         "ZAxisMapping" "4 5"
          EndSection

          Section "InputDevice"
              # generated from default
              Identifier     "Keyboard0"
              Driver         "kbd"
          EndSection

          Section "Monitor"
              # HorizSync source: edid, VertRefresh source: edid
              Identifier     "Monitor0"
              VendorName     "Unknown"
              ModelName      "LG Electronics 24MP55"
              HorizSync       30.0 - 83.0
              VertRefresh     56.0 - 75.0
              Option         "DPMS"
          EndSection

          Section "Device"
              Identifier     "Device0"
              Driver         "nvidia"
              VendorName     "NVIDIA Corporation"
              BoardName      "NVIDIA GeForce GTX 1050"
          EndSection

          Section "Screen"
              Identifier     "Screen0"
              Device         "Device0"
              Monitor        "Monitor0"
              DefaultDepth    24
              Option         "Stereo" "0"
              Option         "nvidiaXineramaInfoOrder" "DVI-D-0"
              Option         "metamodes" "DVI-D-0: nvidia-auto-select +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On, AllowGSYNC=Off}, HDMI-0: nvidia-auto-select +1920+0"
              Option         "SLI" "Off"
              Option         "MultiGPU" "Off"
              Option         "BaseMosaic" "off"
              SubSection     "Display"
                  Depth       24
              EndSubSection
          EndSection
        ''
      else
        "";
  };
  _args = { inherit value args; };
in
nixosModule _args
