# Here is global, all global key cant conflicts with other hotkeys
quit = ['ctrl+q', '']
#
list_up = ['k', '']
list_down = ['j', '']
#
pinned_directory = ['P', '']
#
close_file_panel = ['q', '']
create_new_file_panel = ['n', '']
#
next_file_panel = ['tab', '']
previous_file_panel = ['shift+tab', '']
focus_on_process_bar = ['ctrl+p', '']
focus_on_side_bar = ['b', '']
focus_on_metadata = ['ctrl+m', '']
#
change_panel_mode = ['m', '']
open_help_menu = ['?', '']
#
file_panel_directory_create = ['f', '']
file_panel_file_create = ['c', '']
file_panel_item_rename = ['r', '']
paste_item = ['ctrl+v', '']
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
toggle_dot_file = ['.', '']
#
oepn_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
#
# These hotkeys do not conflict with any other keys (including global hotkey)
cancel = ['ctrl+c', 'esc']
confirm = ['enter', '']
#
# Here is normal mode hotkey you can conflicts with other mode (cant conflicts with global hotkey)
delete_item = ['ctrl+d', '']
select_item = ['enter', 'l']
parent_directory = ['-', '']
copy_single_item = ['ctrl+c', '']
cut_single_item = ['ctrl+x', '']
search_bar = ['/', '']
command_line = ['/', '']
#
# Here is select mode hotkey you can conflicts with other mode (cant conflicts with global hotkey)
file_panel_select_mode_item_single_select = ['enter', 'l']
file_panel_select_mode_item_select_down = ['shift+down', 'J']
file_panel_select_mode_item_select_up = ['shift+up', 'K']
file_panel_select_mode_item_delete = ['ctrl+d', 'delete']
file_panel_select_mode_item_copy = ['ctrl+c', '']
file_panel_select_mode_item_cut = ['ctrl+x', '']
file_panel_select_all_item = ['ctrl+a', '']
