[project]
name = "douyin-downloader"
version = "2025.03.07"
dependencies = [
  "requests",
  "pyyaml",
  "rich",
  "aiohttp",
  "python-json-logger",
  "python-dateutil",
  "requests-toolbelt",
  "tqdm",
]
requires-python = ">= 3.8"

[project.scripts]
douyin-downloader = "DouYinCommand:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["utils", "apiproxy", "DouYinCommand.py"]
