lvim.colorscheme = "tokyonight" -- set to a custom theme, tokyonight or lunar
lvim.log.level = "warn"
lvim.format_on_save = false
lvim.leader = "space"
lvim.transparent_window = false -- enable/disable transparency
lvim.reload_config_on_save = true

lvim.plugins = {}
lvim.user_plugins = {
  language = {
    ansible = true,
    c = false, -- clangd
    cpp = false, -- clangd
    csv = false, -- csv support true
    go = { active = false, debug = false, gopher = false },
    haskhell = false,
    java = { active = false, debug = false },
    javascript = { string = false, npm = false },
    typecript = false,
    json = { quickfix = false },
    lua = { string = false },
    markdown = {
      paste = { first = false, second = true },
      preview_cli = true,
      preview_web = { first = true, second = false },
      quick_edit = true,
      support = true,
      hl_code = { first = false, second = false },
      table_mode = false,
      better_view = true,
    },
    lisp = true,
    neorg = false,
    python = { debug = true, string = false, venv = { first = false, second = false } },
    rust = { active = false, crates = false },
    yaml = { quickfix = false },
    typst = false,
    sql = false,
    cmake = false,
    flutter = false,
    latex = false,
    r = false,
  },
  edit = {
    format = { conform = true, pangu = false },
    compile = { compiler = true, overseer = true },
    comment = { box = true, toggle = { mini = true }, todo = true },
    quickfix = true,
    highlight = {
      color = true,
      brackets = { pair = true, rainbow = { first = true, second = false } },
      line = { mode = false },
      cmd = { range = true },
      word = { first = true, second = false, third = false, fourth = false },
      block = false,
      headlines = false,
      undo = { lua = false, deno = false },
      statuscol = false,
      cursor = { first = false },
      reactive = false,
    },
    completion = {
      cmp = {
        active = true,
        cmd = true,
        fuzzy = true,
        date = true,
        grep = true,
        tabnine = true,
        signature = false,
        codeium = false,
        icons = false,
      },
    },
    image = { image = true, hologram = false },
    window = { border = true, focus = false, animation = false, picker = false, zoom = true, visual_split = true },
    align = true,
    autosave = { first = true, second = false },
    bufferline = { bufferline = { active = true, cycle = false }, tabby = false },
    ca_cx = { dial = true, cycle = false, compter = false, toggler = false },
    doc = { generator = { first = true, second = false }, cheat = true, devdocs = true, zeal = true },
    fold = { save = true, active = false, preview = { first = true, second = false, third = false } },
    inject_type = false,
    jump = {
      flash = true,
      square_brackets = true,
      flit = false,
      hop = false,
      leap = false,
      sj = false,
      treesj = false,
    },
    jumplist = false,
    backout = true,
    macro = { recorder = false, macrobatics = false },
    hover = false,
    mark = { bookmarks = true, marks = true },
    multicursor = true,
    navigation = { grapple = true },
    moveline = { first = false, second = false },
    nocopy = false,
    operators = true,
    exchange = true,
    replace = { spectre = false, ssr = false, motion = false },
    search = {
      fzf = false,
      fzf_lua = false,
      telescope = { emoji = true, files = false, media = false, undo = false, mapper = false },
      legendary = false,
      clap = false,
      motion = true,
    },
    session = {
      auto = { first = false, second = false, third = false, fourth = true, fifth = false },
      manager = false,
      half_auto = { first = false, second = false },
      lastplace = { first = false, second = false },
    },
    share = {
      carbon = { nvim = true, vim = false },
      shot = true,
      pastebin = true,
      rayso = true,
      silicon = true,
      codesnap = true,
      freeze = true,
    },
    split_join = { mini = false },
    surround = { first = false, second = true },
    swap = { node = false },
    template = { new = true, nvim = true, vim = true },
    undo = { forever = true, tree = { first = true, second = false } },
    textobj = { mini = true, targets = false },
    tabout = true,
    git = {
      branch_viewer = true,
      commit = { first = true, second = false },
      diff = true,
      gitignore = false,
      link = true,
      neogit = false,
      fugitive = true,
      timemachine = true,
      messenger = true,
    },
    misc = {
      flatten = true,
      project_note = false,
      screenshot = true,
      extra = false,
      notification = { noice = true },
      stabilize = false,
      dressing = true,
      hlchunk = true,
    },
    file_manager = {
      nnn = false,
      terminal = false,
      sidebar = { neo_tree = false, netman = false },
      lf = { nvim = false, vim = true },
      broot = { vim = true },
      nvimtree = false,
    },
    lsp = {
      go_to = true,
      rename = false,
      hints = { inlay = true, args = true },
      diagnostics = {
        inline = false,
        inline_autocmd = false,
        underline = false,
        dashbroad = true,
        mouse_hover = false,
        hover_autocmd = true,
        troublesum = false,
        murmur = false,
      },
      code_action = { menu = false, hint = false },
      lint = true,
      import = true,
      output = true,
      reference = { symbol = true, corn = false, lens = false },
      progress_bar = false,
      gc = false,
      formatter_wrapper = false,
      enhance = false,
      null_ls = false,
    },
    treesitter = {
      highlight = true,
      context_pair = true,
      regex = false,
      context = { first = true, second = false },
      endwise = true,
      autotag = true,
      textobj = { first = false, second = false },
      swap = { sibling = true },
      setter = true,
      tab = false,
      kakoune = false,
    },
    cmd = {
      norm = true,
      sort = true,
      align = false,
      peek = true,
      lua_sub = true,
      search_highlight = false,
    },
    test = false,
    refactor = true,
    scrollbar = { satellite = false, scrollbar = false },
    runner = true,
    statuscol = false,
    outline = { aerial = false, symbol = false, minimap = false },
    text_case = false,
    translate = true,
    dim = { first = true, second = false },
    open_typo = true,
    autopair = { ultimate = true },
    yank = { first = false, second = false, third = false },
    zen = { first = true, second = false },
    winbar = {
      incline = { active = true, searchcount = false, lsp = true }, -- winbar
      winbar = false,
    },
    attempt = false,
    autoclose = false,
    aw_watcher = false,
    esc = false,
    scroll = { first = false, second = false },
    conceal = false,
    buffer = { cycle = false, explorer = true },
    dashboard = { sidebar = false, drop = false },
    duplicate = false,
    filetype = false,
    http = false,
    line = { numbers = false },
    spider = false,
    discord = false,
    project_manager = false,
    registers = { dashboard = false },
    sound = false,
    scope = { first = false, second = false, third = false },
    substitute = false,
    note = { telekasten = false },
    typos = false,
    uuid = false,
    AI = { tabby = false },
    tmux = false,
    wf = false,
    zk = false,
    terminal = true,
    message = true,
    tips = false,
  },
  package_manager = { mason = { auto = { first = true, second = false } } },
  time_based_themes = false,
  theme = { astro = { nightfox = false } },
  auto_stars = false,
}

lvim.builtin.alpha.active = true
lvim.builtin.breadcrumbs.active = true
lvim.builtin.bufferline.active = lvim.user_plugins.edit.bufferline.bufferline.active
lvim.builtin.dap.active = true
lvim.builtin.terminal.active = true
lvim.builtin.which_key.active = true
lvim.builtin.indentlines.active = false
lvim.builtin.cmp.active = true

lvim.builtin.autopairs.active = false
lvim.builtin.comment.active = false
lvim.builtin.illuminate.active = false
lvim.builtin.lir.active = false -- a simple file manager
lvim.builtin.nvimtree.active = lvim.user_plugins.edit.file_manager.nvimtree -- file explorer

require("plugins").config()
require("themes").config()
require("configs").config()
