#! /usr/bin/env nix-shell
#! nix-shell -i python3 -p python3Packages.pandas

import sqlite3
from enum import Enum

import pandas as pd


class Waiting_Status(Enum):
    WAITING = 1
    DONE = 2
    NOT_PACKAGED = 3
    REMOVED = 4


class Types(Enum):
    PACKAGE = 1
    MODULE = 2


class Categories(Enum):
    MUSIC = 1
    NIX = 2
    SHELL = 3
    DEV = 4
    SYSTEM = 5
    GIT = 6
    WEB = 7
    NETWORK = 8
    DOCKER = 9
    AUDIO = 10
    SHARE = 11
    DOC = 12
    IMAGE = 13
    ENCRYPT = 14
    FONT = 15
    GAME = 16
    VIDEO = 17
    DOWNLOAD = 18
    PROXY = 19
    FUN = 20


with sqlite3.connect("waiting.db") as conn:
    cursor = conn.cursor()
    cursor.execute(
        """
        pragma foreign_keys
        = on
        ;
    """
    )

    cursor.execute(
        """
        CREATE TABLE waiting_status (
            id integer PRIMARY KEY,
            name text NOT NULL
        );
    """
    )

    cursor.execute(
        """
        CREATE TABLE categories (
            id integer PRIMARY KEY,
            name text NOT NULL
        );
    """
    )

    cursor.execute(
        """
        CREATE TABLE types (
            id integer PRIMARY KEY,
            name text NOT NULL
        );
    """
    )

    cursor.execute(
        """
        CREATE TABLE packages (
            id integer PRIMARY KEY,
            name text NOT NULL UNIQUE,
            description text NOT NULL,
            url text NOT NULL,
            categories integer NOT NULL,
            waiting_status integer NOT NULL,
            added_date text NOT NULL,
            finished_date text,
            type integer NOT NULL DEFAULT 1,
            FOREIGN KEY (waiting_status)
            REFERENCES waiting_status (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            FOREIGN KEY (categories)
            REFERENCES categories (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            FOREIGN KEY (type)
            REFERENCES types (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
        );
    """
    )

    cursor.execute(
        f"""
        CREATE VIEW v_packages
        AS
        SELECT '[[' || url || '][' || name || ']]' AS package, description FROM packages WHERE waiting_status = {Waiting_Status.WAITING.value} ORDER BY added_date;
    """
    )

    cursor.execute(
        f"""
        CREATE VIEW v_need_packaging
        AS
        SELECT '[[' || url || '][' || name || ']]' AS package, description FROM packages WHERE waiting_status = {Waiting_Status.NOT_PACKAGED.value} ORDER BY added_date;
    """
    )

    cursor.execute(
        f"""
        INSERT INTO waiting_status  VALUES ({Waiting_Status.WAITING.value},'{Waiting_Status.WAITING.name}'), ({Waiting_Status.DONE.value},'{Waiting_Status.DONE.name}'), ({Waiting_Status.NOT_PACKAGED.value}, '{Waiting_Status.NOT_PACKAGED.name}'), ({Waiting_Status.REMOVED.value}, '{Waiting_Status.REMOVED.name}');
    """
    )

    cursor.execute(
        f"""
        INSERT INTO types VALUES ({Types.PACKAGE.value},'{Types.PACKAGE.name}'), ({Types.MODULE.value},'{Types.MODULE.name}');
    """
    )

    cursor.execute(
        f"""
        INSERT INTO categories VALUES
        ({Categories.MUSIC.value},'{Categories.MUSIC.name}'),
        ({Categories.NIX.value},'{Categories.NIX.name}'),
        ({Categories.SHELL.value},'{Categories.SHELL.name}'),
        ({Categories.DEV.value},'{Categories.DEV.name}'),
        ({Categories.SYSTEM.value},'{Categories.SYSTEM.name}'),
        ({Categories.GIT.value},'{Categories.GIT.name}'),
        ({Categories.WEB.value},'{Categories.WEB.name}'),
        ({Categories.NETWORK.value},'{Categories.NETWORK.name}'),
        ({Categories.DOCKER.value},'{Categories.DOCKER.name}'),
        ({Categories.AUDIO.value},'{Categories.AUDIO.name}'),
        ({Categories.SHARE.value},'{Categories.SHARE.name}'),
        ({Categories.DOC.value},'{Categories.DOC.name}'),
        ({Categories.IMAGE.value},'{Categories.IMAGE.name}'),
        ({Categories.ENCRYPT.value},'{Categories.ENCRYPT.name}'),
        ({Categories.FONT.value},'{Categories.FONT.name}'),
        ({Categories.GAME.value},'{Categories.GAME.name}'),
        ({Categories.VIDEO.value},'{Categories.VIDEO.name}'),
        ({Categories.DOWNLOAD.value},'{Categories.DOWNLOAD.name}'),
        ({Categories.PROXY.value},'{Categories.PROXY.name}');
    """
    )


with sqlite3.connect("waiting.db") as conn:
    df = pd.DataFrame(
        [
            [
                "id3",
                "ID3 mass tagger",
                "https://github.com/squell/id3",
                Categories.MUSIC,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "nix-editor",
                "A simple rust program to edit NixOS configuration files with just a command",
                "https://github.com/snowfallorg/nix-editor",
                Categories.NIX,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "jumper",
                "Accurate and fast files/directories jumper",
                "https://github.com/homerours/jumper",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "schemat",
                "Code formatter for Scheme, Lisp, and any S-expressions",
                "https://github.com/raviqqe/schemat",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "keyviz",
                "Keyviz is a free and open-source tool to visualize your keystrokes ⌨️ and 🖱️ mouse actions in real-time.",
                "https://github.com/mulaRahul/keyviz",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "git-pr",
                "the easiest git collaboration tool",
                "https://github.com/picosh/git-pr",
                Categories.GIT,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "cvtek",
                "📄 Craft your Resume/CV using TOML",
                "https://github.com/varbhat/cvtek",
                Categories.WEB,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "aicommit2",
                "A Reactive CLI that generates git commit messages with Ollama, ChatGPT, Gemini, Claude, Mistral and other AI",
                "https://github.com/tak-bro/aicommit2",
                Categories.GIT,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "AngryOxide",
                "802.11 Attack Tool",
                "https://github.com/Ragnt/AngryOxide",
                Categories.NETWORK,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "ducker",
                "A slightly quackers Docker TUI based on k9s 🦆",
                "https://github.com/robertpsoane/ducker",
                Categories.DOCKER,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "simplemoji",
                "Fast Application for look your amazing emojis write in Rust",
                "https://github.com/SergioRibera/simplemoji",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "voicevox",
                "無料で使える中品質なテキスト読み上げ・歌声合成ソフトウェア",
                "https://voicevox.hiroshiba.jp/",
                Categories.AUDIO,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "otree",
                "A command line tool to view objects (JSON/YAML/TOML) in TUI tree widget.",
                "https://github.com/fioncat/otree",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "azote",
                "Wallpaper manager for wlroots-based compositors and some other WMs",
                "https://github.com/nwg-piotr/azote",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "cloudpan189-go",
                "天翼云盘命令行客户端(CLI)，基于 GO 语言实现",
                "https://github.com/tickstep/cloudpan189-go",
                Categories.SHARE,
                "05/17/2025",
                None,
                Waiting_Status.REMOVED,
                Types.PACKAGE,
            ],
            [
                "cppman",
                "C++ 98/11/14 manual pages for Linux/MacOS",
                "https://github.com/aitjcize/cppman",
                Categories.DOC,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "split-monitor-workspaces",
                "A small Hyprland plugin to provide awesome-like workspace behavior",
                "https://github.com/Duckonaut/split-monitor-workspaces",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "sss",
                "SSS (Super ScreenShot) is a WIP: CLI/Lib to take amazing screenshot of code or screen",
                "https://github.com/SergioRibera/sss",
                Categories.IMAGE,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "Diagon",
                "Interactive ASCII art diagram generators. 🌟",
                "https://github.com/ArthurSonzogni/Diagon",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "Kryptor",
                "A simple, modern, and secure encryption and signing tool that aims to be a better version of age and Minisign.",
                "https://github.com/samuel-lucas6/Kryptor",
                Categories.ENCRYPT,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "gfie",
                "Greenfish Icon Editor Pro (GFIE Pro) is a powerful freeware image editor, especially suitable for creating icons, cursors, animations and icon libraries.",
                "http://greenfishsoftware.org/gfie.php",
                Categories.IMAGE,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "scooter",
                "Interactive find and replace in the terminal",
                "https://github.com/thomasschafer/scooter",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "deskflow",
                "Deskflow lets you share one mouse and keyboard between multiple computers on Windows, macOS and Linux. Its like a software KVM (but without video).",
                "https://github.com/deskflow/deskflow",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "lla",
                "blazing fast `ls` replacement with superpowers",
                "https://github.com/triyanox/lla",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "ahoy",
                "Create self-documenting cli programs from YAML files. Easily wrap bash, grunt, npm, docker, (anything) to standardize your processes and make the lives of the people working on your project better.",
                "https://github.com/ahoy-cli/ahoy",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "opener",
                "Open URL in your local web browser from the SSH-connected remote environment.",
                "https://github.com/superbrothers/opener",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "InputPlumber",
                "Open source input router and remapper daemon for Linux",
                "https://github.com/ShadowBlip/InputPlumber",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "mago",
                "Mago is a toolchain for PHP that aims to provide a set of tools to help developers write better code.",
                "https://github.com/carthage-software/mago",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "ffpb",
                "A progress bar for ffmpeg. Yay !",
                "https://github.com/althonos/ffpb",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "awk-language-server",
                "Language Server for AWK and associated VSCode client extension",
                "https://github.com/Beaglefoot/awk-language-server",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "Lilex",
                "🤘Open source programming font",
                "https://github.com/mishamyrt/Lilex",
                Categories.FONT,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "copywrite",
                "Automate copyright headers and license files at scale",
                "https://github.com/hashicorp/copywrite",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "primitive",
                "Reproducing images with geometric primitives.",
                "https://github.com/fogleman/primitive",
                Categories.IMAGE,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "textidote",
                "Spelling, grammar and style checking on LaTeX documents",
                "https://github.com/sylvainhalle/textidote",
                Categories.DOC,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "urlfinder",
                "A high-speed tool for passively gathering URLs, optimized for efficient and comprehensive web asset discovery without active scanning.",
                "https://github.com/projectdiscovery/urlfinder",
                Categories.NETWORK,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "moxide",
                "A tmux session manager with a modular config",
                "https://github.com/dlurak/moxide",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "suyu",
                "Experimental Nintendo Switch emulator written in C++",
                "https://suyu.dev",
                Categories.GAME,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "astroterm",
                "A planetarium for your terminal! Explore stars, planets, constellations, and more, all rendered right in the command line—no telescope required. ✨🪐",
                "https://github.com/da-luce/astroterm/",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "isd",
                "isd (interactive systemd) – a better way to work with systemd units",
                "https://github.com/isd-project/isd",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "flow",
                "Flow Control: a programmers text editor",
                "https://github.com/neurocyte/flow",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "watcher",
                "Filesystem watcher. Works anywhere. Simple, efficient and friendly.",
                "https://github.com/e-dant/watcher",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "rustic",
                "rustic - fast, encrypted, and deduplicated backups powered by Rust",
                "https://github.com/rustic-rs/rustic",
                Categories.ENCRYPT,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "inori",
                "mpd client",
                "https://github.com/eshrh/inori",
                Categories.MUSIC,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "itgmania",
                "A fork of StepMania 5.1, improved for the post-ITG community!",
                "https://www.itgmania.com/",
                Categories.GAME,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "patchy",
                "A tool which makes it easy to declaratively manage personal forks by automatically merging pull requests",
                "https://github.com/nik-rev/patchy",
                Categories.GIT,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "migrate-to-uv",
                "migrate-to-uv migrates a project to uv from another package manager.",
                "https://mkniewallner.github.io/migrate-to-uv/",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "SeaGOAT",
                "A code search engine for the AI age.",
                "https://kantord.github.io/SeaGOAT/latest/",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "zipline",
                "A ShareX/file upload server that is easy to use, packed with features, and with an easy setup!",
                "https://github.com/diced/zipline",
                Categories.SHARE,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "ffizer",
                "ffizer is a files and folders initializer / generator. Create any kind (or part) of project from template.",
                "https://github.com/ffizer/ffizer",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "gssg",
                "A gemini static site generator",
                "https://git.sr.ht/~gsthnz/gssg",
                Categories.WEB,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "PowerShellEditorServices",
                "Common platform for PowerShell development support in any editor or application",
                "https://github.com/PowerShell/PowerShellEditorServices",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "tmux-which-key",
                "Tmux plugin that allows users to select actions from a customizable popup menu",
                "https://github.com/alexwforsythe/tmux-which-key",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "readeck",
                "Readeck is a simple web application that lets you save the precious readable content of web pages you like and want to keep forever.",
                "https://codeberg.org/readeck/readeck",
                Categories.WEB,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "PowerStation",
                "Open source TDP control and performance daemon with DBus interface",
                "https://github.com/ShadowBlip/PowerStation",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "jellyfin-tui",
                "🪼 Music streaming client for the terminal",
                "https://github.com/dhonus/jellyfin-tui",
                Categories.VIDEO,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "fum",
                "A fully customizable tui-based mpris music client.",
                "https://github.com/qxb3/fum",
                Categories.MUSIC,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "sourcegit",
                "Windows/macOS/Linux GUI client for GIT users",
                "https://github.com/sourcegit-scm/sourcegit",
                Categories.GIT,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "clock-rs",
                "clock-rs - A clock for your terminal!",
                "https://github.com/Oughie/clock-rs",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "nix-search-tv",
                "Fuzzy search for Nix packages.",
                "https://github.com/3timeslazy/nix-search-tv",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "xan",
                "The CSV magician",
                "https://github.com/medialab/xan",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "tooling-language-server",
                "A language server for tools & package managers",
                "https://github.com/filiptibell/tooling-language-server",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "telegram-integration",
                "Memogram is an easy to use integration service for syncing messages and images from a Telegram bot into your Memos.",
                "https://github.com/usememos/telegram-integration",
                Categories.WEB,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "exercism-cli-fish-wrapper",
                "A fish wrapper for the Exercism CLI",
                "https://github.com/glennj/exercism-cli-fish-wrapper",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "posting",
                "The API client that lives in your terminal.",
                "https://posting.sh/",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "clashtui",
                "Mihomo (Clash.Meta) TUI Client",
                "https://github.com/JohanChane/clashtui",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "mpls",
                "Markdown Preview Language Server",
                "https://github.com/mhersson/mpls",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "flamelens",
                "Flamegraph viewer in the terminal",
                "https://github.com/YS-L/flamelens",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "t3",
                "Next generation tee with colorized output streams and precise time stamping",
                "https://github.com/flox/t3",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "umu-launcher",
                "",
                "https://github.com/Open-Wine-Components/umu-launcher",
                Categories.GAME,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "xdg-desktop-portal-termfilechooser",
                "xdg-desktop-portal backend for choosing files with your favorite file chooser",
                "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "ni",
                "💡 Use the right package manager",
                "https://github.com/antfu-collective/ni",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "jinja-lsp",
                "Language Server for jinja",
                "https://github.com/uros-5/jinja-lsp",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "biliup-rs",
                "命令行投稿(B站)和视频下载工具，提供多种登录方式，支持多p。",
                "https://github.com/biliup/biliup-rs",
                Categories.DOWNLOAD,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "world-wall-clock",
                "world-wall-clock is a TUI application that provides a multi-timezone graphical clock in a terminal environment.",
                "https://github.com/ddelabru/world-wall-clock",
                Categories.SHELL,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "aonsoku",
                "A modern desktop client for Navidrome/Subsonic servers built with React and Rust.",
                "https://github.com/victoralvesf/aonsoku",
                Categories.MUSIC,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "simple-completion-language-server",
                "Language server to enable word completion and snippets for Helix editor",
                "https://github.com/estin/simple-completion-language-server",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "taze",
                "🥦 A modern cli tool that keeps your deps fresh",
                "https://github.com/antfu-collective/taze",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "tray-tui",
                "System tray in your terminal",
                "https://github.com/Levizor/tray-tui",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "hot-resize",
                "A tool for hot resizing (without reboot) disk partitions and filesystems.",
                "https://github.com/liberodark/hot-resize",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "N_m3u8DL-RE",
                "Cross-Platform, modern and powerful stream downloader for MPD/M3U8/ISM. English/简体中文/繁體中文.",
                "https://github.com/nilaoda/N_m3u8DL-RE",
                Categories.DOWNLOAD,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "kubexporter",
                "📥 easily export your k8s resources",
                "https://github.com/bakito/kubexporter",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "pandoc-mustache",
                "Pandoc filter for variable substitution using Mustache syntax",
                "https://github.com/michaelstepner/pandoc-mustache",
                Categories.DEV,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "rofi-network-manager",
                "🛠 Manage wifi and ethernet with rofi.",
                "https://github.com/meowrch/rofi-network-manager",
                Categories.SYSTEM,
                "05/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "nix-heuristic-gc",
                "A more discerning cousin of nix-collect-garbage",
                "https://github.com/risicle/nix-heuristic-gc",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "UDPspeeder",
                "A Tunnel which Improves your Network Quality on a High-latency Lossy Link by using Forward Error Correction, possible for All Traffics(TCP/UDP/ICMP)",
                "https://github.com/wangyu-/UDPspeeder",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "tmux-sessionx",
                "A Tmux session manager, with preview, fuzzy finding, and MORE",
                "https://github.com/omerxx/tmux-sessionx",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "bunster",
                "Compile shell scripts to static binaries.",
                "https://github.com/yassinebenaid/bunster",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "guesswidth",
                "Guess the width (fwf)  output without delimiters in commands that output to the terminal.",
                "https://github.com/noborus/guesswidth",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "bed",
                "Binary editor written in Go",
                "https://github.com/itchyny/bed",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "osc",
                "Access the system clipboard from anywhere using the ANSI OSC52 sequence",
                "https://github.com/theimpostor/osc",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "hydra",
                "Hydra Launcher is an open-source gaming platform created to be the single tool that you need",
                "https://github.com/hydralauncher/hydra",
                Categories.GAME,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "textLSP",
                "Language server for text spell and grammar check with various tools.",
                "https://github.com/hangyav/textLSP",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "uv-sort",
                "Sort uvs dependencies alphabetically",
                "https://github.com/ninoseki/uv-sort",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "vim-apathy",
                "apathy.vim: Set the path option for miscellaneous file types",
                "https://github.com/tpope/vim-apathy/",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "mdq",
                "like jq but for Markdown: find specific elements in a md doc",
                "https://github.com/yshavit/mdq",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "jellyflix",
                "Jellyfix is an easy-to-use Jellyfin client for movies and shows. It's cross-platform and supports Mobile (iOS, Android) and Desktop (Windows, Mac, Linux).",
                "https://github.com/jellyflix-app/jellyflix",
                Categories.VIDEO,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "tparted",
                "Text-based user interface (TUI) frontend for parted: A simple, user-friendly utility for creating, reorganizing, and deleting disk partitions, based on Turbo/Free Vision application framework.",
                "https://github.com/Kagamma/tparted",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "proftpd",
                "Highly configurable GPL-licensed FTP server software",
                "http://www.proftpd.org/",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "clive",
                "⚡ Automates terminal operations.",
                "https://github.com/koki-develop/clive",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "docker-color-output",
                "🎨 Docker color output which improves readability.",
                "https://github.com/devemio/docker-color-output",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "bpfilter",
                "An eBPF-based packet filtering framework.",
                "https://bpfilter.io/",
                Categories.NETWORK,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "go-mod-upgrade",
                "Update outdated Go dependencies interactively",
                "https://github.com/oligot/go-mod-upgrade/",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "awesome-wm-widgets",
                "Widgets for Awesome Window Manager",
                "https://github.com/streetturtle/awesome-wm-widgets",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "systemd-language-server",
                "Language Server for Systemd unit files",
                "https://github.com/psacawa/systemd-language-server",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "docfx",
                "Static site generator for .NET API documentation.",
                "https://github.com/dotnet/docfx",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "docker-vackup",
                "Script to easily backup and restore docker volumes",
                "https://github.com/BretFisher/docker-vackup",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "soundalike",
                "soundalike is a command-line program that tries to find similar audio files by comparing acoustic fingerprints. Its main focus is identifying duplicate songs in music collections.",
                "https://codeberg.org/derat/soundalike",
                Categories.AUDIO,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "bsky",
                "A cli application for bluesky social",
                "https://github.com/mattn/bsky",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "pavolctld",
                "pavolctld is a minimal volume control daemon for PulseAudio written in C.",
                "https://tjkeller.xyz/projects/pavolctld/",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "Gokapi",
                "Lightweight selfhosted Firefox Send alternative without public upload. AWS S3 supported.",
                "https://github.com/Forceu/Gokapi",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "etterna",
                "Advanced cross-platform rhythm game focused on keyboard play",
                "https://etternaonline.com/",
                Categories.GAME,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "lon",
                "Lock & update Nix dependencies",
                "https://github.com/nikstur/lon",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "git-who",
                "Git blame for file trees",
                "https://github.com/sinclairtarget/git-who",
                Categories.GIT,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "git-dumper",
                "A tool to dump a git repository from a website",
                "https://github.com/arthaud/git-dumper",
                Categories.GIT,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "dioxionary",
                "StarDict in Rust! 使用 离线 / 在线 词典在终端中查单词、背单词！",
                "https://github.com/vaaandark/dioxionary",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "nixpkgs-track",
                "📦 Track where Nixpkgs pull requests have reached.",
                "https://github.com/uncenter/nixpkgs-track",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "roomarranger",
                "Room Arranger is a 3D room / apartment / floor planner with a simple user interface.",
                "https://www.roomarranger.com/",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "nyaa",
                "A tui tool for browsing and downloading torrents",
                "https://github.com/Beastwick18/nyaa",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "mouseless",
                "A replacement for the mouse in Linux",
                "https://github.com/jbensmann/mouseless",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "cliflux",
                "A terminal client for Miniflux RSS reader",
                "https://github.com/spencerwi/cliflux",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "go-grip",
                "Preview Markdown files locally before committing them.",
                "https://github.com/chrishrb/go-grip",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "omnix",
                "Nix companion to improve developer experience",
                "https://omnix.page",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "bashunit",
                "A simple testing library for bash scripts. Test your bash scripts in the fastest and simplest way.",
                "https://github.com/TypedDevs/bashunit",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "better-commits",
                "A CLI for creating better commits following the conventional commits specification",
                "https://github.com/Everduin94/better-commits",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "runmd",
                "Executable markdown files",
                "https://github.com/broofa/runmd",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "godns",
                "A dynamic DNS client tool that supports AliDNS, Cloudflare, Google Domains, DNSPod, HE.net & DuckDNS & DreamHost, etc, written in Go.",
                "https://github.com/TimothyYe/godns",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "KrillinAI",
                " A video translation and dubbing tool powered by LLMs, offering professional-grade translations and one-click full-process deployment. It can generate content optimized for platforms like YouTube，TikTok, and Shorts.  基于AI大模型的视频翻译和配音工具，专业级翻译，一键部署全流程，可以生成适配抖音，小红书，哔哩哔哩，视频号，TikTok，Youtube Shorts等形态的内容",
                "https://github.com/krillinai/KrillinAI",
                Categories.VIDEO,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "ferrishot",
                "A powerful screenshot app written in Rust 📸🦀",
                "https://github.com/nik-rev/ferrishot",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "markdown-code-runner",
                "Execute and optionally rewrite code blocks in Markdown files based on external commands",
                "https://github.com/drupol/markdown-code-runner",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "codex",
                "Lightweight coding agent that runs in your terminal",
                "https://github.com/openai/codex",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "g-ls",
                "powerful and cross-platform ls 🌈",
                "https://github.com/Equationzhao/g",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "zashboard",
                "A Dashboard Using Clash API",
                "https://github.com/Zephyruso/zashboard",
                Categories.PROXY,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "ggh",
                "Recall your SSH sessions (also search your SSH config file)",
                "https://github.com/byawitz/ggh",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "hevi",
                "Hex viewer",
                "https://github.com/Arnau478/hevi",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "speed-cloudflare-cli",
                "📈 Measure the speed and consistency of your internet connection using speed.cloudflare.com",
                "https://github.com/KNawm/speed-cloudflare-cli",
                Categories.NETWORK,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "goshs",
                "A SimpleHTTPServer written in Go, enhanced with features and with a nice design - https://goshs.de",
                "https://github.com/patrickhener/goshs",
                Categories.SHARE,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "codebook",
                "Spell Checker for Code",
                "https://github.com/blopker/codebook",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "just-lsp",
                "A language server for just",
                "https://github.com/terror/just-lsp",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "animeko",
                "集找番、追番、看番的一站式弹幕追番平台，云收藏同步 (Bangumi)，离线缓存，BitTorrent，弹幕云过滤。100% Kotlin/Compose Multiplatform",
                "https://github.com/open-ani/animeko",
                Categories.VIDEO,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "redu",
                "ncdu for your restic repository",
                "https://github.com/drdo/redu",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "cookcli",
                "Command line program which provides a suite of tools to create shopping lists and maintain recipes. ",
                "https://github.com/cooklang/cookcli",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "karakeep",
                "A self-hostable bookmark-everything app (links, notes and images) with AI-based automatic tagging and full text search",
                "https://github.com/karakeep-app/karakeep",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "scspell",
                "Spell checker for source code",
                "https://github.com/myint/scspell",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "Beyond-All-Reason",
                "Main game repository for Beyond All Reason.",
                "https://github.com/beyond-all-reason/Beyond-All-Reason",
                Categories.GAME,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "qwertone",
                "Turns your PC into music instrument",
                "https://gitlab.com/azymohliad/qwertone",
                Categories.MUSIC,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "yarr",
                "yet another rss reader",
                "https://github.com/nkanaev/yarr",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "regname",
                "Mass renamer TUI written in Rust",
                "https://github.com/linkdd/regname?tab=readme-ov-file",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "repro-env",
                "Dependency lockfiles for reproducible build environments 📦🔒",
                "https://github.com/kpcyrd/repro-env",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "wrkflw",
                "Validate and execute GitHub Actions workflows locally.",
                "https://github.com/bahdotsh/wrkflw",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "mdsf",
                "Format markdown code blocks using your favorite tools",
                "https://github.com/hougesen/mdsf",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "OliveTin",
                "OliveTin gives safe and simple access to predefined shell commands from a web interface. ",
                "https://github.com/OliveTin/OliveTin",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "PySceneDetect",
                ":movie_camera: Python and OpenCV-based scene cut/transition detection program & library.",
                "https://github.com/Breakthrough/PySceneDetect",
                Categories.VIDEO,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "jqfmt",
                "like gofmt, but for jq",
                "https://github.com/noperator/jqfmt",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "warehouse",
                "A versatile toolbox for viewing flatpak info, managing user data, and batch managing installed flatpaks",
                "https://github.com/flattool/warehouse",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "goverter",
                "Generate type-safe Go converters by defining function signatures.",
                "https://github.com/jmattheis/goverter",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "bootdev",
                "A CLI used to complete coding challenges and lessons on Boot.dev",
                "https://github.com/bootdotdev/bootdev",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "WindSend",
                "Quickly and securely sync clipboard, transfer files and directories between devices. 快速安全的同步剪切板，传输文件或文件夹",
                "https://github.com/doraemonkeys/WindSend",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "tiny-rdm",
                "Tiny RDM (Tiny Redis Desktop Manager) - A modern, colorful, super lightweight Redis GUI client for Mac, Windows, and Linux.",
                "https://github.com/tiny-craft/tiny-rdm",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "alisthelper",
                "Alist Helper is an application developed using Flutter, designed to simplify the use of the desktop version of alist. It can manage alist, allowing you to easily start and stop the alist program.",
                "https://github.com/Xmarmalade/alisthelper",
                Categories.SHARE,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "rexi",
                "Terminal UI for Regex Testing",
                "https://github.com/royreznik/rexi",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "nwg-icon-picker",
                "GTK icon chooser with a text search option",
                "https://github.com/nwg-piotr/nwg-icon-picker",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "coc-basedpyright",
                "Basedpyright extension for coc.nvim",
                "https://github.com/fannheyward/coc-basedpyright",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "pkl",
                "Configuration-as-code language with rich validation and tooling",
                "https://pkl-lang.org/",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "SkyEmu",
                "Game Boy Advance, Game Boy, Game Boy Color, and DS Emulator",
                "https://github.com/skylersaleh/SkyEmu",
                Categories.GAME,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "xnviewmp",
                "Efficient multimedia viewer, browser and converter",
                "https://www.xnview.com/en/xnviewmp/",
                Categories.IMAGE,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "nix-converter",
                "All-in-one converter configuration language to Nix and vice versa",
                "https://github.com/theobori/nix-converter",
                Categories.NIX,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "Poliedros",
                "Multi-type dice roller",
                "https://github.com/kriptolix/Poliedros",
                Categories.GAME,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "Bagels",
                "Powerful expense tracker that lives in your terminal.",
                "https://github.com/EnhancedJax/Bagels",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "megabasterd",
                "Yet another unofficial (and ugly) cross-platform MEGA downloader/uploader/streaming suite.",
                "https://github.com/tonikelope/megabasterd",
                Categories.SHARE,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "MeowPDF",
                "A PDF viewer for the Kitty terminal with GUI-like usage and Vim-like keybindings written in Rust",
                "https://github.com/monoamine11231/meowpdf",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "fancy-cat",
                "PDF reader for terminal emulators using the Kitty image protocol",
                "https://github.com/freref/fancy-cat",
                Categories.SHELL,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "go-import-lint",
                "Golang source code analyzer that checks imports order. It verifies that standard, current package, and vendor imports are separated by a line.",
                "https://github.com/hedhyw/go-import-lint",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "luau-lsp",
                "Language Server Implementation for Luau",
                "https://github.com/JohnnyMorganz/luau-lsp",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "gitsnip",
                "A CLI tool to download specific folders from a git repository.",
                "https://github.com/dagimg-dot/gitsnip/",
                Categories.GIT,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "typewriter",
                "Create documents with typst, the new markup-based typesetting system that is powerful and easy to learn.",
                "https://gitlab.gnome.org/JanGernert/typewriter",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "pgbackrest",
                "Reliable PostgreSQL Backup & Restore",
                "https://github.com/pgbackrest/pgbackrest",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "biff",
                "A command line tool for datetime arithmetic, parsing, formatting and more.",
                "https://github.com/BurntSushi/biff",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "typship",
                "A Typst package CLI tool",
                "https://github.com/sjfhsjfh/typship",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "outfieldr",
                "A TLDR client written in Zig",
                "https://gitlab.com/ve-nt/outfieldr",
                Categories.DOC,
                "05/18/2025",
                None,
                Waiting_Status.DONE,
                Types.PACKAGE,
            ],
            [
                "darkly",
                "A modern style for qt applications.",
                "https://github.com/Bali10050/Darkly",
                Categories.SYSTEM,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "uwu_colors",
                "a dead simple language server to colorize hex color strings via textDocument/documentColor",
                "https://codeberg.org/q60/uwu_colors",
                Categories.DEV,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "geminicommit",
                "CLI that writes git commit messages for you with Google Gemini AI ",
                "https://github.com/tfkhdyt/geminicommit",
                Categories.GIT,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "gorched",
                'Gorched is terminal based game written in Go inspired by "The Mother of all games" Scorched Earth',
                "https://github.com/zladovan/gorched",
                Categories.GAME,
                "05/18/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "kompanion",
                "a self hosted backend for bookworms, tightly coupled with KOReader",
                "https://github.com/vanadium23/kompanion",
                Categories.WEB,
                "05/18/2025",
                None,
                Waiting_Status.NOT_PACKAGED,
                Types.PACKAGE,
            ],
            [
                "mkbrr",
                "⚡ mkbrr is a tool to create, modify and inspect torrent files. Fast.",
                "https://github.com/autobrr/mkbrr",
                Categories.DOWNLOAD,
                "05/20/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "plant-it",
                "🪴 Self-hosted, open source gardening companion app",
                "https://github.com/MDeLuise/plant-it",
                Categories.WEB,
                "05/23/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "dix",
                "Diff Nix",
                "https://github.com/bloxx12/dix",
                Categories.DEV,
                "05/23/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "oci2git",
                "Introspecting Docker images as easy as using Git",
                "https://github.com/Virviil/oci2git",
                Categories.GIT,
                "05/23/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "lucida-downloader",
                "a multithreaded client for downloading music for free with https://lucida.to/.",
                "https://github.com/jelni/lucida-downloader",
                Categories.DOWNLOAD,
                "05/23/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "bkmr",
                "A Unified CLI Tool for Bookmark, Snippet, and Knowledge Management",
                "https://github.com/sysid/bkmr",
                Categories.SHELL,
                "05/24/2025",
                None,
                Waiting_Status.NOT_PACKAGED,
                Types.PACKAGE,
            ],
            [
                "nocjk",
                "Detect CJK text",
                "https://github.com/aethiopicuschan/nocjk",
                Categories.DEV,
                "05/24/2025",
                None,
                Waiting_Status.NOT_PACKAGED,
                Types.PACKAGE,
            ],
            [
                "zeitgrep",
                "sorted grep",
                "https://github.com/kantord/zeitgrep",
                Categories.SHELL,
                "05/24/2025",
                None,
                Waiting_Status.NOT_PACKAGED,
                Types.PACKAGE,
            ],
            [
                "mcat",
                "cat command for documents / images / videos and more!",
                "https://github.com/Skardyy/mcat",
                Categories.SHELL,
                "05/24/2025",
                None,
                Waiting_Status.NOT_PACKAGED,
                Types.PACKAGE,
            ],
            [
                "lexy",
                'Lexy is a lightweight CLI tool that fetches programming tutorials from "Learn X in Y Minutes" directly into your terminal. Quickly search, learn, and reference code examples without leaving your workflow.',
                "https://github.com/antoniorodr/lexy",
                Categories.DOC,
                "05/24/2025",
                None,
                Waiting_Status.NOT_PACKAGED,
                Types.PACKAGE,
            ],
            [
                "zlint",
                "A linter for the Zig programming language",
                "https://github.com/DonIsaac/zlint",
                Categories.DEV,
                "05/30/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "efibooteditor",
                "Boot Editor for (U)EFI based systems",
                "https://github.com/Neverous/efibooteditor",
                Categories.SYSTEM,
                "06/02/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "jellytui",
                "TUI Jellyfin Client using MPV",
                "https://github.com/tyrantlink/jellytui",
                Categories.VIDEO,
                "06/02/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "enroot",
                "A simple yet powerful tool to turn traditional container/OS images into unprivileged sandboxes.",
                "https://github.com/NVIDIA/enroot",
                Categories.DEV,
                "06/02/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "drupal",
                "Drupal CMS",
                "https://new.drupal.org/home",
                Categories.WEB,
                "06/07/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "git-metrics",
                "A git extension to be able to track metrics about your project, within the git repository",
                "https://github.com/jdrouet/git-metrics",
                Categories.GIT,
                "06/07/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "pi-hole",
                "A black hole for Internet advertisements",
                "https://github.com/pi-hole/pi-hole",
                Categories.NETWORK,
                "06/07/2025",
                None,
                Waiting_Status.WAITING,
                Types.MODULE,
            ],
            [
                "cpc",
                "Text calculator with support for units and conversion",
                "https://github.com/probablykasper/cpc",
                Categories.DEV,
                "06/07/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "broadcast-box",
                "A broadcast, in a box. ",
                "https://github.com/Glimesh/broadcast-box",
                Categories.VIDEO,
                "06/07/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "nix-check-deps",
                "scan nix packages for unused buildInputs",
                "https://github.com/LordGrimmauld/nix-check-deps",
                Categories.DEV,
                "06/07/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "rumdl",
                "A Markdown Linter and Formatter written in Rust",
                "https://github.com/rvben/rumdl",
                Categories.DEV,
                "10/17/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
            [
                "durdraw",
                "Versatile ASCII and ANSI Art text editor for drawing in the Linux/Unix/macOS terminal, with animation, 256 and 16 colors, Unicode and CP437, and customizable themes",
                Categories.FUN,
                "11/19/2025",
                None,
                Waiting_Status.WAITING,
                Types.PACKAGE,
            ],
        ],
        columns=[
            "name",
            "description",
            "url",
            "categories",
            "added_date",
            "finished_date",
            "waiting_status",
            "type",
        ],
    )

    df["categories"] = df["categories"].apply(lambda x: x.value)
    df["waiting_status"] = df["waiting_status"].apply(lambda x: x.value)
    df["type"] = df["type"].apply(lambda x: x.value)

    df.to_sql("packages", conn, if_exists="append", index=False)
