pragma foreign_keys
= on
;

CREATE TABLE waiting_status (
    id integer PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE categories (
    id integer PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE types (
    id integer PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE packages (
    id integer PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text NOT NULL,
    url text NOT NULL,
    categories integer NOT NULL,
    waiting_status integer NOT NULL,
    added_date text NOT NULL,
    finished_date text,
    type integer NOT NULL DEFAULT 1,
    FOREIGN KEY (waiting_status)
    REFERENCES waiting_status (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    FOREIGN KEY (categories)
    REFERENCES categories (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    FOREIGN KEY (type)
    REFERENCES types (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);

INSERT INTO waiting_status  VALUES (1,'waiting'), (2,'done');

INSERT INTO types VALUES (1,'package'), (2,'module');

INSERT INTO categories  VALUES
(1,'music'),
(2,'nix'),
(3,'shell'),
(4,'dev'),
(5,'system'),
(6,'git'),
(7,'web'),
(8,'network'),
(9,'docker'),
(10,'audio'),
(11,'share'),
(12,'doc'),
(13,'image'),
(14,'encrypt'),
(15,'font'),
(16,'game'),
(17,'video'),
(18,'download'),
(19,'proxy');

INSERT INTO
packages (name,description,url,categories,added_date,finished_date,waiting_status,type)
VALUES
('id3',
'ID3 mass tagger',
'https://github.com/squell/id3',1,'05/17/2025',null,1,1),
('nix-editor',
'A simple rust program to edit NixOS configuration files with just a command',
'https://github.com/snowfallorg/nix-editor',2,'05/17/2025',null,1,1),
('jumper',
'Accurate and fast files/directories jumper',
'https://github.com/homerours/jumper',3,'05/17/2025',null,1,1),
('schemat',
'Code formatter for Scheme, Lisp, and any S-expressions',
'https://github.com/raviqqe/schemat',4,'05/17/2025',null,1,1),
('keyviz',
'Keyviz is a free and open-source tool to visualize your keystrokes ⌨️ and 🖱️ mouse actions in real-time.',
'https://github.com/mulaRahul/keyviz',5,'05/17/2025',null,1,1),
('git-pr',
'the easiest git collaboration tool',
'https://github.com/picosh/git-pr',6,'05/17/2025',null,1,1),
('cvtek',
'📄 Craft your Resume/CV using TOML',
'https://github.com/varbhat/cvtek',7,'05/17/2025',null,1,1),
('aicommit2',
'A Reactive CLI that generates git commit messages with Ollama, ChatGPT, Gemini, Claude, Mistral and other AI',
'https://github.com/tak-bro/aicommit2',6,'05/17/2025',null,1,1),
('AngryOxide',
'802.11 Attack Tool',
'https://github.com/Ragnt/AngryOxide',8,'05/17/2025',null,1,1),
('ducker',
'A slightly quackers Docker TUI based on k9s 🦆',
'https://github.com/robertpsoane/ducker',9,'05/17/2025',null,1,1),
('simplemoji',
'Fast Application for look your amazing emojis write in Rust',
'https://github.com/SergioRibera/simplemoji',3,'05/17/2025',null,1,1),
('voicevox',
'無料で使える中品質なテキスト読み上げ・歌声合成ソフトウェア',
'https://voicevox.hiroshiba.jp/',10,'05/17/2025',null,1,1),
('otree',
'A command line tool to view objects (JSON/YAML/TOML) in TUI tree widget.',
'https://github.com/fioncat/otree',4,'05/17/2025',null,1,1),
('azote',
'Wallpaper manager for wlroots-based compositors and some other WMs',
'https://github.com/nwg-piotr/azote',5,'05/17/2025',null,1,1),
('cloudpan189-go',
'天翼云盘命令行客户端(CLI)，基于 GO 语言实现',
'https://github.com/tickstep/cloudpan189-go',11,'05/17/2025',null,1,1),
('cppman',
'C++ 98/11/14 manual pages for Linux/MacOS',
'https://github.com/aitjcize/cppman',12,'05/17/2025',null,1,1),
('split-monitor-workspaces',
'A small Hyprland plugin to provide awesome-like workspace behavior',
'https://github.com/Duckonaut/split-monitor-workspaces',5,'05/17/2025',null,1,1),
('sss',
'SSS (Super ScreenShot) is a WIP: CLI/Lib to take amazing screenshot of code or screen',
'https://github.com/SergioRibera/sss',13,'05/17/2025',null,1,1),
('Diagon',
'Interactive ASCII art diagram generators. 🌟',
'https://github.com/ArthurSonzogni/Diagon',3,'05/17/2025',null,1,1),
('Kryptor',
'A simple, modern, and secure encryption and signing tool that aims to be a better version of age and Minisign.',
'https://github.com/samuel-lucas6/Kryptor',14,'05/17/2025',null,1,1),
('gfie',
'Greenfish Icon Editor Pro (GFIE Pro) is a powerful freeware image editor, especially suitable for creating icons, cursors, animations and icon libraries.',
'http://greenfishsoftware.org/gfie.php',13,'05/17/2025',null,1,1),
('scooter',
'Interactive find and replace in the terminal',
'https://github.com/thomasschafer/scooter',5,'05/17/2025',null,1,1),
('deskflow',
'Deskflow lets you share one mouse and keyboard between multiple computers on Windows, macOS and Linux. Its like a software KVM (but without video).',
'https://github.com/deskflow/deskflow',5,'05/17/2025',null,1,1),
('lla',
'blazing fast `ls` replacement with superpowers',
'https://github.com/triyanox/lla',3,'05/17/2025',null,1,1),
('ahoy',
'Create self-documenting cli programs from YAML files. Easily wrap bash, grunt, npm, docker, (anything) to standardize your processes and make the lives of the people working on your project better.',
'https://github.com/ahoy-cli/ahoy',3,'05/17/2025',null,1,1),
('opener',
'Open URL in your local web browser from the SSH-connected remote environment.',
'https://github.com/superbrothers/opener',5,'05/17/2025',null,1,1),
('InputPlumber',
'Open source input router and remapper daemon for Linux',
'https://github.com/ShadowBlip/InputPlumber',5,'05/17/2025',null,1,1),
('mago',
'Mago is a toolchain for PHP that aims to provide a set of tools to help developers write better code.',
'https://github.com/carthage-software/mago',4,'05/17/2025',null,1,1),
('ffpb',
'A progress bar for ffmpeg. Yay !',
'https://github.com/althonos/ffpb',3,'05/17/2025',null,1,1),
('awk-language-server',
'Language Server for AWK and associated VSCode client extension',
'https://github.com/Beaglefoot/awk-language-server',4,'05/17/2025',null,1,1),
('Lilex',
'🤘Open source programming font',
'https://github.com/mishamyrt/Lilex',15,'05/17/2025',null,1,1),
('copywrite',
'Automate copyright headers and license files at scale',
'https://github.com/hashicorp/copywrite',4,'05/17/2025',null,1,1),
('primitive',
'Reproducing images with geometric primitives.',
'https://github.com/fogleman/primitive',13,'05/17/2025',null,1,1),
('textidote',
'Spelling, grammar and style checking on LaTeX documents',
'https://github.com/sylvainhalle/textidote',12,'05/17/2025',null,1,1),
('urlfinder',
'A high-speed tool for passively gathering URLs, optimized for efficient and comprehensive web asset discovery without active scanning.',
'https://github.com/projectdiscovery/urlfinder',8,'05/17/2025',null,1,1),
('moxide',
'A tmux session manager with a modular config',
'https://github.com/dlurak/moxide',3,'05/17/2025',null,1,1),
('suyu',
'Experimental Nintendo Switch emulator written in C++',
'https://suyu.dev',16,'05/17/2025',null,1,1),
('astroterm',
'A planetarium for your terminal! Explore stars, planets, constellations, and more, all rendered right in the command line—no telescope required. ✨🪐',
'https://github.com/da-luce/astroterm/',3,'05/17/2025',null,1,1),
('isd',
'isd (interactive systemd) – a better way to work with systemd units',
'https://github.com/isd-project/isd',5,'05/17/2025',null,1,1),
('flow',
'Flow Control: a programmer''s text editor',
'https://github.com/neurocyte/flow',4,'05/17/2025',null,1,1),
('watcher',
'Filesystem watcher. Works anywhere. Simple, efficient and friendly.',
'https://github.com/e-dant/watcher',5,'05/17/2025',null,1,1),
('rustic',
'rustic - fast, encrypted, and deduplicated backups powered by Rust',
'https://github.com/rustic-rs/rustic',14,'05/17/2025',null,1,2),
('inori',
'mpd client',
'https://github.com/eshrh/inori',1,'05/17/2025',null,1,1),
('itgmania',
'A fork of StepMania 5.1, improved for the post-ITG community!',
'https://www.itgmania.com/',16,'05/17/2025',null,1,1),
('patchy',
'A tool which makes it easy to declaratively manage personal forks by automatically merging pull requests',
'https://github.com/nik-rev/patchy',6,'05/17/2025',null,1,1),
('migrate-to-uv',
'migrate-to-uv migrates a project to uv from another package manager.',
'https://mkniewallner.github.io/migrate-to-uv/',4,'05/17/2025',null,1,1),
('SeaGOAT',
'A code search engine for the AI age.',
'https://kantord.github.io/SeaGOAT/latest/',4,'05/17/2025',null,1,1),
('zipline',
'A ShareX/file upload server that is easy to use, packed with features, and with an easy setup!',
'https://github.com/diced/zipline',11,'05/17/2025',null,1,2),
('ffizer',
'ffizer is a files and folders initializer / generator. Create any kind (or part) of project from template.',
'https://github.com/ffizer/ffizer',5,'05/17/2025',null,1,1),
('gssg',
'A gemini static site generator',
'https://git.sr.ht/~gsthnz/gssg',7,'05/17/2025',null,1,1),
('PowerShellEditorServices',
'Common platform for PowerShell development support in any editor or application',
'https://github.com/PowerShell/PowerShellEditorServices',4,'05/17/2025',null,1,1),
('tmux-which-key',
'Tmux plugin that allows users to select actions from a customizable popup menu',
'https://github.com/alexwforsythe/tmux-which-key',3,'05/17/2025',null,1,1),
('readeck',
'Readeck is a simple web application that lets you save the precious readable content of web pages you like and want to keep forever.',
'https://codeberg.org/readeck/readeck',7,'05/17/2025',null,1,2),
('PowerStation',
'Open source TDP control and performance daemon with DBus interface',
'https://github.com/ShadowBlip/PowerStation',5,'05/17/2025',null,1,2),
('jellyfin-tui',
'🪼 Music streaming client for the terminal',
'https://github.com/dhonus/jellyfin-tui',17,'05/17/2025',null,1,1),
('fum',
'A fully customizable tui-based mpris music client.',
'https://github.com/qxb3/fum',1,'05/17/2025',null,1,1),
('sourcegit',
'Windows/macOS/Linux GUI client for GIT users',
'https://github.com/sourcegit-scm/sourcegit',6,'05/17/2025',null,1,1),
('clock-rs',
'clock-rs - A clock for your terminal!',
'https://github.com/Oughie/clock-rs',5,'05/17/2025',null,1,1),
('nix-search-tv',
'Fuzzy search for Nix packages.',
'https://github.com/3timeslazy/nix-search-tv',3,'05/17/2025',null,1,1),
('xan',
'The CSV magician',
'https://github.com/medialab/xan',4,'05/17/2025',null,1,1),
('tooling-language-server',
'A language server for tools & package managers',
'https://github.com/filiptibell/tooling-language-server',4,'05/17/2025',null,1,1),
('telegram-integration',
'Memogram is an easy to use integration service for syncing messages and images from a Telegram bot into your Memos.',
'https://github.com/usememos/telegram-integration',7,'05/17/2025',null,1,1),
('exercism-cli-fish-wrapper',
'A fish wrapper for the Exercism CLI',
'https://github.com/glennj/exercism-cli-fish-wrapper',3,'05/17/2025',null,1,1),
('posting',
'The API client that lives in your terminal.',
'https://posting.sh/',4,'05/17/2025',null,1,1),
('clashtui',
'Mihomo (Clash.Meta) TUI Client',
'https://github.com/JohanChane/clashtui',3,'05/17/2025',null,1,1),
('mpls',
'Markdown Preview Language Server',
'https://github.com/mhersson/mpls',4,'05/17/2025',null,1,1),
('flamelens',
'Flamegraph viewer in the terminal',
'https://github.com/YS-L/flamelens',4,'05/17/2025',null,1,1),
('t3',
'Next generation tee with colorized output streams and precise time stamping',
'https://github.com/flox/t3',3,'05/17/2025',null,1,1),
('umu-launcher',
'',
'https://github.com/Open-Wine-Components/umu-launcher',16,'05/17/2025',null,1,1),
('xdg-desktop-portal-termfilechooser',
'xdg-desktop-portal backend for choosing files with your favorite file chooser',
'https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser',5,'05/17/2025',null,1,1),
('ni',
'💡 Use the right package manager',
'https://github.com/antfu-collective/ni',5,'05/17/2025',null,1,1),
('jinja-lsp',
'Language Server for jinja',
'https://github.com/uros-5/jinja-lsp',4,'05/17/2025',null,1,1),
('biliup-rs',
'命令行投稿(B站)和视频下载工具，提供多种登录方式，支持多p。',
'https://github.com/biliup/biliup-rs',18,'05/17/2025',null,1,1),
('world-wall-clock',
'world-wall-clock is a TUI application that provides a multi-timezone graphical clock in a terminal environment.',
'https://github.com/ddelabru/world-wall-clock',3,'05/17/2025',null,1,1),
('aonsoku',
'A modern desktop client for Navidrome/Subsonic servers built with React and Rust.',
'https://github.com/victoralvesf/aonsoku',1,'05/17/2025',null,1,1),
('simple-completion-language-server',
'Language server to enable word completion and snippets for Helix editor',
'https://github.com/estin/simple-completion-language-server',4,'05/17/2025',null,1,1),
('taze',
'🥦 A modern cli tool that keeps your deps fresh',
'https://github.com/antfu-collective/taze',4,'05/17/2025',null,1,1),
('tray-tui',
'System tray in your terminal',
'https://github.com/Levizor/tray-tui',5,'05/17/2025',null,1,1),
('hot-resize',
'A tool for hot resizing (without reboot) disk partitions and filesystems.',
'https://github.com/liberodark/hot-resize',5,'05/17/2025',null,1,1),
('N_m3u8DL-RE',
'Cross-Platform, modern and powerful stream downloader for MPD/M3U8/ISM. English/简体中文/繁體中文.',
'https://github.com/nilaoda/N_m3u8DL-RE',18,'05/17/2025',null,1,1),
('kubexporter',
'📥 easily export your k8s resources',
'https://github.com/bakito/kubexporter',4,'05/17/2025',null,1,1),
('pandoc-mustache',
'Pandoc filter for variable substitution using Mustache syntax',
'https://github.com/michaelstepner/pandoc-mustache',4,'05/17/2025',null,1,1),
('rofi-network-manager',
'🛠 Manage wifi and ethernet with rofi.',
'https://github.com/meowrch/rofi-network-manager',5,'05/17/2025',null,1,1),
('nix-heuristic-gc',
'A more discerning cousin of nix-collect-garbage',
'https://github.com/risicle/nix-heuristic-gc',5,'05/18/2025',null,1,1),
('UDPspeeder',
'A Tunnel which Improves your Network Quality on a High-latency Lossy Link by using Forward Error Correction, possible for All Traffics(TCP/UDP/ICMP)',
'https://github.com/wangyu-/UDPspeeder',5,'05/18/2025',null,1,1),
('tmux-sessionx',
'A Tmux session manager, with preview, fuzzy finding, and MORE',
'https://github.com/omerxx/tmux-sessionx',3,'05/18/2025',null,1,1),
('bunster',
'Compile shell scripts to static binaries.',
'https://github.com/yassinebenaid/bunster',3,'05/18/2025',null,1,1),
('guesswidth',
'Guess the width (fwf)  output without delimiters in commands that output to the terminal.',
'https://github.com/noborus/guesswidth',3,'05/18/2025',null,1,1),
('bed',
'Binary editor written in Go',
'https://github.com/itchyny/bed',4,'05/18/2025',null,1,1),
('osc',
'Access the system clipboard from anywhere using the ANSI OSC52 sequence',
'https://github.com/theimpostor/osc',3,'05/18/2025',null,1,1),
('hydra',
'Hydra Launcher is an open-source gaming platform created to be the single tool that you need',
'https://github.com/hydralauncher/hydra',16,'05/18/2025',null,1,1),
('textLSP',
'Language server for text spell and grammar check with various tools.',
'https://github.com/hangyav/textLSP',4,'05/18/2025',null,1,1),
('uv-sort',
'Sort uv''s dependencies alphabetically',
'https://github.com/ninoseki/uv-sort',4,'05/18/2025',null,1,1),
('vim-apathy',
'apathy.vim: Set the ''path'' option for miscellaneous file types',
'https://github.com/tpope/vim-apathy/',4,'05/18/2025',null,1,1),
('mdq',
'like jq but for Markdown: find specific elements in a md doc',
'https://github.com/yshavit/mdq',4,'05/18/2025',null,1,1),
('jellyflix',
'Jellyfix is an easy-to-use Jellyfin client for movies and shows. It''s cross-platform and supports Mobile (iOS, Android) and Desktop (Windows, Mac, Linux).',
'https://github.com/jellyflix-app/jellyflix',17,'05/18/2025',null,1,1),
('tparted',
'Text-based user interface (TUI) frontend for parted: A simple, user-friendly utility for creating, reorganizing, and deleting disk partitions, based on Turbo/Free Vision application framework.',
'https://github.com/Kagamma/tparted',5,'05/18/2025',null,1,1),
('proftpd',
'Highly configurable GPL-licensed FTP server software',
'http://www.proftpd.org/',5,'05/18/2025',null,1,1),
('clive',
'⚡ Automates terminal operations.',
'https://github.com/koki-develop/clive',3,'05/18/2025',null,1,1),
('docker-color-output',
'🎨 Docker color output which improves readability.',
'https://github.com/devemio/docker-color-output',4,'05/18/2025',null,1,1),
('bpfilter',
'An eBPF-based packet filtering framework.',
'https://bpfilter.io/',8,'05/18/2025',null,1,1),
('go-mod-upgrade',
'Update outdated Go dependencies interactively',
'https://github.com/oligot/go-mod-upgrade/',4,'05/18/2025',null,1,1),
('awesome-wm-widgets',
'Widgets for Awesome Window Manager',
'https://github.com/streetturtle/awesome-wm-widgets',5,'05/18/2025',null,1,1),
('systemd-language-server',
'Language Server for Systemd unit files',
'https://github.com/psacawa/systemd-language-server',4,'05/18/2025',null,1,1),
('docfx',
'Static site generator for .NET API documentation.',
'https://github.com/dotnet/docfx',4,'05/18/2025',null,1,1),
('docker-vackup',
'Script to easily backup and restore docker volumes',
'https://github.com/BretFisher/docker-vackup',4,'05/18/2025',null,1,1),
('soundalike',
'soundalike is a command-line program that tries to find similar audio files by comparing acoustic fingerprints. Its main focus is identifying duplicate songs in music collections.',
'https://codeberg.org/derat/soundalike',10,'05/18/2025',null,1,1),
('bsky',
'A cli application for bluesky social',
'https://github.com/mattn/bsky',7,'05/18/2025',null,1,1),
('pavolctld',
'pavolctld is a minimal volume control daemon for PulseAudio written in C.',
'https://tjkeller.xyz/projects/pavolctld/',5,'05/18/2025',null,1,1),
('Gokapi',
'Lightweight selfhosted Firefox Send alternative without public upload. AWS S3 supported.',
'https://github.com/Forceu/Gokapi',7,'05/18/2025',null,1,1),
('etterna',
'Advanced cross-platform rhythm game focused on keyboard play',
'https://etternaonline.com/',16,'05/18/2025',null,1,1),
('lon',
'Lock & update Nix dependencies',
'https://github.com/nikstur/lon',4,'05/18/2025',null,1,1),
('git-who',
'Git blame for file trees',
'https://github.com/sinclairtarget/git-who',6,'05/18/2025',null,1,1),
('git-dumper',
'A tool to dump a git repository from a website',
'https://github.com/arthaud/git-dumper',6,'05/18/2025',null,1,1),
('dioxionary',
'StarDict in Rust! 使用 离线 / 在线 词典在终端中查单词、背单词！',
'https://github.com/vaaandark/dioxionary',7,'05/18/2025',null,1,1),
('nixpkgs-track',
'📦 Track where Nixpkgs pull requests have reached.',
'https://github.com/uncenter/nixpkgs-track',4,'05/18/2025',null,1,1),
('roomarranger',
'Room Arranger is a 3D room / apartment / floor planner with a simple user interface.',
'https://www.roomarranger.com/',4,'05/18/2025',null,1,1),
('nyaa',
'A tui tool for browsing and downloading torrents',
'https://github.com/Beastwick18/nyaa',7,'05/18/2025',null,1,1),
('mouseless',
'A replacement for the mouse in Linux',
'https://github.com/jbensmann/mouseless',5,'05/18/2025',null,1,1),
('cliflux',
'A terminal client for Miniflux RSS reader',
'https://github.com/spencerwi/cliflux',7,'05/18/2025',null,1,1),
('go-grip',
'Preview Markdown files locally before committing them.',
'https://github.com/chrishrb/go-grip',4,'05/18/2025',null,1,1),
('omnix',
'Nix companion to improve developer experience',
'https://omnix.page',4,'05/18/2025',null,1,1),
('bashunit',
'A simple testing library for bash scripts. Test your bash scripts in the fastest and simplest way.',
'https://github.com/TypedDevs/bashunit',4,'05/18/2025',null,1,1),
('better-commits',
'A CLI for creating better commits following the conventional commits specification',
'https://github.com/Everduin94/better-commits',4,'05/18/2025',null,1,1),
('runmd',
'Executable markdown files',
'https://github.com/broofa/runmd',4,'05/18/2025',null,1,1),
('godns',
'A dynamic DNS client tool that supports AliDNS, Cloudflare, Google Domains, DNSPod, HE.net & DuckDNS & DreamHost, etc, written in Go.',
'https://github.com/TimothyYe/godns',5,'05/18/2025',null,1,2),
('KrillinAI',
' A video translation and dubbing tool powered by LLMs, offering professional-grade translations and one-click full-process deployment. It can generate content optimized for platforms like YouTube，TikTok, and Shorts.  基于AI大模型的视频翻译和配音工具，专业级翻译，一键部署全流程，可以生成适配抖音，小红书，哔哩哔哩，视频号，TikTok，Youtube Shorts等形态的内容',
'https://github.com/krillinai/KrillinAI',17,'05/18/2025',null,1,1),
('ferrishot',
'A powerful screenshot app written in Rust 📸🦀',
'https://github.com/nik-rev/ferrishot',5,'05/18/2025',null,1,1),
('markdown-code-runner',
'Execute and optionally rewrite code blocks in Markdown files based on external commands',
'https://github.com/drupol/markdown-code-runner',4,'05/18/2025',null,1,1),
('codex',
'Lightweight coding agent that runs in your terminal',
'https://github.com/openai/codex',4,'05/18/2025',null,1,1),
('g-ls',
'powerful and cross-platform ls 🌈',
'https://github.com/Equationzhao/g',5,'05/18/2025',null,1,1),
('zashboard',
'A Dashboard Using Clash API',
'https://github.com/Zephyruso/zashboard',19,'05/18/2025',null,1,1),
('ggh',
'Recall your SSH sessions (also search your SSH config file)',
'https://github.com/byawitz/ggh',5,'05/18/2025',null,1,1),
('hevi',
'Hex viewer',
'https://github.com/Arnau478/hevi',4,'05/18/2025',null,1,1),
('speed-cloudflare-cli',
'📈 Measure the speed and consistency of your internet connection using speed.cloudflare.com',
'https://github.com/KNawm/speed-cloudflare-cli',8,'05/18/2025',null,1,1),
('goshs',
'A SimpleHTTPServer written in Go, enhanced with features and with a nice design - https://goshs.de',
'https://github.com/patrickhener/goshs',11,'05/18/2025',null,1,1),
('codebook',
'Spell Checker for Code',
'https://github.com/blopker/codebook',4,'05/18/2025',null,1,1),
('just-lsp',
'A language server for just',
'https://github.com/terror/just-lsp',4,'05/18/2025',null,1,1),
('animeko',
'集找番、追番、看番的一站式弹幕追番平台，云收藏同步 (Bangumi)，离线缓存，BitTorrent，弹幕云过滤。100% Kotlin/Compose Multiplatform',
'https://github.com/open-ani/animeko',17,'05/18/2025',null,1,1),
('redu',
'ncdu for your restic repository',
'https://github.com/drdo/redu',5,'05/18/2025',null,1,1),
('cookcli',
'Command line program which provides a suite of tools to create shopping lists and maintain recipes. ',
'https://github.com/cooklang/cookcli',4,'05/18/2025',null,1,2);


CREATE VIEW v_packages
AS
SELECT '[[' || url || '][' || name || ']]' AS package, description FROM packages WHERE waiting_status = 1 ORDER BY added_date
