# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  adl = {
    pname = "adl";
    version = "3cbacf34728ca2bb8056865cff78d6f3b54688c8";
    src = fetchFromGitHub {
      owner = "RaitaroH";
      repo = "adl";
      rev = "3cbacf34728ca2bb8056865cff78d6f3b54688c8";
      fetchSubmodules = false;
      sha256 = "sha256-LJ+awJHXOYSGuuvD/jq1zO26aKYAsK6hoVkcsmfArZI=";
    };
    date = "2024-09-02";
  };
  advance-touch = {
    pname = "advance-touch";
    version = "1.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/advance-touch/advance-touch-1.0.2.tar.gz";
      sha256 = "sha256-I4wF4PuhDUnM7YluERJzMWysUODtfUTPOo4nvNSGZ8U=";
    };
  };
  animdl = {
    pname = "animdl";
    version = "c7c3b79198e66695e0bbbc576f9d9b788616957f";
    src = fetchFromGitHub {
      owner = "justfoolingaround";
      repo = "animdl";
      rev = "c7c3b79198e66695e0bbbc576f9d9b788616957f";
      fetchSubmodules = false;
      sha256 = "sha256-kn6vCCFhJNlruxoO+PTHVIwTf1E5j1aSdBhrFuGzUq4=";
    };
    date = "2023-10-17";
  };
  antifennel = {
    pname = "antifennel";
    version = "a135f016414517ecb624bad26b39ed56d256beaa";
    src = fetchgit {
      url = "https://git.sr.ht/~technomancy/antifennel";
      rev = "a135f016414517ecb624bad26b39ed56d256beaa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XynKKDyykyPM4z2ZLp9Oy8KFlEZG2iHXKMkajaS/DaE=";
    };
    date = "2024-09-25";
  };
  argparse = {
    pname = "argparse";
    version = "1.4.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/argparse/argparse-1.4.0.tar.gz";
      sha256 = "sha256-YrCJpVvh2JSc0rx+DfC9254Cj678jDIDjMhIYq791uQ=";
    };
  };
  autocrop = {
    pname = "autocrop";
    version = "2afe00ed87fb10a6d368d0d4140307dc99b1a545";
    src = fetchFromGitHub {
      owner = "mandykoh";
      repo = "autocrop";
      rev = "2afe00ed87fb10a6d368d0d4140307dc99b1a545";
      fetchSubmodules = false;
      sha256 = "sha256-oxvu0P0LmusFQ5qX557pgyiq+eslWwfCaoEAkxJnqOA=";
    };
    date = "2021-06-03";
  };
  "autopair.fish" = {
    pname = "autopair.fish";
    version = "ec7ccf41eb945657a829338e85c88ad3353f961a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "autopair.fish";
      rev = "ec7ccf41eb945657a829338e85c88ad3353f961a";
      fetchSubmodules = false;
      sha256 = "sha256-hM2J82NHe5LPSHZ+yYHZNWAjif0vbwerloHIvTUT+tQ=";
    };
    date = "2024-07-08";
  };
  av = {
    pname = "av";
    version = "v0.0.43";
    src = fetchFromGitHub {
      owner = "aviator-co";
      repo = "av";
      rev = "v0.0.43";
      fetchSubmodules = false;
      sha256 = "sha256-zfS7yfsKvfWQXRx4yYrWIbB9ak/hTs+Gq3UH6o7PkKE=";
    };
  };
  awesome-freedesktop = {
    pname = "awesome-freedesktop";
    version = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
    src = fetchFromGitHub {
      owner = "lcpz";
      repo = "awesome-freedesktop";
      rev = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
      fetchSubmodules = false;
      sha256 = "sha256-lQstCcTPUYUt5hzAJIyQ16crPngeOnUla7I4QiG6gEs=";
    };
    date = "2022-06-23";
  };
  baidupcs-go = {
    pname = "baidupcs-go";
    version = "v3.9.5";
    src = fetchFromGitHub {
      owner = "qjfoidnh";
      repo = "BaiduPCS-Go";
      rev = "v3.9.5";
      fetchSubmodules = false;
      sha256 = "sha256-zNodRQzflOOB3hAeq4KbjRFlHQwknVy+4ucipUcoufY=";
    };
  };
  blendr = {
    pname = "blendr";
    version = "v1.3.3";
    src = fetchFromGitHub {
      owner = "dmtrKovalenko";
      repo = "blendr";
      rev = "v1.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-6QRI1MQnoppzlVfRV/bfqfTnBjC0/haFm52Ez9nltzw=";
    };
  };
  bling = {
    pname = "bling";
    version = "19ccfc0daf5edda8bbc508487616d00277a9d954";
    src = fetchFromGitHub {
      owner = "BlingCorp";
      repo = "bling";
      rev = "19ccfc0daf5edda8bbc508487616d00277a9d954";
      fetchSubmodules = false;
      sha256 = "sha256-6NZSUb7sSBUegSIPIubQUOZG3knzXfnyfEbCoEyggtc=";
    };
    date = "2024-06-02";
  };
  blobdrop = {
    pname = "blobdrop";
    version = "v2.1";
    src = fetchFromGitHub {
      owner = "vimpostor";
      repo = "blobdrop";
      rev = "v2.1";
      fetchSubmodules = false;
      sha256 = "sha256-o2+qtkyu2qcwXpum3KiogyO8D6aY7bRJ6y4FWQKQY/o=";
    };
  };
  bluetui = {
    pname = "bluetui";
    version = "v0.5.1";
    src = fetchFromGitHub {
      owner = "pythops";
      repo = "bluetui";
      rev = "v0.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-9svPIZzKuI4XBlxBsKucGLdX2dkfAy9ERT5oj8Su9TM=";
    };
  };
  boilr = {
    pname = "boilr";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "tmrts";
      repo = "boilr";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-ITUr1YUgqfrKAY6QEqxzdl3U7IjxYidbKT2eR1qEsPU=";
    };
  };
  bt = {
    pname = "bt";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "LeperGnome";
      repo = "bt";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-6hNdAmAflPcky1QxQvZCo+ffprRuIn2NPZYlS4wurww=";
    };
  };
  c = {
    pname = "c";
    version = "7cdc09e69d2f7fc49f70c80c565aa09b19e666db";
    src = fetchFromGitHub {
      owner = "ryanmjacobs";
      repo = "c";
      rev = "7cdc09e69d2f7fc49f70c80c565aa09b19e666db";
      fetchSubmodules = false;
      sha256 = "sha256-dOFM9wQzoEsuBwWb/FfxGDW07oyRXyGRH7lpscoSgUY=";
    };
    date = "2023-11-24";
  };
  chezmoi-vim = {
    pname = "chezmoi-vim";
    version = "abf37336437867cbd99ce2f8849b717415391cc3";
    src = fetchFromGitHub {
      owner = "alker0";
      repo = "chezmoi.vim";
      rev = "abf37336437867cbd99ce2f8849b717415391cc3";
      fetchSubmodules = false;
      sha256 = "sha256-S1/myC1dEydi1F9a6XV0lJW3S/wWQe+A2ZXPo8GbtQo=";
    };
    date = "2024-07-26";
  };
  clashctl = {
    pname = "clashctl";
    version = "0.3.3";
    src = fetchFromGitHub {
      owner = "George-Miao";
      repo = "clashctl";
      rev = "0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-7XVMtl6yFxT9fy205sZL8eJ711NXdmYIMFVBbF0RoPc=";
    };
  };
  cloneit = {
    pname = "cloneit";
    version = "6198556e810d964cc5938c446ef42fc21b55fe0b";
    src = fetchFromGitHub {
      owner = "alok8bb";
      repo = "cloneit";
      rev = "6198556e810d964cc5938c446ef42fc21b55fe0b";
      fetchSubmodules = false;
      sha256 = "sha256-RP0/kquAlSwRMeB6cjvS5JB9qfdkT8IKLVxaxrmzJ+0=";
    };
    date = "2024-07-28";
  };
  cmdx = {
    pname = "cmdx";
    version = "v1.7.4";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "cmdx";
      rev = "v1.7.4";
      fetchSubmodules = false;
      sha256 = "sha256-UzAtDTs9KGcImQVU6ve80j68you900ag+aJaVZXF3Dw=";
    };
  };
  code-radio-cli = {
    pname = "code-radio-cli";
    version = "v1.0.5";
    src = fetchFromGitHub {
      owner = "JasonWei512";
      repo = "code-radio-cli";
      rev = "v1.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-H2mnMWMJcFZIWHRz4QzM7ZwfbJ0N/ycu4g2W7187E3A=";
    };
  };
  comigo = {
    pname = "comigo";
    version = "v0.9.11.1";
    src = fetchFromGitHub {
      owner = "yumenaka";
      repo = "comigo";
      rev = "v0.9.11.1";
      fetchSubmodules = false;
      sha256 = "sha256-+SyHeJkGh9G3tklqLCF5oBL8H6XAGSEo+hVDa5Zpdhw=";
    };
  };
  compose2nix = {
    pname = "compose2nix";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "aksiksi";
      repo = "compose2nix";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-rFnnbRVVv/N5021Al3vmjFAui1cTp8NBZDBNQo8CsXM=";
    };
  };
  convfmt = {
    pname = "convfmt";
    version = "0.1.6";
    src = fetchFromGitHub {
      owner = "oriontvv";
      repo = "convfmt";
      rev = "0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-k2Qj6/dllArP6jIDyiHA7luudsdQgipZMYY6Hm5hqEs=";
    };
  };
  corgi = {
    pname = "corgi";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "junyu-w";
      repo = "corgi";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-1qG11iuHrf3jg0aPqNU4ItT4rvYxXg5ZDDaJIMOWOUE=";
    };
  };
  "ctrl-z.fish" = {
    pname = "ctrl-z.fish";
    version = "82448a44c9ba8e2d8a5c7394184e977f5f76e0b8";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "ctrl-z.fish";
      rev = "82448a44c9ba8e2d8a5c7394184e977f5f76e0b8";
      fetchSubmodules = false;
      sha256 = "sha256-JXy5y0FXLvgdqgkwqGFkv2aqV40AHWRq9mq/EhsTEyo=";
    };
    date = "2024-10-20";
  };
  curd = {
    pname = "curd";
    version = "bb64b3bb3407d965e0ec17c232871dec6fcc8457";
    src = fetchFromGitHub {
      owner = "Wraient";
      repo = "curd";
      rev = "bb64b3bb3407d965e0ec17c232871dec6fcc8457";
      fetchSubmodules = false;
      sha256 = "sha256-AzoEAd6WMV1ROoiKVghQReSg4dL9Z75xacmwgOGG/To=";
    };
    date = "2024-10-16";
  };
  dblab = {
    pname = "dblab";
    version = "v0.26.0";
    src = fetchFromGitHub {
      owner = "danvergara";
      repo = "dblab";
      rev = "v0.26.0";
      fetchSubmodules = false;
      sha256 = "sha256-3v9L1mV+DZ6FlrBoGSg8tewKJVyeqqacVj3yGVtYVHc=";
    };
  };
  devdocs-vim = {
    pname = "devdocs-vim";
    version = "ae7e029c1fc1d89c3a18f1244a6747ad3ddfc271";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "devdocs.vim";
      rev = "ae7e029c1fc1d89c3a18f1244a6747ad3ddfc271";
      fetchSubmodules = false;
      sha256 = "sha256-Q+e9pwvmNfBPewT3mfAHH5fZh+VVY7mXELbMI41WkqY=";
    };
    date = "2024-10-18";
  };
  diffnav = {
    pname = "diffnav";
    version = "v0.2.8";
    src = fetchFromGitHub {
      owner = "dlvhdr";
      repo = "diffnav";
      rev = "v0.2.8";
      fetchSubmodules = false;
      sha256 = "sha256-xZAi/Ky1RjOxjhQKHvozaPTqDPcrGfhMemGWzi7WyW4=";
    };
  };
  docker-alist = {
    pname = "docker-alist";
    version = "v3.38.0";
    src = dockerTools.pullImage {
      imageName = "xhofe/alist-aria2";
      imageDigest = "sha256:f5dba0ff984ef218284334f073b3d97a6c56919de2bd02b1d8127e5313282197";
      sha256 = "sha256-mXXtKqbz3hNxzLeJuf+A3+eX5RsC6d8sx7rDfoqoRnw=";
      finalImageTag = "v3.38.0";
    };
  };
  docker-flaresolverr = {
    pname = "docker-flaresolverr";
    version = "v3.3.21";
    src = dockerTools.pullImage {
      imageName = "flaresolverr/flaresolverr";
      imageDigest = "sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b";
      sha256 = "sha256-unGzkgDG5RvVPz+cHdNqizBjEf9FCHSMwi7PbRgjETI=";
      finalImageTag = "v3.3.21";
    };
  };
  docker-qd = {
    pname = "docker-qd";
    version = "20240210";
    src = dockerTools.pullImage {
      imageName = "qdtoday/qd";
      imageDigest = "sha256:7d9a54588876203720d7638cd0ca5e25897d3c8993fcfa9f9c0c59a91cf8ed9f";
      sha256 = "sha256-vxZHuExbVwA4HyXzrXgogomxRg3EaHaEwBG1BH/gvnI=";
      finalImageTag = "20240210";
    };
  };
  docker-subconverter = {
    pname = "docker-subconverter";
    version = "0.9.0";
    src = dockerTools.pullImage {
      imageName = "tindy2013/subconverter";
      imageDigest = "sha256:41899af10188ce83f6359eacc3d12f33c74b423c35b37bcd09b686575e9e10ad";
      sha256 = "sha256-PiCD+jyQRhzbHKQeJxJiyUd+TZRG3OZHRkV97ITlI9w=";
      finalImageTag = "0.9.0";
    };
  };
  dra = {
    pname = "dra";
    version = "0.6.2";
    src = fetchFromGitHub {
      owner = "devmatteini";
      repo = "dra";
      rev = "0.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-9Ts9xipEacb+704BDVoOPGKlYKbuSdso1WYsFspNJTY=";
    };
  };
  easyjump-vim = {
    pname = "easyjump-vim";
    version = "7be7e1b6e8000971d0f6ef9e8480f86094f56635";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "easyjump.vim";
      rev = "7be7e1b6e8000971d0f6ef9e8480f86094f56635";
      fetchSubmodules = false;
      sha256 = "sha256-SuvbOOp0G+V0X4G++HkiGO0SWaZvCMd7/Y8q9gWvUYE=";
    };
    date = "2024-06-06";
  };
  eg = {
    pname = "eg";
    version = "1.2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/eg/eg-1.2.2.tar.gz";
      sha256 = "sha256-jTdF7OsqTJFQexkjGTdHt66IiI5iV+uKrM996uKjAKc=";
    };
  };
  eleventy = {
    pname = "eleventy";
    version = "v3.0.0";
    src = fetchFromGitHub {
      owner = "11ty";
      repo = "eleventy";
      rev = "v3.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-0xyVski+WTfTdYfNUBMKX4fnorGSsbi95WMR8ocSU2Q=";
    };
  };
  envset = {
    pname = "envset";
    version = "v0.1.17";
    src = fetchFromGitHub {
      owner = "schpet";
      repo = "envset";
      rev = "v0.1.17";
      fetchSubmodules = false;
      sha256 = "sha256-d2cStBjI2heQyP0cODRYQPvZJ4frFw7w5lsSdyvi5y8=";
    };
  };
  facad = {
    pname = "facad";
    version = "v2.18.0";
    src = fetchFromGitHub {
      owner = "yellow-footed-honeyguide";
      repo = "facad";
      rev = "v2.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-0Z8CDHLWAighRhcVZIlSQAWb9CpeMpmw9ASy9ACep4Q=";
    };
  };
  fast-anime = {
    pname = "fast-anime";
    version = "v2.6.9";
    src = fetchFromGitHub {
      owner = "Benex254";
      repo = "FastAnime";
      rev = "v2.6.9";
      fetchSubmodules = false;
      sha256 = "sha256-gQrNedNJ+joGhWtVub6im/74xIW1wgiOFeMgB+pSbH4=";
    };
  };
  fc-fish = {
    pname = "fc-fish";
    version = "9457a9c47391ff712696bbef0e4a109de2a653d1";
    src = fetchFromGitHub {
      owner = "lengyijun";
      repo = "fc-fish";
      rev = "9457a9c47391ff712696bbef0e4a109de2a653d1";
      fetchSubmodules = false;
      sha256 = "sha256-DQQofY5FPdy5kWctlKmi2SRTH7zL9ZpBdrdMx+iX+dA=";
    };
    date = "2023-04-07";
  };
  fetch = {
    pname = "fetch";
    version = "v0.4.6";
    src = fetchFromGitHub {
      owner = "gruntwork-io";
      repo = "fetch";
      rev = "v0.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-otHsP3Y8FZqB9omNYuM7gZfolqFiDwlXLEXeJB3pefI=";
    };
  };
  fgit = {
    pname = "fgit";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "fastgh";
      repo = "fgit";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-27GZp1qd0pJg9usIxj8wl1Dz+4ZC0273bb1tJ4Hhc9s=";
    };
  };
  fifc = {
    pname = "fifc";
    version = "e953fcd521f34651d4eabedcc08cfdef7945b31d";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fifc";
      rev = "e953fcd521f34651d4eabedcc08cfdef7945b31d";
      fetchSubmodules = false;
      sha256 = "sha256-VmeVVwX5/rPZr98vaitvw6bqcZgaBNc+mEYkDRjFBXA=";
    };
    date = "2024-10-16";
  };
  fingerpaint = {
    pname = "fingerpaint";
    version = "v1.2.7";
    src = fetchFromGitHub {
      owner = "Wazzaps";
      repo = "fingerpaint";
      rev = "v1.2.7";
      fetchSubmodules = false;
      sha256 = "sha256-BPpSAaWLmF0JkMijx7pI87tzO/rcjTryxdI2ekTavRY=";
    };
  };
  fish-abbreviation-tips = {
    pname = "fish-abbreviation-tips";
    version = "8ed76a62bb044ba4ad8e3e6832640178880df485";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fish-abbreviation-tips";
      rev = "8ed76a62bb044ba4ad8e3e6832640178880df485";
      fetchSubmodules = false;
      sha256 = "sha256-F1t81VliD+v6WEWqj1c1ehFBXzqLyumx5vV46s/FZRU=";
    };
    date = "2023-01-23";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  fish-color-scheme-switcher = {
    pname = "fish-color-scheme-switcher";
    version = "9f9720dbf06cd4690e6b78c3daa897ae05f792bb";
    src = fetchFromGitHub {
      owner = "h-matsuo";
      repo = "fish-color-scheme-switcher";
      rev = "9f9720dbf06cd4690e6b78c3daa897ae05f792bb";
      fetchSubmodules = false;
      sha256 = "sha256-9VOgPxCNfuyy9DlicaN6W2EQ6OQFq/z8oSx1l9RitP4=";
    };
    date = "2022-02-21";
  };
  fish-colored-man = {
    pname = "fish-colored-man";
    version = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-colored-man";
      rev = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
      fetchSubmodules = false;
      sha256 = "sha256-uoZ4eSFbZlsRfISIkJQp24qPUNqxeD0JbRb/gVdRYlA=";
    };
    date = "2021-07-16";
  };
  fish-done = {
    pname = "fish-done";
    version = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
      fetchSubmodules = false;
      sha256 = "sha256-DMIRKRAVOn7YEnuAtz4hIxrU93ULxNoQhW6juxCoh4o=";
    };
    date = "2024-04-11";
  };
  fish-f = {
    pname = "fish-f";
    version = "6099f3a4b5d148674106a264fffc84dd5a4dfe35";
    src = fetchFromGitHub {
      owner = "gokulsoumya";
      repo = "f";
      rev = "6099f3a4b5d148674106a264fffc84dd5a4dfe35";
      fetchSubmodules = false;
      sha256 = "sha256-NSp4TCWjsVboT0xI+5zbWx2xr+S4go4zbR6nyxbUz8g=";
    };
    date = "2021-05-09";
  };
  fish-fzf = {
    pname = "fish-fzf";
    version = "479fa67d7439b23095e01b64987ae79a91a4e283";
    src = fetchFromGitHub {
      owner = "jethrokuan";
      repo = "fzf";
      rev = "479fa67d7439b23095e01b64987ae79a91a4e283";
      fetchSubmodules = false;
      sha256 = "sha256-28QW/WTLckR4lEfHv6dSotwkAKpNJFCShxmKFGQQ1Ew=";
    };
    date = "2021-05-12";
  };
  fish-gitnow = {
    pname = "fish-gitnow";
    version = "0cf3c89209305779e82d3b5cb956cf8b54025dd6";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "gitnow";
      rev = "0cf3c89209305779e82d3b5cb956cf8b54025dd6";
      fetchSubmodules = false;
      sha256 = "sha256-vNYUMzgBvPxHpeybhzBvyVL5RhM6qZlFtk3uZiiDvf8=";
    };
    date = "2024-10-12";
  };
  fish-sponge = {
    pname = "fish-sponge";
    version = "384299545104d5256648cee9d8b117aaa9a6d7be";
    src = fetchFromGitHub {
      owner = "meaningful-ooo";
      repo = "sponge";
      rev = "384299545104d5256648cee9d8b117aaa9a6d7be";
      fetchSubmodules = false;
      sha256 = "sha256-MdcZUDRtNJdiyo2l9o5ma7nAX84xEJbGFhAVhK+Zm1w=";
    };
    date = "2022-10-05";
  };
  fishbang = {
    pname = "fishbang";
    version = "0b5ef82ead524a7dd0da5760d8f677b02b35f654";
    src = fetchFromGitHub {
      owner = "brewingweasel";
      repo = "fishbang";
      rev = "0b5ef82ead524a7dd0da5760d8f677b02b35f654";
      fetchSubmodules = false;
      sha256 = "sha256-AbFSUz2C4ru0jclF60JOpzf7xWo0ffahEsM5hkNNtGw=";
    };
    date = "2023-08-04";
  };
  flatpak-compose = {
    pname = "flatpak-compose";
    version = "0.4.0";
    src = fetchFromGitHub {
      owner = "faan11";
      repo = "flatpak-compose";
      rev = "0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-BpsEelrtb5yWRiP70/wIsrYWS2aFl6tUFbQ8ChTrj+s=";
    };
  };
  focus = {
    pname = "focus";
    version = "v1.4.3";
    src = fetchFromGitHub {
      owner = "ayoisaiah";
      repo = "focus";
      rev = "v1.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-p9gTFUYHdyOY2EFT/ZmBHT7dRNm64s/3ExUXG7bfQ70=";
    };
  };
  fzf-kill = {
    pname = "fzf-kill";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "Zeioth";
      repo = "fzf-kill";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-Aa+jqcavFber+tAWUqPgV87sKKZS+5rGeJLS7RoYGLA=";
    };
  };
  game_2048_tui = {
    pname = "game_2048_tui";
    version = "v0.0.2";
    src = fetchFromGitHub {
      owner = "WanderHuang";
      repo = "game-2048-tui";
      rev = "v0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-/O548IEhGYSOSIG/xTGCi+P75poM5KY2AYW6lXRCtF0=";
    };
  };
  geminicommit = {
    pname = "geminicommit";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "tfkhdyt";
      repo = "geminicommit";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-wfSYR458uK47JtsiNrD3f6bD5HcfFf5WxlKdx8oLidY=";
    };
  };
  gg = {
    pname = "gg";
    version = "14e45a8e946eb7a04ebacc07e3a1f1f4235b1cd8";
    src = fetchFromGitHub {
      owner = "qw3rtman";
      repo = "gg";
      rev = "14e45a8e946eb7a04ebacc07e3a1f1f4235b1cd8";
      fetchSubmodules = false;
      sha256 = "sha256-+8WpnY9oBdDQ4fUj/xtsrx2w6LCfZIQjex+6BEk5qlk=";
    };
    date = "2022-12-27";
  };
  gh-branch = {
    pname = "gh-branch";
    version = "7ed0aff7601dc4162e0cac8835ecd73409d8a009";
    src = fetchFromGitHub {
      owner = "mislav";
      repo = "gh-branch";
      rev = "7ed0aff7601dc4162e0cac8835ecd73409d8a009";
      fetchSubmodules = false;
      sha256 = "sha256-yiRSXU/jLi067i+gBb3cEHTOuo+w3oEVsGL0NN6shl8=";
    };
    date = "2023-12-06";
  };
  gh-cp = {
    pname = "gh-cp";
    version = "58afdf5b5e1acfe71fce2390f6431003505ae0aa";
    src = fetchFromGitHub {
      owner = "mislav";
      repo = "gh-cp";
      rev = "58afdf5b5e1acfe71fce2390f6431003505ae0aa";
      fetchSubmodules = false;
      sha256 = "sha256-Ih3Wit0nnB8PrgbeZEuhTNVPCrwMWBmKMJSGmgLIrVY=";
    };
    date = "2021-11-08";
  };
  gh-screensaver = {
    pname = "gh-screensaver";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "vilmibm";
      repo = "gh-screensaver";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-MqwaqXGP4E+46vpgftZ9bttmMyENuojBnS6bWacmYLE=";
    };
  };
  gh-stars = {
    pname = "gh-stars";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "aymanbagabas";
      repo = "gh-stars";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-p1GLENa6UIXcasXbJtj5wpS2nMnJzT7V7k3pwfJOano=";
    };
  };
  git-cal = {
    pname = "git-cal";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "k4rthik";
      repo = "git-cal";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-fzzcxGre3YebvFrSRrul2L73mfQF/4ubsGVSPFzUSSM=";
    };
  };
  git-grab = {
    pname = "git-grab";
    version = "3.0.0";
    src = fetchFromGitHub {
      owner = "wezm";
      repo = "git-grab";
      rev = "3.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-MsJDfmWU6LyK7M0LjYQufIpKmtS4f2hgo4Yi/x1HsrU=";
    };
  };
  git-heatgrid = {
    pname = "git-heatgrid";
    version = "2263ce34d2929652e6cfe31fe076577dfcefd168";
    src = fetchFromGitHub {
      owner = "denshakhov";
      repo = "git-heatgrid";
      rev = "2263ce34d2929652e6cfe31fe076577dfcefd168";
      fetchSubmodules = false;
      sha256 = "sha256-nBiZfwiWmwM0a839NaDsCouJtL2d0HYHIZ+FFGrmzjM=";
    };
    date = "2024-05-13";
  };
  git-ink = {
    pname = "git-ink";
    version = "1.0.1";
    src = fetchFromGitHub {
      owner = "davidosomething";
      repo = "git-ink";
      rev = "1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-OiAajjMXyLezEXNxmHnwZZBP0lZEYmRGUkxh6xEoThw=";
    };
  };
  git-issue = {
    pname = "git-issue";
    version = "d056998566d30235072b97982756ff607e9ecce9";
    src = fetchFromGitHub {
      owner = "dspinellis";
      repo = "git-issue";
      rev = "d056998566d30235072b97982756ff607e9ecce9";
      fetchSubmodules = false;
      sha256 = "sha256-VYMIgJRcXKlhX05tfILA8dB8x3lcR6nX6vdls79cAgA=";
    };
    date = "2024-05-17";
  };
  git-of-theseus = {
    pname = "git-of-theseus";
    version = "961bda027ffa9fcd8bbe99d5b8809cc0eaa86464";
    src = fetchFromGitHub {
      owner = "erikbern";
      repo = "git-of-theseus";
      rev = "961bda027ffa9fcd8bbe99d5b8809cc0eaa86464";
      fetchSubmodules = false;
      sha256 = "sha256-FZXLJbximJWrDyuRril6whlOYWppGLns3k8sDNRmOuI=";
    };
    date = "2023-11-25";
  };
  git-playback = {
    pname = "git-playback";
    version = "0d4a51993b8a1b58579964e883fd344f6b92763b";
    src = fetchFromGitHub {
      owner = "jianli";
      repo = "git-playback";
      rev = "0d4a51993b8a1b58579964e883fd344f6b92763b";
      fetchSubmodules = false;
      sha256 = "sha256-lHqr+4dFFbktTI1J4Qu3t3BmV6xA32H2o5yOgaJJcNs=";
    };
    date = "2016-03-22";
  };
  git-spend = {
    pname = "git-spend";
    version = "1.2.1";
    src = fetchFromGitHub {
      owner = "Goutte";
      repo = "git-spend";
      rev = "1.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-4bR5CVM1zTSdLiHyigYgmvpO1VDM6rteeBHuADXq2pk=";
    };
  };
  git-stats = {
    pname = "git-stats";
    version = "3.2.0";
    src = fetchFromGitHub {
      owner = "IonicaBizau";
      repo = "git-stats";
      rev = "3.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-LhsesKHPggV7asOcJCPS/o4O5jP4WVlSiDXIWlyj8Yc=";
    };
  };
  git-sumi = {
    pname = "git-sumi";
    version = "v0.0.9";
    src = fetchFromGitHub {
      owner = "welpo";
      repo = "git-sumi";
      rev = "v0.0.9";
      fetchSubmodules = false;
      sha256 = "sha256-ZSpQJeiGn6J8G/35PTW6pRzPhTRW1Op3gakx/yXB3Zc=";
    };
  };
  git-toolbelt = {
    pname = "git-toolbelt";
    version = "v1.9.3";
    src = fetchFromGitHub {
      owner = "nvie";
      repo = "git-toolbelt";
      rev = "v1.9.3";
      fetchSubmodules = false;
      sha256 = "sha256-ANqv/iIDUyy2G4pKSw+2sutMEA0WhPN3OKfPTm5lwDU=";
    };
  };
  gitcs = {
    pname = "gitcs";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "knbr13";
      repo = "gitcs";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-IyhVVRTKftZIzqMH5pBUMLPIk8bk0rVAxPKD6bABP68=";
    };
  };
  github-dlr = {
    pname = "github-dlr";
    version = "0.1.2";
    src = fetchFromGitHub {
      owner = "rocktimsaikia";
      repo = "github-dlr";
      rev = "0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-vXLrX3gWx1K77TA79dOxaC2U59ZWpS0PGQnUHIb+BxI=";
    };
  };
  gitty = {
    pname = "gitty";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "worlpaker";
      repo = "gitty";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-+jKMp13EVbsJ67Uklg/XjULbHTpscfLSfRTjhjzKnHw=";
    };
  };
  gogitmoji = {
    pname = "gogitmoji";
    version = "v1.1.5";
    src = fetchFromGitHub {
      owner = "jamesdobson";
      repo = "gogitmoji";
      rev = "v1.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-mXJga9Y1ZA7htzCEyMIuyj2oMjyFOj/Z/2U/yzLfQPw=";
    };
  };
  goji = {
    pname = "goji";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "muandane";
      repo = "goji";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-By4BQN7ftja4VMdxaksbQqtUcgjaQhF0ORUWZspmho8=";
    };
  };
  goodls = {
    pname = "goodls";
    version = "v2.0.5";
    src = fetchFromGitHub {
      owner = "tanaikech";
      repo = "goodls";
      rev = "v2.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-SrDDRQvogsYtdp8El/NOeeTOg0RKqaR3m7dq4Lhqrps=";
    };
  };
  grip-grab = {
    pname = "grip-grab";
    version = "v0.5.5";
    src = fetchFromGitHub {
      owner = "alexpasmantier";
      repo = "grip-grab";
      rev = "v0.5.5";
      fetchSubmodules = false;
      sha256 = "sha256-T3tla6Gf9lUQ+F8D57glzmfsmuX5FV806zuKQxYt2lw=";
    };
  };
  gtm = {
    pname = "gtm";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "git-time-metric";
      repo = "gtm";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-O09wFBT45ExkIYVhnVVOAcHbB4SHeaA+SaDilA8qW3g=";
    };
  };
  gtm-vim-plugin = {
    pname = "gtm-vim-plugin";
    version = "ebd33f7d01a7ac9b2695f71b1136d6b89a0d5d44";
    src = fetchFromGitHub {
      owner = "git-time-metric";
      repo = "gtm-vim-plugin";
      rev = "ebd33f7d01a7ac9b2695f71b1136d6b89a0d5d44";
      fetchSubmodules = false;
      sha256 = "sha256-rAbcwJ6Frgj6s1lPP0iUVJn39w0vzCvg2ImOaQD2+2w=";
    };
    date = "2017-04-16";
  };
  gw = {
    pname = "gw";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "daniel7grant";
      repo = "gw";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-oexh8/iPVdJoU5PzEypho4+LSsAkHHByz0ZNCWYtHNA=";
    };
  };
  hexpatch = {
    pname = "hexpatch";
    version = "v1.9.0";
    src = fetchFromGitHub {
      owner = "Etto48";
      repo = "HexPatch";
      rev = "v1.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-yyYxRJ+o+Z5z7PmjcFCsahRXZ9JHFmGmituzGTxY6ec=";
    };
  };
  hl = {
    pname = "hl";
    version = "v0.29.8";
    src = fetchFromGitHub {
      owner = "pamburus";
      repo = "hl";
      rev = "v0.29.8";
      fetchSubmodules = false;
      sha256 = "sha256-YL9DWVArUf+ZdldTyTY4Y2rDMofwZJ8o6PsVECkr2q0=";
    };
  };
  hypergrep = {
    pname = "hypergrep";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "p-ranav";
      repo = "hypergrep";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-kzM8MGic/bGGKr7CdCCFbmpVR4TA356lDFMDa+9U25Q=";
    };
  };
  images-upload-cli = {
    pname = "images-upload-cli";
    version = "v3.0.4";
    src = fetchFromGitHub {
      owner = "DeadNews";
      repo = "images-upload-cli";
      rev = "v3.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-UHXhudNqyL/efA+7D2BZYsKPHVJ5/ObTH6gEnOn/+bI=";
    };
  };
  impala = {
    pname = "impala";
    version = "v0.2.3";
    src = fetchFromGitHub {
      owner = "pythops";
      repo = "Impala";
      rev = "v0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-4LQmM4VTW3ykh6eDWKxBe3jxlJphgAytgeaQZNwivsQ=";
    };
  };
  jalm = {
    pname = "jalm";
    version = "f1e79605af1b4852b2a5dbfcc4674a5c14fc551d";
    src = fetchFromGitHub {
      owner = "neelkarma";
      repo = "jalm";
      rev = "f1e79605af1b4852b2a5dbfcc4674a5c14fc551d";
      fetchSubmodules = false;
      sha256 = "sha256-xwB6IXQX4bch+j+VhWicEz4MIsdjld29q0CJZvAhulI=";
    };
    date = "2022-10-08";
  };
  jerry = {
    pname = "jerry";
    version = "e8d15983a90a0be583419637b46723192ef5c1d3";
    src = fetchFromGitHub {
      owner = "justchokingaround";
      repo = "Jerry";
      rev = "e8d15983a90a0be583419637b46723192ef5c1d3";
      fetchSubmodules = false;
      sha256 = "sha256-VEb9mrAXGmD9EYzU/W/E7sPoWw4eMBd2q0n2s8dqLls=";
    };
    date = "2024-09-29";
  };
  jtbl = {
    pname = "jtbl";
    version = "v1.6.0";
    src = fetchFromGitHub {
      owner = "kellyjonbrazil";
      repo = "Jtbl";
      rev = "v1.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-ILQwUpjNueaYR5hxOWd5kZSPhVoFnnS2FcttyKSTPr8=";
    };
  };
  koji = {
    pname = "koji";
    version = "2.2.0";
    src = fetchFromGitHub {
      owner = "cococonscious";
      repo = "Koji";
      rev = "2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-2kBjHX7izo4loJ8oyPjE9FtCvUODC3Sm4T8ETIdeGZM=";
    };
  };
  lain = {
    pname = "lain";
    version = "88f5a8abd2649b348ffec433a24a263b37f122c0";
    src = fetchFromGitHub {
      owner = "lcpz";
      repo = "lain";
      rev = "88f5a8abd2649b348ffec433a24a263b37f122c0";
      fetchSubmodules = false;
      sha256 = "sha256-MH/aiYfcO3lrcuNbnIu4QHqPq25LwzTprOhEJUJBJ7I=";
    };
    date = "2023-01-12";
  };
  lite-xl-vibe = {
    pname = "lite-xl-vibe";
    version = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
    src = fetchFromGitHub {
      owner = "eugenpt";
      repo = "lite-xl-vibe";
      rev = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
      fetchSubmodules = false;
      sha256 = "sha256-JSTYmfiy0BeBCVXxOLkXf9SaxPTWrsAam2ZQKn0hk4M=";
    };
    date = "2023-10-31";
  };
  lobster = {
    pname = "lobster";
    version = "v4.3.0";
    src = fetchFromGitHub {
      owner = "justchokingaround";
      repo = "Lobster";
      rev = "v4.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-ch91LYKs6MswTC08Xi8VcIxooWvDprGuIn0B2Yo3ufo=";
    };
  };
  lobtui = {
    pname = "lobtui";
    version = "v0.3";
    src = fetchFromGitHub {
      owner = "pythops";
      repo = "lobtui";
      rev = "v0.3";
      fetchSubmodules = false;
      sha256 = "sha256-Vc6fh0XbSYNCQWosP7cOfphJin6Z5AJdcfSNdd38cKs=";
    };
  };
  lookatme = {
    pname = "lookatme";
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "d0c-s4vage";
      repo = "lookatme";
      rev = "v2.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-mn28OLIlxk97aDow1dTBsMRxVTkCqVeiAtrlyh8zJTg=";
    };
  };
  lssh = {
    pname = "lssh";
    version = "v0.6.13";
    src = fetchFromGitHub {
      owner = "blacknon";
      repo = "lssh";
      rev = "v0.6.13";
      fetchSubmodules = false;
      sha256 = "sha256-0dxkFOXNaOmIjKuhmTsfQmS+Nf8QiM5txmI8p1XcqTQ=";
    };
  };
  machma = {
    pname = "machma";
    version = "9ab93d72e36fe2cbb15af37c914605212ac28642";
    src = fetchFromGitHub {
      owner = "fd0";
      repo = "machma";
      rev = "9ab93d72e36fe2cbb15af37c914605212ac28642";
      fetchSubmodules = false;
      sha256 = "sha256-VmyWAsWIe6dhLq7UEit389v3fnQqRwZYk5gY6gj6Q3M=";
    };
    date = "2021-01-02";
  };
  makedown = {
    pname = "makedown";
    version = "4418bd111b4f86d0e35038d45332153c263c2d06";
    src = fetchFromGitHub {
      owner = "tzador";
      repo = "makedown";
      rev = "4418bd111b4f86d0e35038d45332153c263c2d06";
      fetchSubmodules = false;
      sha256 = "sha256-6oZawRzQ/Q++ydqDZ2CfYyxLz9xQO8IdB/qR5JgmD8A=";
    };
    date = "2024-10-18";
  };
  manga-tui = {
    pname = "manga-tui";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "josueBarretogit";
      repo = "manga-tui";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-672AuQWviwihnUS3G0xSn4IAMHy0fPE1VLDfu8wrPGg=";
    };
  };
  mdtt = {
    pname = "mdtt";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "szktkfm";
      repo = "mdtt";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-OFS/ZhXdvdmlpfCNutsvlhMv1krFlx4Xju8RSl3GS2s=";
    };
  };
  minimal-tmux-status = {
    pname = "minimal-tmux-status";
    version = "672b230313fa238e569c672eb30a0677982156bf";
    src = fetchFromGitHub {
      owner = "niksingh710";
      repo = "minimal-tmux-status";
      rev = "672b230313fa238e569c672eb30a0677982156bf";
      fetchSubmodules = false;
      sha256 = "sha256-0PROCM7iirKywY4SYjVkAgUio+NxjsCM+4TdiXjcuaw=";
    };
    date = "2024-10-19";
  };
  miru = {
    pname = "miru";
    version = "v5.5.6";
    src = fetchFromGitHub {
      owner = "ThaUnknown";
      repo = "miru";
      rev = "v5.5.6";
      fetchSubmodules = false;
      sha256 = "sha256-T32a7xcgPeDSmRjW10iSvIuTgFOM3KONPbxaV1y+sRY=";
    };
  };
  mpv-M-x = {
    pname = "mpv-M-x";
    version = "229cb615e701fafa8d7c3077286053243b252525";
    src = fetchFromGitHub {
      owner = "Seme4eg";
      repo = "mpv-scripts";
      rev = "229cb615e701fafa8d7c3077286053243b252525";
      fetchSubmodules = false;
      sha256 = "sha256-xekWIjqVkan1XS7dIqt5iZzI+CgByb9OjYE+GULYgMs=";
    };
    date = "2024-08-16";
  };
  mpv-autoloop = {
    pname = "mpv-autoloop";
    version = "a8920592a4dbda574b51ddc6c2000851a13549a5";
    src = fetchFromGitHub {
      owner = "zc62";
      repo = "mpv-scripts";
      rev = "a8920592a4dbda574b51ddc6c2000851a13549a5";
      fetchSubmodules = false;
      sha256 = "sha256-pot53UjIJjzehLGxku16dNG1DBwXuOZ7FXQtmnezhwY=";
    };
    date = "2020-08-28";
  };
  mpv-blur-edges = {
    pname = "mpv-blur-edges";
    version = "d0390c8e802c2e888ff4a2e1d5e4fb040f855b89";
    src = fetchFromGitHub {
      owner = "occivink";
      repo = "mpv-scripts";
      rev = "d0390c8e802c2e888ff4a2e1d5e4fb040f855b89";
      fetchSubmodules = false;
      sha256 = "sha256-pc2aaO7lZaoYMEXv5M0WI7PtmqgkNbdtNiLZZwVzppM=";
    };
    date = "2024-01-11";
  };
  mpv-smartcopypaste_ii = {
    pname = "mpv-smartcopypaste_ii";
    version = "48d68283cea47ff8e904decc9003b3abc3e2123e";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "48d68283cea47ff8e904decc9003b3abc3e2123e";
      fetchSubmodules = false;
      sha256 = "sha256-95CAKjBRELX2f7oWSHFWJnI0mikAoxhfUphe9k51Qf4=";
    };
    date = "2023-11-25";
  };
  mpv-smartskip = {
    pname = "mpv-smartskip";
    version = "48d68283cea47ff8e904decc9003b3abc3e2123e";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "48d68283cea47ff8e904decc9003b3abc3e2123e";
      fetchSubmodules = false;
      sha256 = "sha256-95CAKjBRELX2f7oWSHFWJnI0mikAoxhfUphe9k51Qf4=";
    };
    date = "2023-11-25";
  };
  neonmodem = {
    pname = "neonmodem";
    version = "v1.0.6";
    src = fetchFromGitHub {
      owner = "mrusme";
      repo = "neonmodem";
      rev = "v1.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-VLR6eicffA0IXVwEZMvgpm1kVmrLYVZOtq7MSy+vIw8=";
    };
  };
  nix-auto-follow = {
    pname = "nix-auto-follow";
    version = "a76c20cd36fb2b6fa4a58be4c5edf4ae6e143648";
    src = fetchFromGitHub {
      owner = "fzakaria";
      repo = "nix-auto-follow";
      rev = "a76c20cd36fb2b6fa4a58be4c5edf4ae6e143648";
      fetchSubmodules = false;
      sha256 = "sha256-pK8hV2W7MkgBgY0g+LwhlaWJH79lCHfZQInT6s/mZp4=";
    };
    date = "2024-08-20";
  };
  nrf-udev = {
    pname = "nrf-udev";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "NordicSemiconductor";
      repo = "nrf-udev";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-bEIAsz9ZwX6RTzhv5/waFZ5a3KlnwX4kQs29+475zN0=";
    };
  };
  numara = {
    pname = "numara";
    version = "v5.5.0";
    src = fetchFromGitHub {
      owner = "bornova";
      repo = "numara-calculator";
      rev = "v5.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-JumAFKIp2Q56FdhDagjoqPlIQAzHB1SP+yBt1yW+5N4=";
    };
  };
  org-export = {
    pname = "org-export";
    version = "64ac299c041877620c2cadba83ded44f46c4e124";
    src = fetchFromGitHub {
      owner = "nhoffman";
      repo = "org-export";
      rev = "64ac299c041877620c2cadba83ded44f46c4e124";
      fetchSubmodules = false;
      sha256 = "sha256-GIkkYary9R3mf9r9QW0fgmnutMlhIp7PhM9KX7kXiuQ=";
    };
    date = "2023-10-25";
  };
  otree = {
    pname = "otree";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "fioncat";
      repo = "otree";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-M6xmz7aK+NNZUDN8NJCUEODwotJ9VeY3bsueFpwjjjs=";
    };
  };
  pangu-vim = {
    pname = "pangu-vim";
    version = "b7210117695dca05d94de1ac2108401f8eff0a2d";
    src = fetchFromGitHub {
      owner = "hotoo";
      repo = "pangu.vim";
      rev = "b7210117695dca05d94de1ac2108401f8eff0a2d";
      fetchSubmodules = false;
      sha256 = "sha256-MvT/3keKv05ZetWnKRA9nD2AyJKoyeLV7rtPlCCl98Q=";
    };
    date = "2023-02-19";
  };
  parinfer-rust = {
    pname = "parinfer-rust";
    version = "d84828b453e158d06406f6b5e9056f6b54ff76c9";
    src = fetchFromGitHub {
      owner = "eraserhd";
      repo = "parinfer-rust";
      rev = "d84828b453e158d06406f6b5e9056f6b54ff76c9";
      fetchSubmodules = false;
      sha256 = "sha256-Q2fYogfn5QcNDEie4sUaVydAmDmcFXnsvz35cxPCf+M=";
    };
    date = "2024-05-07";
  };
  pik = {
    pname = "pik";
    version = "fcb9d7eb7dfcb62d0c93e32dd462be1728c3096e";
    src = fetchFromGitHub {
      owner = "immanelg";
      repo = "pik";
      rev = "fcb9d7eb7dfcb62d0c93e32dd462be1728c3096e";
      fetchSubmodules = false;
      sha256 = "sha256-s13olb4J3f9DZpGqi3CRwx7Q7zWIe6PyLZmnBI+USnk=";
    };
    date = "2024-08-28";
  };
  play = {
    pname = "play";
    version = "v0.3.3";
    src = fetchFromGitHub {
      owner = "paololazzari";
      repo = "play";
      rev = "v0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-l6nYyfNqm3hunNQqteQWAVJSdeJG2O2FPb6IypHw6CA=";
    };
  };
  pnut = {
    pname = "pnut";
    version = "f30d6fda77339ae57f480c0086660a01fde003f6";
    src = fetchFromGitHub {
      owner = "udem-dlteam";
      repo = "pnut";
      rev = "f30d6fda77339ae57f480c0086660a01fde003f6";
      fetchSubmodules = false;
      sha256 = "sha256-UQ+6MbTrxMgL5h2kK19X5wxhFQ3FSBvtCWA/RQw8CvU=";
    };
    date = "2024-10-19";
  };
  posting = {
    pname = "posting";
    version = "2.0.0";
    src = fetchFromGitHub {
      owner = "darrenburns";
      repo = "posting";
      rev = "2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-zxSLZGkc/svEgMmhKxuAZDwWf5S4RtOn9BYMDuToa3M=";
    };
  };
  pot = {
    pname = "pot";
    version = "3.0.5";
    src = fetchFromGitHub {
      owner = "pot-app";
      repo = "pot-desktop";
      rev = "3.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-Y0/N5xunEXOG+FuZE23xsSwFd6PL1XClV5UIckTYNPs=";
    };
  };
  puffer-fish = {
    pname = "puffer-fish";
    version = "12d062eae0ad24f4ec20593be845ac30cd4b5923";
    src = fetchFromGitHub {
      owner = "nickeb96";
      repo = "puffer-fish";
      rev = "12d062eae0ad24f4ec20593be845ac30cd4b5923";
      fetchSubmodules = false;
      sha256 = "sha256-2niYj0NLfmVIQguuGTA7RrPIcorJEPkxhH6Dhcy+6Bk=";
    };
    date = "2024-03-03";
  };
  pydantic = {
    pname = "pydantic";
    version = "2.9.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic/pydantic-2.9.2.tar.gz";
      sha256 = "sha256-0VXO9xJl0emAftHDK0yN7sBCpEpQpBiLJaxn7NganA8=";
    };
  };
  pydantic-core = {
    pname = "pydantic-core";
    version = "2.24.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic_core/pydantic_core-2.24.2.tar.gz";
      sha256 = "sha256-RJcpj8Y4Hj4aYcdP7DCI2BObmWmBd/vC3Ke3/rWuHCA=";
    };
  };
  pydantic-settings = {
    pname = "pydantic-settings";
    version = "2.6.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic_settings/pydantic_settings-2.6.0.tar.gz";
      sha256 = "sha256-RKGASr/6yeajA3K7RfbK+rlF71ryXmaxxjTAHdOeAYg=";
    };
  };
  quartz = {
    pname = "quartz";
    version = "64686482cb9e8a24a53d44134497a600eaa5d275";
    src = fetchFromGitHub {
      owner = "vimpostor";
      repo = "quartz";
      rev = "64686482cb9e8a24a53d44134497a600eaa5d275";
      fetchSubmodules = false;
      sha256 = "sha256-sDMD68hwSEcFAEfuv1sn3JcGCL8bRSYxkgv24vrwcb4=";
    };
    date = "2024-10-03";
  };
  radio-go-go = {
    pname = "radio-go-go";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "matteo-pacini";
      repo = "RadioGoGo";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-vEZUBA+KeDHgqZvzrAN6ramZ5D4iqQdVU+qFOK/39co=";
    };
  };
  ranger-devicons2 = {
    pname = "ranger-devicons2";
    version = "9606009aa01743768b0f27de0a841f7d8fe196c5";
    src = fetchFromGitHub {
      owner = "cdump";
      repo = "ranger-devicons2";
      rev = "9606009aa01743768b0f27de0a841f7d8fe196c5";
      fetchSubmodules = false;
      sha256 = "sha256-T96+7dX/7B0BKOJgVDg55+Zonp9sSt6SvmLGknhL8Gg=";
    };
    date = "2024-07-29";
  };
  ranger-zoxide = {
    pname = "ranger-zoxide";
    version = "281828de060299f73fe0b02fcabf4f2f2bd78ab3";
    src = fetchFromGitHub {
      owner = "jchook";
      repo = "ranger-zoxide";
      rev = "281828de060299f73fe0b02fcabf4f2f2bd78ab3";
      fetchSubmodules = false;
      sha256 = "sha256-JEuyYSVa1NS3aftezEJx/k19lwwzf7XhqBCL0jH6VT4=";
    };
    date = "2024-02-08";
  };
  rat = {
    pname = "rat";
    version = "397b4d7faabc59c9da6ae1abbff877f8ae83fc4b";
    src = fetchFromGitHub {
      owner = "ericfreese";
      repo = "rat";
      rev = "397b4d7faabc59c9da6ae1abbff877f8ae83fc4b";
      fetchSubmodules = false;
      sha256 = "sha256-/DAK2lc/4Vh1+fJa6blUBdoWWrnftBy9lcR7xx48WQM=";
    };
    date = "2021-09-23";
  };
  reader = {
    pname = "reader";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "mrusme";
      repo = "reader";
      rev = "v0.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-9hZ7ZS+p6PoLKcuHS2re537wxojN2SzhOm5gBuRX9Xc=";
    };
  };
  repoblame = {
    pname = "repoblame";
    version = "66c7eb2ce6a62f60be1711e8975c1b582ec39045";
    src = fetchFromGitHub {
      owner = "martinn";
      repo = "repoblame";
      rev = "66c7eb2ce6a62f60be1711e8975c1b582ec39045";
      fetchSubmodules = false;
      sha256 = "sha256-CjjDh0Go4gEDFdUHEsTtnIdwR8Aokz0DIMzu/h7tIOA=";
    };
    date = "2024-09-15";
  };
  rexi = {
    pname = "rexi";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "royreznik";
      repo = "rexi";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-tag2/QTM6tDCU3qr4e1GqRYAZgpvEgtA+FtR4P7WdiU=";
    };
  };
  "rgg.fish" = {
    pname = "rgg.fish";
    version = "00a852b7d62553b24b8f1bf65d63744ff40c0e5c";
    src = fetchFromGitHub {
      owner = "soraxas";
      repo = "rgg.fish";
      rev = "00a852b7d62553b24b8f1bf65d63744ff40c0e5c";
      fetchSubmodules = false;
      sha256 = "sha256-PjQpoORrYxgt2/2gonOZDambOq4ZMtLmijxwZYlISIk=";
    };
    date = "2024-07-21";
  };
  rimage = {
    pname = "rimage";
    version = "v0.10.3";
    src = fetchFromGitHub {
      owner = "SalOne22";
      repo = "rimage";
      rev = "v0.10.3";
      fetchSubmodules = false;
      sha256 = "sha256-GfxnZ9fuok4/6BGrCZHD+hslCaHYUv16/8jreK+9JEI=";
    };
  };
  rsv = {
    pname = "rsv";
    version = "v0.4.14";
    src = fetchFromGitHub {
      owner = "ribbondz";
      repo = "rsv";
      rev = "v0.4.14";
      fetchSubmodules = false;
      sha256 = "sha256-LKom7cLu4P95Vg9m/cP/CfWjeU5tcenejgNQhKPs8uM=";
    };
  };
  rust-kanban = {
    pname = "rust-kanban";
    version = "v0.10.4";
    src = fetchFromGitHub {
      owner = "yashs662";
      repo = "rust_kanban";
      rev = "v0.10.4";
      fetchSubmodules = false;
      sha256 = "sha256-1sCc5ChDTYEo+WYsyYvmxJJ/JXtd/uPtUeKBjYjXcHU=";
    };
  };
  rustywatch = {
    pname = "rustywatch";
    version = "v0.2.11";
    src = fetchFromGitHub {
      owner = "ak9024";
      repo = "rustywatch";
      rev = "v0.2.11";
      fetchSubmodules = false;
      sha256 = "sha256-UzMLSPBH/ElpEWnPV2zD1+2Pt6pO4cG7CmgJvy1MawM=";
    };
  };
  s = {
    pname = "s";
    version = "v0.7.1";
    src = fetchFromGitHub {
      owner = "zquestz";
      repo = "s";
      rev = "v0.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-cu2XGA5rRO+cHZ9QkJvMBjbxNZigxsx12ziCJG1LCQs=";
    };
  };
  sake = {
    pname = "sake";
    version = "v0.15.1";
    src = fetchFromGitHub {
      owner = "alajmo";
      repo = "sake";
      rev = "v0.15.1";
      fetchSubmodules = false;
      sha256 = "sha256-aTbom8J4S0ZCiHPfAPeFKZ+15PxG64dGqQtOKXuEBo8=";
    };
  };
  sbsrf-rime-data = {
    pname = "sbsrf-rime-data";
    version = "20241016";
    src = fetchFromGitHub {
      owner = "sbsrf";
      repo = "sbsrf";
      rev = "20241016";
      fetchSubmodules = false;
      sha256 = "sha256-5tZT4syf6MPBOmIjZjnjsoFWuXwtdhsvFF8/vULJs6w=";
    };
  };
  serie = {
    pname = "serie";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "lusingander";
      repo = "serie";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-RP9Tv6IrDfawjXCQp0nB0nd7b6IwkdykHcEfGEguFHo=";
    };
  };
  serpl = {
    pname = "serpl";
    version = "0.3.3";
    src = fetchFromGitHub {
      owner = "yassinebridi";
      repo = "serpl";
      rev = "0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-koD5aFqL+XVxc5Iq3reTYIHiPm0z7hAQ4K59IfbY4Hg=";
    };
  };
  shipit = {
    pname = "shipit";
    version = "0.4.0";
    src = fetchFromGitHub {
      owner = "sapegin";
      repo = "shipit";
      rev = "0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-gT+4b1D4kfy39CuFIR/eF316Ep8E1Ef74wuebljfhI4=";
    };
  };
  sig = {
    pname = "sig";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "ynqa";
      repo = "sig";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-nt/KV4ohFNZTJTwbNoSxb5v9zQwp+7ypvfMthL1yMus=";
    };
  };
  simple-completion-language-server = {
    pname = "simple-completion-language-server";
    version = "b1d39467ef2780266e5fe5ee9b7b49083adf08b3";
    src = fetchFromGitHub {
      owner = "estin";
      repo = "simple-completion-language-server";
      rev = "b1d39467ef2780266e5fe5ee9b7b49083adf08b3";
      fetchSubmodules = false;
      sha256 = "sha256-SESiYrdPruQg4gV92OTcrKSClh3xyo5wkQ3NdN7e30M=";
    };
    date = "2024-10-08";
  };
  soba = {
    pname = "soba";
    version = "1.2.20";
    src = fetchFromGitHub {
      owner = "jonhadfield";
      repo = "soba";
      rev = "1.2.20";
      fetchSubmodules = false;
      sha256 = "sha256-DOAdhTEVwjV0uhG2jo35lp66W5znoyM0K36pSkW8clE=";
    };
  };
  sonicradio = {
    pname = "sonicradio";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "dancnb";
      repo = "sonicradio";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-i9IBe5jcCCzWRxu+dbx3neu5jakZe/Zzi3+FgtYNynk=";
    };
  };
  ssh-tpm-agent = {
    pname = "ssh-tpm-agent";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "Foxboron";
      repo = "ssh-tpm-agent";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-yK7G+wZIn+kJazKOFOs8EYlRWZkCQuT0qZfmdqbcOnM=";
    };
  };
  sunbeam = {
    pname = "sunbeam";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "pomdtr";
      repo = "sunbeam";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-X5LPRrI5VVCLnZLrjLyocexmReS5RdmQyJbbAvwFxs0=";
    };
  };
  svgshift = {
    pname = "svgshift";
    version = "5a24a7e661a6056c994d1bf1b4ef63b8dd506ada";
    src = fetchFromGitHub {
      owner = "10xJSChad";
      repo = "svgshift";
      rev = "5a24a7e661a6056c994d1bf1b4ef63b8dd506ada";
      fetchSubmodules = false;
      sha256 = "sha256-je9ZbXTFKq3tA3aE0QTu70Sco45rQyLW+lS6//zNCmw=";
    };
    date = "2024-08-20";
  };
  tabry-rs = {
    pname = "tabry-rs";
    version = "58bf619e2f90102d0678de056d9b9088ad7d179a";
    src = fetchFromGitHub {
      owner = "evanbattaglia";
      repo = "tabry-rs";
      rev = "58bf619e2f90102d0678de056d9b9088ad7d179a";
      fetchSubmodules = false;
      sha256 = "sha256-iWl16BEYMSQ1cvJJqkJ8anhrJui033NZeoLmockyarw=";
    };
    date = "2024-10-11";
  };
  task-relative-recur = {
    pname = "task-relative-recur";
    version = "5d4ab7d0a5e3f697fb2a00790972e6f3f705fe42";
    src = fetchFromGitHub {
      owner = "mlaradji";
      repo = "task-relative-recur";
      rev = "5d4ab7d0a5e3f697fb2a00790972e6f3f705fe42";
      fetchSubmodules = false;
      sha256 = "sha256-oPK67wG0wiUZCgCMtdwvK8w/WKjq3fMbZ9G1HVuVO6Q=";
    };
    date = "2023-02-06";
  };
  taskwarrior-better-recur = {
    pname = "taskwarrior-better-recur";
    version = "2731e1c441d81a3b2217b132e1f40ce4ea49ec5f";
    src = fetchFromGitHub {
      owner = "scottyob";
      repo = "taskwarrior-better-recur";
      rev = "2731e1c441d81a3b2217b132e1f40ce4ea49ec5f";
      fetchSubmodules = false;
      sha256 = "sha256-FpUX+6cOZUhv2ZDHwqlwyl1413RJaekvBADZ4486YPU=";
    };
    date = "2024-07-04";
  };
  termsand = {
    pname = "termsand";
    version = "75a50ba82ed299047cd5d0cd53b6fce390cfc6e8";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "termsand";
      rev = "75a50ba82ed299047cd5d0cd53b6fce390cfc6e8";
      fetchSubmodules = false;
      sha256 = "sha256-tylzyjg3AJutwnrxjxzshEfuTD14VegCIMb/wroGpj0=";
    };
    date = "2024-08-15";
  };
  tewi = {
    pname = "tewi";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "anlar";
      repo = "tewi";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-tCbfpuiV/Conxf1SoRc014+55eLSMEaxfbXecrrqEHU=";
    };
  };
  textual = {
    pname = "textual";
    version = "0.83.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/textual/textual-0.83.0.tar.gz";
      sha256 = "sha256-/DuXeWCS2cfmheU5Lzjz6yAH/+GzsThN7m0/ENJWur0=";
    };
  };
  textual-autocomplete = {
    pname = "textual-autocomplete";
    version = "3.0.0a12";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/textual_autocomplete/textual_autocomplete-3.0.0a12.tar.gz";
      sha256 = "sha256-HSyeTSTH9XWryMYSy2q//0cG9qqrm5OVBrldroRUkwk=";
    };
  };
  tmux-auto-renumber-session = {
    pname = "tmux-auto-renumber-session";
    version = "19fead0395afdc36830d840249c0c7190ccd8bb9";
    src = fetchFromGitHub {
      owner = "T1erno";
      repo = "tmux-auto-renumber-session";
      rev = "19fead0395afdc36830d840249c0c7190ccd8bb9";
      fetchSubmodules = false;
      sha256 = "sha256-An92IORTC2aeKGkUcAEj8gLPd9t5V3FE4EaAHF4LDoA=";
    };
    date = "2023-03-01";
  };
  tmux-continuum = {
    pname = "tmux-continuum";
    version = "c7ae4f4f4a1c5b7a00718f71742eb3d3ebd9b82a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-continuum";
      rev = "c7ae4f4f4a1c5b7a00718f71742eb3d3ebd9b82a";
      fetchSubmodules = false;
      sha256 = "sha256-YqQvKWQ+nPxGJoA4LQVWAuRt9gzLsF7bi/KB4uofpe8=";
    };
    date = "2024-07-08";
  };
  tmux-edgelord = {
    pname = "tmux-edgelord";
    version = "a390528534bf8e0f050daa1776db555eba4fadd9";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-edgelord";
      rev = "a390528534bf8e0f050daa1776db555eba4fadd9";
      fetchSubmodules = false;
      sha256 = "sha256-jermraRckdUz3BQCJVKcF1DyuKhnUzfSBJcCicXC7Q4=";
    };
    date = "2024-07-08";
  };
  tmux-fzf-url = {
    pname = "tmux-fzf-url";
    version = "28ed7ce3c73a328d8463d4f4aaa6ccb851e520fa";
    src = fetchFromGitHub {
      owner = "wfxr";
      repo = "tmux-fzf-url";
      rev = "28ed7ce3c73a328d8463d4f4aaa6ccb851e520fa";
      fetchSubmodules = false;
      sha256 = "sha256-tl0SjG/CeolrN7OIHj6MgkB9lFmFgEuJevsSuwVs+78=";
    };
    date = "2024-04-14";
  };
  tmux-kanagawa = {
    pname = "tmux-kanagawa";
    version = "fc95d797ba24536bffe3f2b2101e7d7ec3e5aaa1";
    src = fetchFromGitHub {
      owner = "Nybkox";
      repo = "tmux-kanagawa";
      rev = "fc95d797ba24536bffe3f2b2101e7d7ec3e5aaa1";
      fetchSubmodules = false;
      sha256 = "sha256-vCgqXrT7qukAmx/DUu4H6CT997pdiKOKA0CjLTWEALQ=";
    };
    date = "2024-07-17";
  };
  tmux-loadavg = {
    pname = "tmux-loadavg";
    version = "91319eff74ee677efb77c882dcc8e3b8780dc3a2";
    src = fetchFromGitHub {
      owner = "jamesoff";
      repo = "tmux-loadavg";
      rev = "91319eff74ee677efb77c882dcc8e3b8780dc3a2";
      fetchSubmodules = false;
      sha256 = "sha256-JW/O/bVryDILlFCnWYRC+B7nrCIsGYEJDozzu0odX+U=";
    };
    date = "2018-05-30";
  };
  tmux-pane-focus = {
    pname = "tmux-pane-focus";
    version = "94adfd620bee88b9262fe28df6b07a23e82f3a5c";
    src = fetchFromGitHub {
      owner = "graemedavidson";
      repo = "tmux-pane-focus";
      rev = "94adfd620bee88b9262fe28df6b07a23e82f3a5c";
      fetchSubmodules = false;
      sha256 = "sha256-Aur7OkJ8De6BDtSJHSfO1LLpbCfjWsxXi8jh5HNlUbo=";
    };
    date = "2024-03-05";
  };
  tmux-power-zoom = {
    pname = "tmux-power-zoom";
    version = "30eb97c090ff07c8e957b2e761f25931c1d49133";
    src = fetchFromGitHub {
      owner = "jaclu";
      repo = "tmux-power-zoom";
      rev = "30eb97c090ff07c8e957b2e761f25931c1d49133";
      fetchSubmodules = false;
      sha256 = "sha256-FMzdN+xEejjZfmQ65q7sK9sRbSoK/bZYtcaEPgeDGBc=";
    };
    date = "2024-10-14";
  };
  tmux-tea = {
    pname = "tmux-tea";
    version = "345af747c36e94344cbb360310f1d746f1517b6a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-tea";
      rev = "345af747c36e94344cbb360310f1d746f1517b6a";
      fetchSubmodules = false;
      sha256 = "sha256-CgPn+VZmaMm8lxJlgzQRLdhwHM/XA+KSIr/qwQdf5bs=";
    };
    date = "2024-09-10";
  };
  tmux-tome = {
    pname = "tmux-tome";
    version = "4fa1f007007fee4f5d1e81339c38f69c70c70104";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "tome";
      rev = "4fa1f007007fee4f5d1e81339c38f69c70c70104";
      fetchSubmodules = false;
      sha256 = "sha256-y1zcfXwaMpORAcSNtwskJwx1DpIJu4XE81m4utBcusY=";
    };
    date = "2024-10-12";
  };
  tmux-transient-status = {
    pname = "tmux-transient-status";
    version = "c3fcd5180999a7afc075d2dd37d37d1b1b82f7e8";
    src = fetchFromGitHub {
      owner = "TheSast";
      repo = "tmux-transient-status";
      rev = "c3fcd5180999a7afc075d2dd37d37d1b1b82f7e8";
      fetchSubmodules = false;
      sha256 = "sha256-fOIn8hVVBDFVLwzmPZP+Bf3ccxy/hsAnKIXYD9yv3BE=";
    };
    date = "2023-12-26";
  };
  tmux-which-key = {
    pname = "tmux-which-key";
    version = "b7283f4ccece66dd4a49fd6badd55b43262c6ae6";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-which-key";
      rev = "b7283f4ccece66dd4a49fd6badd55b43262c6ae6";
      fetchSubmodules = false;
      sha256 = "sha256-zJlQ+3945xrfI5BpywpB5J79m5j2y3vtLUHsZgUaCJ0=";
    };
    date = "2024-09-09";
  };
  "tmux.fish" = {
    pname = "tmux.fish";
    version = "7e820cb45c6784df71cbaf6dca0d17e39a9d59d4";
    src = fetchFromGitHub {
      owner = "budimanjojo";
      repo = "tmux.fish";
      rev = "7e820cb45c6784df71cbaf6dca0d17e39a9d59d4";
      fetchSubmodules = false;
      sha256 = "sha256-ynhEhrdXQfE1dcYsSk2M2BFScNXWPh3aws0U7eDFtv4=";
    };
    date = "2024-10-14";
  };
  tmux2k = {
    pname = "tmux2k";
    version = "74c6c25a28111345cb9af1fd85e4c0b84236b242";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "tmux2k";
      rev = "74c6c25a28111345cb9af1fd85e4c0b84236b242";
      fetchSubmodules = false;
      sha256 = "sha256-KWoZkob1anemfv2mNJoIzlgAYnzo4HN8cU+Szm7DfjI=";
    };
    date = "2024-07-29";
  };
  to-fish = {
    pname = "to-fish";
    version = "52b151cfe67c00cb64d80ccc6dae398f20364938";
    src = fetchFromGitHub {
      owner = "joehillen";
      repo = "to-fish";
      rev = "52b151cfe67c00cb64d80ccc6dae398f20364938";
      fetchSubmodules = false;
      sha256 = "sha256-DfDsU/qY2XdYlkLISIOv02ggHfKEpb+YompNWWjs5/A=";
    };
    date = "2023-04-24";
  };
  "todo-comments.fish" = {
    pname = "todo-comments.fish";
    version = "fb818507c2b95e498495fb73206eb101566d71ee";
    src = fetchFromGitHub {
      owner = "kpbaks";
      repo = "todo-comments.fish";
      rev = "fb818507c2b95e498495fb73206eb101566d71ee";
      fetchSubmodules = false;
      sha256 = "sha256-x6B1qm1sEODBus6Dd30iifcOMj/q+8DA3pKzKQ7zzlc=";
    };
    date = "2024-02-11";
  };
  toolong = {
    pname = "toolong";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "Textualize";
      repo = "toolong";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-Zd6j1BIrsLJqptg7BXb67qY3DaeHRHieWJoYYCDHaoc=";
    };
  };
  toru = {
    pname = "toru";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "sweetbbak";
      repo = "toru";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-rfnZvo1O46EW794T0/JaV9Wb8JxnTrbo/aD7EgeHcFc=";
    };
  };
  tp = {
    pname = "tp";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "minefuto";
      repo = "tp";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-e/G0cN0HKzpgBRajztp/DucgO0JWW/jqi/omvLWsVyQ=";
    };
  };
  treegen = {
    pname = "treegen";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "bilbilak";
      repo = "treegen";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-z6CHr89fC9UVQgPmugOctB82XQ8yP6K5Ap2qsMLSnyk=";
    };
  };
  tuime = {
    pname = "tuime";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "nate-sys";
      repo = "tuime";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-9CGktRXx7IZ0yv/U78SWSifJ6YBIiV8cf5Dq60PPCcQ=";
    };
  };
  vim-auto-save = {
    pname = "vim-auto-save";
    version = "6697e84b25f6a56c36d0c5ae9004b8b9247662ea";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-auto-save";
      rev = "6697e84b25f6a56c36d0c5ae9004b8b9247662ea";
      fetchSubmodules = false;
      sha256 = "sha256-hP3s7iIfGjLMYF6lqnL6ORGqmPfM0d2BCdW4OSqg4ac=";
    };
    date = "2024-07-15";
  };
  vim-cycle = {
    pname = "vim-cycle";
    version = "a327a47e16cbc7f83a1427050c5878b165a53132";
    src = fetchFromGitHub {
      owner = "zef";
      repo = "vim-cycle";
      rev = "a327a47e16cbc7f83a1427050c5878b165a53132";
      fetchSubmodules = false;
      sha256 = "sha256-pSpqt5JUG26G0T1849z1lcFK4tpdJWPTgODPK5nW72M=";
    };
    date = "2022-02-17";
  };
  vim-floaterm = {
    pname = "vim-floaterm";
    version = "4e28c8dd0271e10a5f55142fb6fe9b1599ee6160";
    src = fetchFromGitHub {
      owner = "voldikss";
      repo = "vim-floaterm";
      rev = "4e28c8dd0271e10a5f55142fb6fe9b1599ee6160";
      fetchSubmodules = false;
      sha256 = "sha256-wIgcBcdxJsT+qrsC5Boj6hp0xpp5gFeQFhK7yyC5a1o=";
    };
    date = "2024-04-08";
  };
  vim-github-link = {
    pname = "vim-github-link";
    version = "0612c180d699c5d298e5181befa1830980e8e083";
    src = fetchFromGitHub {
      owner = "knsh14";
      repo = "vim-github-link";
      rev = "0612c180d699c5d298e5181befa1830980e8e083";
      fetchSubmodules = false;
      sha256 = "sha256-C0XU351KCm/Og0I7jl5PH+yOydOJ91WdPTcA6068GgI=";
    };
    date = "2024-01-04";
  };
  vim-mkdir = {
    pname = "vim-mkdir";
    version = "f0ba7a7dc190a0cedf1d827958c99f3718109cf0";
    src = fetchFromGitHub {
      owner = "pbrisbin";
      repo = "vim-mkdir";
      rev = "f0ba7a7dc190a0cedf1d827958c99f3718109cf0";
      fetchSubmodules = false;
      sha256 = "sha256-3GZFp6Q6ZM48b4Qxy3BpsMGI9K9vmIsvZ53R6niw4k4=";
    };
    date = "2019-04-29";
  };
  vim-silicon = {
    pname = "vim-silicon";
    version = "4a93122ae2139a12e2a56f064d086c05160b6835";
    src = fetchFromGitHub {
      owner = "segeljakt";
      repo = "vim-silicon";
      rev = "4a93122ae2139a12e2a56f064d086c05160b6835";
      fetchSubmodules = false;
      sha256 = "sha256-8pCHtApD/xXav2UBVOVhkaHg3YS4aNCZ73mog04bYuA=";
    };
    date = "2020-12-01";
  };
  vim-snipewin = {
    pname = "vim-snipewin";
    version = "9616fd4564d61c78947e3dda53ef9ac61cce032c";
    src = fetchFromGitHub {
      owner = "4513ECHO";
      repo = "vim-snipewin";
      rev = "9616fd4564d61c78947e3dda53ef9ac61cce032c";
      fetchSubmodules = false;
      sha256 = "sha256-dUOP8/NBwAhie0DUdkjyCUuoQ9q1UD1PJm02zzz9BNg=";
    };
    date = "2024-03-28";
  };
  vim-templates = {
    pname = "vim-templates";
    version = "c4ce1903fc458688bc421f0cb4572af8a8977cdb";
    src = fetchFromGitHub {
      owner = "tibabit";
      repo = "vim-templates";
      rev = "c4ce1903fc458688bc421f0cb4572af8a8977cdb";
      fetchSubmodules = false;
      sha256 = "sha256-p0TEJr/2TBoOk48xgtrqwnAtQlYRkz/NEKcadLAJoCA=";
    };
    date = "2024-04-26";
  };
  vim-tome = {
    pname = "vim-tome";
    version = "4fa1f007007fee4f5d1e81339c38f69c70c70104";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "tome";
      rev = "4fa1f007007fee4f5d1e81339c38f69c70c70104";
      fetchSubmodules = false;
      sha256 = "sha256-y1zcfXwaMpORAcSNtwskJwx1DpIJu4XE81m4utBcusY=";
    };
    date = "2024-10-12";
  };
  vim-toop = {
    pname = "vim-toop";
    version = "836c043756b57770068186886b72cbb2fef0d0eb";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-toop";
      rev = "836c043756b57770068186886b72cbb2fef0d0eb";
      fetchSubmodules = false;
      sha256 = "sha256-+z/4uAIUMqaoXxzqF9qVZsPIWh04zkfybZT+opeJOXg=";
    };
    date = "2024-10-16";
  };
  vim-visual-star-search = {
    pname = "vim-visual-star-search";
    version = "3ea07a973a8f3cb2b714c50ac0adca35da157631";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-visual-star-search";
      rev = "3ea07a973a8f3cb2b714c50ac0adca35da157631";
      fetchSubmodules = false;
      sha256 = "sha256-hiL9DuvQl4wUSZWCLJjGZYWLzIRXqbVCtZ1GLJTKFp4=";
    };
    date = "2024-07-16";
  };
  vim-workspace = {
    pname = "vim-workspace";
    version = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
    src = fetchFromGitHub {
      owner = "thaerkh";
      repo = "vim-workspace";
      rev = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
      fetchSubmodules = false;
      sha256 = "sha256-2Brx098dk5THiieBiW71FG9mUUwS1CSY9mpOPWA/Tq4=";
    };
    date = "2023-05-28";
  };
  vim-zoom = {
    pname = "vim-zoom";
    version = "65145acd49c62e042502e6f9a5b9b468006c768f";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-zoom";
      rev = "65145acd49c62e042502e6f9a5b9b468006c768f";
      fetchSubmodules = false;
      sha256 = "sha256-mTcqxP9mr9P14d7fCUWhIY7Zu4ehjwLJbjMrBsNBUHc=";
    };
    date = "2024-07-17";
  };
  vimsuggest = {
    pname = "vimsuggest";
    version = "8ab1d69c387c9f088103d349e92240e6f934adb1";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "vimsuggest";
      rev = "8ab1d69c387c9f088103d349e92240e6f934adb1";
      fetchSubmodules = false;
      sha256 = "sha256-BbGkPtqhNHBadwwyNGbCNlcv52hxn/oMAA0oc1jy6bk=";
    };
    date = "2024-10-19";
  };
  visual-split-vim = {
    pname = "visual-split-vim";
    version = "423a25911b3e8da04a28d29f205e1059a06e6afa";
    src = fetchFromGitHub {
      owner = "wellle";
      repo = "visual-split.vim";
      rev = "423a25911b3e8da04a28d29f205e1059a06e6afa";
      fetchSubmodules = false;
      sha256 = "sha256-v0j6AExrOJIgde/Aphr7lvonZptMwYQLCB6E+2YsiVg=";
    };
    date = "2017-01-29";
  };
  vl = {
    pname = "vl";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "ellisonleao";
      repo = "vl";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-zmSwlZwbPNafe2PyvFHMeQuJNJvs/c3zsMfVagcVXlU=";
    };
  };
  vlime = {
    pname = "vlime";
    version = "f57518bf6ac1b6c5e10db6a9259016b84ff81d8b";
    src = fetchFromGitHub {
      owner = "vlime";
      repo = "vlime";
      rev = "f57518bf6ac1b6c5e10db6a9259016b84ff81d8b";
      fetchSubmodules = false;
      sha256 = "sha256-034h9L9k+X3b+Z1Kt6HGiteYbHajoo8wu5zgh7RIjv8=";
    };
    date = "2023-10-08";
  };
  "web-search.fish" = {
    pname = "web-search.fish";
    version = "29d3027685cdc7f8ed857e3888733c6d5b5458fb";
    src = fetchFromGitHub {
      owner = "veirt";
      repo = "web-search.fish";
      rev = "29d3027685cdc7f8ed857e3888733c6d5b5458fb";
      fetchSubmodules = false;
      sha256 = "sha256-bGgdO3jS+kYaTQBhfw9bGke1S6egg9S4fmEe0buf684=";
    };
    date = "2024-10-14";
  };
  whitespace-format = {
    pname = "whitespace-format";
    version = "0.0.2";
    src = fetchFromGitHub {
      owner = "DavidPal";
      repo = "whitespace-format";
      rev = "0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-UscDx0cQ7YqZc6k42ww9Pi9g5nxJCRr+fcETneG0zHc=";
    };
  };
  wiper = {
    pname = "wiper";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "ikebastuz";
      repo = "wiper";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-IheSAPk1l6wJ2v4RLPIPvY/5XMfh+vJLyQ/Lc7RrCJQ=";
    };
  };
  wush = {
    pname = "wush";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "coder";
      repo = "wush";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-2mFe1p15HRyy86pw5LoBtiW9lKrw/N9V81/jkiT4jo4=";
    };
  };
  ytui = {
    pname = "ytui";
    version = "v0.1.8";
    src = fetchFromGitHub {
      owner = "Banh-Canh";
      repo = "ytui";
      rev = "v0.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-+sfkqz2LZCImWQrt3p4jx/i3jj7yJuH8F3fQ9raE9D4=";
    };
  };
  zfind = {
    pname = "zfind";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "zfind";
      rev = "v0.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-sRZAsmh193K5HX7oC1UdCQccNpSc5QHtec+UpvpntKU=";
    };
  };
}
