# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  advance-touch = {
    pname = "advance-touch";
    version = "1.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/advance-touch/advance-touch-1.0.2.tar.gz";
      sha256 = "sha256-I4wF4PuhDUnM7YluERJzMWysUODtfUTPOo4nvNSGZ8U=";
    };
  };
  ahoy = {
    pname = "ahoy";
    version = "v2.3.0";
    src = fetchFromGitHub {
      owner = "ahoy-cli";
      repo = "ahoy";
      rev = "v2.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-PLKogNPA3+7wsO02He8xJXx3ki4pRwpVwo+6ELiKuCY=";
    };
  };
  akuse = {
    pname = "akuse";
    version = "1.9.0";
    src = fetchurl {
      url = "https://github.com/akuse-app/akuse/releases/download/1.9.0/linux-akuse-1.9.0.AppImage";
      sha256 = "sha256-tBM16s5XTKo06xICf2iKNDcvqLkXYzD+/7qZEIjdiOg=";
    };
  };
  aniweather = {
    pname = "aniweather";
    version = "18cc76d9f4c0ee1276d8314d48ffaa0b4640dbf9";
    src = fetchFromGitHub {
      owner = "kaishira";
      repo = "aniweather";
      rev = "18cc76d9f4c0ee1276d8314d48ffaa0b4640dbf9";
      fetchSubmodules = false;
      sha256 = "sha256-rtFq1a1jmEMuEfICuBRZc23aRxj1M54swsWa3P2Oh/c=";
    };
    date = "2025-01-08";
  };
  antifennel = {
    pname = "antifennel";
    version = "a135f016414517ecb624bad26b39ed56d256beaa";
    src = fetchgit {
      url = "https://git.sr.ht/~technomancy/antifennel";
      rev = "a135f016414517ecb624bad26b39ed56d256beaa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XynKKDyykyPM4z2ZLp9Oy8KFlEZG2iHXKMkajaS/DaE=";
    };
    date = "2024-09-25";
  };
  argparse = {
    pname = "argparse";
    version = "1.4.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/argparse/argparse-1.4.0.tar.gz";
      sha256 = "sha256-YrCJpVvh2JSc0rx+DfC9254Cj678jDIDjMhIYq791uQ=";
    };
  };
  "aria2.conf" = {
    pname = "aria2.conf";
    version = "02b9d95ea155e66f7e3c4340cd22717f8bc7401c";
    src = fetchFromGitHub {
      owner = "P3TERX";
      repo = "aria2.conf";
      rev = "02b9d95ea155e66f7e3c4340cd22717f8bc7401c";
      fetchSubmodules = false;
      sha256 = "sha256-O7g/oGgANgoChKACAKzLIOOUbacWpHCEsH533eJwePo=";
    };
    date = "2024-02-28";
  };
  autocrop = {
    pname = "autocrop";
    version = "2afe00ed87fb10a6d368d0d4140307dc99b1a545";
    src = fetchFromGitHub {
      owner = "mandykoh";
      repo = "autocrop";
      rev = "2afe00ed87fb10a6d368d0d4140307dc99b1a545";
      fetchSubmodules = false;
      sha256 = "sha256-oxvu0P0LmusFQ5qX557pgyiq+eslWwfCaoEAkxJnqOA=";
    };
    date = "2021-06-03";
  };
  "autopair.fish" = {
    pname = "autopair.fish";
    version = "ec7ccf41eb945657a829338e85c88ad3353f961a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "autopair.fish";
      rev = "ec7ccf41eb945657a829338e85c88ad3353f961a";
      fetchSubmodules = false;
      sha256 = "sha256-hM2J82NHe5LPSHZ+yYHZNWAjif0vbwerloHIvTUT+tQ=";
    };
    date = "2024-07-08";
  };
  av = {
    pname = "av";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "aviator-co";
      repo = "av";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-2jBbuzMLnQVyd+Ix+laqoH37knMbhyUcGH/HlY5fwZU=";
    };
  };
  awesome-freedesktop = {
    pname = "awesome-freedesktop";
    version = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
    src = fetchFromGitHub {
      owner = "lcpz";
      repo = "awesome-freedesktop";
      rev = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
      fetchSubmodules = false;
      sha256 = "sha256-lQstCcTPUYUt5hzAJIyQ16crPngeOnUla7I4QiG6gEs=";
    };
    date = "2022-06-23";
  };
  baca = {
    pname = "baca";
    version = "v0.1.17";
    src = fetchFromGitHub {
      owner = "wustho";
      repo = "baca";
      rev = "v0.1.17";
      fetchSubmodules = false;
      sha256 = "sha256-uiMzXqA52atees5tHC5Vqk3ALojkJZ8ouivo+omBnlM=";
    };
  };
  bafi = {
    pname = "bafi";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "mmalcek";
      repo = "bafi";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-mYfnHb6Gin2e+Zjvo87ZzTp1/mnDG42UDl99zncB3O0=";
    };
  };
  blendr = {
    pname = "blendr";
    version = "v1.3.3";
    src = fetchFromGitHub {
      owner = "dmtrKovalenko";
      repo = "blendr";
      rev = "v1.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-6QRI1MQnoppzlVfRV/bfqfTnBjC0/haFm52Ez9nltzw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./blendr-v1.3.3/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  bling = {
    pname = "bling";
    version = "bcfb671248cf9ff636b7fd7d7120d8ed9deaa395";
    src = fetchFromGitHub {
      owner = "BlingCorp";
      repo = "bling";
      rev = "bcfb671248cf9ff636b7fd7d7120d8ed9deaa395";
      fetchSubmodules = false;
      sha256 = "sha256-rhhUsXQ3awjFiEHEG0axilSCWS6pR+w74K/pIfEUc5w=";
    };
    date = "2024-12-17";
  };
  boilr = {
    pname = "boilr";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "tmrts";
      repo = "boilr";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-ITUr1YUgqfrKAY6QEqxzdl3U7IjxYidbKT2eR1qEsPU=";
    };
  };
  bt = {
    pname = "bt";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "LeperGnome";
      repo = "bt";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-6hNdAmAflPcky1QxQvZCo+ffprRuIn2NPZYlS4wurww=";
    };
  };
  c = {
    pname = "c";
    version = "7cdc09e69d2f7fc49f70c80c565aa09b19e666db";
    src = fetchFromGitHub {
      owner = "ryanmjacobs";
      repo = "c";
      rev = "7cdc09e69d2f7fc49f70c80c565aa09b19e666db";
      fetchSubmodules = false;
      sha256 = "sha256-dOFM9wQzoEsuBwWb/FfxGDW07oyRXyGRH7lpscoSgUY=";
    };
    date = "2023-11-24";
  };
  cache = {
    pname = "cache";
    version = "0.2.0";
    src = fetchFromGitHub {
      owner = "Hejsil";
      repo = "cache";
      rev = "0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-9SvKw096yvLG4eYnNfIgHpgc5VceXqKkALSEBVuqfi0=";
    };
  };
  cat_win = {
    pname = "cat_win";
    version = "v1.10.2";
    src = fetchFromGitHub {
      owner = "SilenZcience";
      repo = "cat_win";
      rev = "v1.10.2";
      fetchSubmodules = false;
      sha256 = "sha256-AJVZdjkyNhl3ZUo2pl8zqlV8A4Cp6xLeL8dZTdfnU/Y=";
    };
  };
  cdo = {
    pname = "cdo";
    version = "9e438f4794a1bb366fea214d4b006c087c9b5e63";
    src = fetchFromGitHub {
      owner = "dotboris";
      repo = "cdo";
      rev = "9e438f4794a1bb366fea214d4b006c087c9b5e63";
      fetchSubmodules = false;
      sha256 = "sha256-TrTahk+rnWtvWewlMS2y1ybTu5JSUhj0k4rbGW7I1kA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cdo-9e438f4794a1bb366fea214d4b006c087c9b5e63/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-01-16";
  };
  chezmoi-vim = {
    pname = "chezmoi-vim";
    version = "abf37336437867cbd99ce2f8849b717415391cc3";
    src = fetchFromGitHub {
      owner = "alker0";
      repo = "chezmoi.vim";
      rev = "abf37336437867cbd99ce2f8849b717415391cc3";
      fetchSubmodules = false;
      sha256 = "sha256-S1/myC1dEydi1F9a6XV0lJW3S/wWQe+A2ZXPo8GbtQo=";
    };
    date = "2024-07-26";
  };
  cidr = {
    pname = "cidr";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "bschaatsbergen";
      repo = "cidr";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-8Tf7He7pY5A5UqpQ9lwJTW8DC4qBu0AEuGOXHpYo6bQ=";
    };
  };
  clashctl = {
    pname = "clashctl";
    version = "0.3.3";
    src = fetchFromGitHub {
      owner = "George-Miao";
      repo = "clashctl";
      rev = "0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-7XVMtl6yFxT9fy205sZL8eJ711NXdmYIMFVBbF0RoPc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./clashctl-0.3.3/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  classifier = {
    pname = "classifier";
    version = "09e958baeedeb6eed0fb1e048ed820888c5dbb84";
    src = fetchFromGitHub {
      owner = "bhrigu123";
      repo = "classifier";
      rev = "09e958baeedeb6eed0fb1e048ed820888c5dbb84";
      fetchSubmodules = false;
      sha256 = "sha256-nj+PlZpz8M2lvxsEa8RulWEb+aGN7ez7uF+iM9IhGKQ=";
    };
    date = "2017-05-23";
  };
  climage = {
    pname = "climage";
    version = "0.2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/c/climage/climage-0.2.2.tar.gz";
      sha256 = "sha256-5hFrL189MTrbCFZlfv5KbRGeIhjN7yPCipk9lLhxq44=";
    };
  };
  cmdx = {
    pname = "cmdx";
    version = "v1.7.7";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "cmdx";
      rev = "v1.7.7";
      fetchSubmodules = false;
      sha256 = "sha256-Z3mGBsLisCoz3/e31e2OcshhVJu440Xz9xEUHJBTtUw=";
    };
  };
  code-radio-cli = {
    pname = "code-radio-cli";
    version = "v1.0.5";
    src = fetchFromGitHub {
      owner = "JasonWei512";
      repo = "code-radio-cli";
      rev = "v1.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-H2mnMWMJcFZIWHRz4QzM7ZwfbJ0N/ycu4g2W7187E3A=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./code-radio-cli-v1.0.5/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  comigo = {
    pname = "comigo";
    version = "v0.9.13";
    src = fetchFromGitHub {
      owner = "yumenaka";
      repo = "comigo";
      rev = "v0.9.13";
      fetchSubmodules = false;
      sha256 = "sha256-Ck8DZMcVQSMm6udYwMe9FxfxEmGmQWYO1y3yqyjnV2Y=";
    };
  };
  complate = {
    pname = "complate";
    version = "0.14.0";
    src = fetchFromGitHub {
      owner = "replicadse";
      repo = "complate";
      rev = "0.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-X/uFpfHz0DCj0KFR2IcV6vhSkP0sSX0MsEBDmw0nan0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./complate-0.14.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  compose2nix = {
    pname = "compose2nix";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "aksiksi";
      repo = "compose2nix";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-rFnnbRVVv/N5021Al3vmjFAui1cTp8NBZDBNQo8CsXM=";
    };
  };
  config-file-validator = {
    pname = "config-file-validator";
    version = "v1.8.0";
    src = fetchFromGitHub {
      owner = "Boeing";
      repo = "config-file-validator";
      rev = "v1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-vMORG3ieExTXOuFI8lVZzpY5ffN6qfuwsm1mVVjum4A=";
    };
  };
  convfmt = {
    pname = "convfmt";
    version = "0.1.7";
    src = fetchFromGitHub {
      owner = "oriontvv";
      repo = "convfmt";
      rev = "0.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-gQo4XUXRsCnG9TOV/LWZaLceM/PAl8knXMteNvzKoYA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./convfmt-0.1.7/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  corgi = {
    pname = "corgi";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "junyu-w";
      repo = "corgi";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-1qG11iuHrf3jg0aPqNU4ItT4rvYxXg5ZDDaJIMOWOUE=";
    };
  };
  "ctrl-z.fish" = {
    pname = "ctrl-z.fish";
    version = "82448a44c9ba8e2d8a5c7394184e977f5f76e0b8";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "ctrl-z.fish";
      rev = "82448a44c9ba8e2d8a5c7394184e977f5f76e0b8";
      fetchSubmodules = false;
      sha256 = "sha256-JXy5y0FXLvgdqgkwqGFkv2aqV40AHWRq9mq/EhsTEyo=";
    };
    date = "2024-10-20";
  };
  curd = {
    pname = "curd";
    version = "v1.0.8";
    src = fetchFromGitHub {
      owner = "Wraient";
      repo = "curd";
      rev = "v1.0.8";
      fetchSubmodules = false;
      sha256 = "sha256-CMD76W7uszu4iwd1G6ht7+zAVPRsDdyAtHnaUw6R5mM=";
    };
  };
  datadash = {
    pname = "datadash";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "keithknott26";
      repo = "datadash";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-WEB1MVG2aGvKnkMAgF7nxKHgA05VRJONoNdsBpXM2Wk=";
    };
  };
  debounce = {
    pname = "debounce";
    version = "v0.5.1";
    src = fetchFromGitHub {
      owner = "oalders";
      repo = "debounce";
      rev = "v0.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-pXHvl3cxWukCExuRbmiFMhm7Kp85SC1wY6u/FZ9WTTQ=";
    };
  };
  devdocs-vim = {
    pname = "devdocs-vim";
    version = "798cc7d26db27906526345af65d900887b9d4160";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "devdocs.vim";
      rev = "798cc7d26db27906526345af65d900887b9d4160";
      fetchSubmodules = false;
      sha256 = "sha256-k9tCrdru2tGdtJCU7edn/Er7bUUBpgYygxGUSO7RgH8=";
    };
    date = "2024-12-19";
  };
  dext = {
    pname = "dext";
    version = "03691dfc96c99a5dddc7171bae5d19739aac2b82";
    src = fetchFromGitHub {
      owner = "AfzGit";
      repo = "dext";
      rev = "03691dfc96c99a5dddc7171bae5d19739aac2b82";
      fetchSubmodules = false;
      sha256 = "sha256-xR6r+zAGDcmwBDPu/euni9qzYtugq8HxSfBoXuu7qnM=";
    };
    date = "2023-04-23";
  };
  dlorg = {
    pname = "dlorg";
    version = "d4966d6d1e4384e8f6c7f33b473a24cf6cdd0617";
    src = fetchFromGitHub {
      owner = "deepspeccode";
      repo = "dlorg";
      rev = "d4966d6d1e4384e8f6c7f33b473a24cf6cdd0617";
      fetchSubmodules = false;
      sha256 = "sha256-yu+m1HGFSex/S1ik47ee8tGCFjTDkgfHqMmVNW2lQgY=";
    };
    date = "2024-08-18";
  };
  dnspyre = {
    pname = "dnspyre";
    version = "v3.5.0";
    src = fetchFromGitHub {
      owner = "Tantalor93";
      repo = "dnspyre";
      rev = "v3.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-bcBVpCX7n0IpdLn5VqG+1yDiH5Yy8Kn9UGd8KVwDYhI=";
    };
  };
  docker-alist = {
    pname = "docker-alist";
    version = "v3.41.0";
    src = dockerTools.pullImage {
      imageName = "xhofe/alist-aria2";
      imageDigest = "sha256:573e8862f6893804fd4a98781e269459f0d69fa148ede371afd2bf58a2dda289";
      sha256 = "sha256-66iXxKv+XdMjCn1Oa3XhgNpOKaoy7NXCnEG7OwVz6RY=";
      finalImageTag = "v3.41.0";
    };
  };
  docker-flaresolverr = {
    pname = "docker-flaresolverr";
    version = "v3.3.21";
    src = dockerTools.pullImage {
      imageName = "flaresolverr/flaresolverr";
      imageDigest = "sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b";
      sha256 = "sha256-unGzkgDG5RvVPz+cHdNqizBjEf9FCHSMwi7PbRgjETI=";
      finalImageTag = "v3.3.21";
    };
  };
  docker-lancommander = {
    pname = "docker-lancommander";
    version = "v1.1.0";
    src = dockerTools.pullImage {
      imageName = "lancommander/lancommander";
      imageDigest = "sha256:fccb43221169b5097ced9b48a10c6617f0146d5bb701394815be3e7aff5af928";
      sha256 = "sha256-vXl4yIngvlHVFGcK3hR4N2YykUQe6YZA6OBcX8IbvYA=";
      finalImageTag = "v1.1.0";
    };
  };
  docker-qd = {
    pname = "docker-qd";
    version = "20250129";
    src = dockerTools.pullImage {
      imageName = "qdtoday/qd";
      imageDigest = "sha256:0d3605a7bb780049565e03f05e71a45c79f44ae8d3815dd2f77ce5eb4adda168";
      sha256 = "sha256-j60PPD8StZVrMJtAw8FEqU+mKic3v3dtxx4XrU6CpOY=";
      finalImageTag = "20250129";
    };
  };
  docker-subconverter = {
    pname = "docker-subconverter";
    version = "0.9.7";
    src = dockerTools.pullImage {
      imageName = "asdlokj1qpi23/subconverter";
      imageDigest = "sha256:cc93272ad39eee19769e2d950bc9a2d605cbb28b5777fc67b4ed645d5969ec05";
      sha256 = "sha256-zJAZCp5WjZyZBeE+t0U/7PdfE8Ca53UECU4iNNSR9MQ=";
      finalImageTag = "0.9.7";
    };
  };
  dps-ghosttext-vim = {
    pname = "dps-ghosttext-vim";
    version = "70eb098546c498342bba6d6568b60558d33d613c";
    src = fetchFromGitHub {
      owner = "gamoutatsumi";
      repo = "dps-ghosttext.vim";
      rev = "70eb098546c498342bba6d6568b60558d33d613c";
      fetchSubmodules = false;
      sha256 = "sha256-w34dragcm/7E7jz6ZQsPKSNCBNwgk3kbSzEM1IPzuc8=";
    };
    date = "2024-10-18";
  };
  dra = {
    pname = "dra";
    version = "0.8.0";
    src = fetchFromGitHub {
      owner = "devmatteini";
      repo = "dra";
      rev = "0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-TOPU88sN4QFeKzz6pSk+TmBjksLptD+IpJX/N/7St7s=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./dra-0.8.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  easyjump-vim = {
    pname = "easyjump-vim";
    version = "7be7e1b6e8000971d0f6ef9e8480f86094f56635";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "easyjump.vim";
      rev = "7be7e1b6e8000971d0f6ef9e8480f86094f56635";
      fetchSubmodules = false;
      sha256 = "sha256-SuvbOOp0G+V0X4G++HkiGO0SWaZvCMd7/Y8q9gWvUYE=";
    };
    date = "2024-06-06";
  };
  eg = {
    pname = "eg";
    version = "1.2.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/eg/eg-1.2.3.tar.gz";
      sha256 = "sha256-MfIhskcBqfxLA02Vk/CBhZ2UOxS/JrLpgZBQm2TiYis=";
    };
  };
  ehh = {
    pname = "ehh";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "lennardv2";
      repo = "ehh";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-mXDive5yHac2MdAsDrMsp0QzcrhnIS805yt7AkpXnwM=";
    };
  };
  eleventy = {
    pname = "eleventy";
    version = "v3.0.0";
    src = fetchFromGitHub {
      owner = "11ty";
      repo = "eleventy";
      rev = "v3.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-0xyVski+WTfTdYfNUBMKX4fnorGSsbi95WMR8ocSU2Q=";
    };
  };
  enhancd = {
    pname = "enhancd";
    version = "v2.5.1";
    src = fetchFromGitHub {
      owner = "babarot";
      repo = "enhancd";
      rev = "v2.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-kaintLXSfLH7zdLtcoZfVNobCJCap0S/Ldq85wd3krI=";
    };
  };
  envset = {
    pname = "envset";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "schpet";
      repo = "envset";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-QyC73f3PUzs50aRxDAknM//38Al8WYA1cTVaLwybhPc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./envset-v0.2.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  facad = {
    pname = "facad";
    version = "v2.18.0";
    src = fetchFromGitHub {
      owner = "yellow-footed-honeyguide";
      repo = "facad";
      rev = "v2.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-0Z8CDHLWAighRhcVZIlSQAWb9CpeMpmw9ASy9ACep4Q=";
    };
  };
  fast-anime = {
    pname = "fast-anime";
    version = "v2.8.7";
    src = fetchFromGitHub {
      owner = "Benex254";
      repo = "FastAnime";
      rev = "v2.8.7";
      fetchSubmodules = false;
      sha256 = "sha256-cYj26LdaY5+EhjHyvKwjUCZ5DiXpYHQSzlgzFVqaKtM=";
    };
  };
  fc-fish = {
    pname = "fc-fish";
    version = "9457a9c47391ff712696bbef0e4a109de2a653d1";
    src = fetchFromGitHub {
      owner = "lengyijun";
      repo = "fc-fish";
      rev = "9457a9c47391ff712696bbef0e4a109de2a653d1";
      fetchSubmodules = false;
      sha256 = "sha256-DQQofY5FPdy5kWctlKmi2SRTH7zL9ZpBdrdMx+iX+dA=";
    };
    date = "2023-04-07";
  };
  fetch = {
    pname = "fetch";
    version = "v0.4.6";
    src = fetchFromGitHub {
      owner = "gruntwork-io";
      repo = "fetch";
      rev = "v0.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-otHsP3Y8FZqB9omNYuM7gZfolqFiDwlXLEXeJB3pefI=";
    };
  };
  fgit = {
    pname = "fgit";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "fastgh";
      repo = "fgit";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-27GZp1qd0pJg9usIxj8wl1Dz+4ZC0273bb1tJ4Hhc9s=";
    };
  };
  fifc = {
    pname = "fifc";
    version = "a01650cd432becdc6e36feeff5e8d657bd7ee84a";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fifc";
      rev = "a01650cd432becdc6e36feeff5e8d657bd7ee84a";
      fetchSubmodules = false;
      sha256 = "sha256-Ynb0Yd5EMoz7tXwqF8NNKqCGbzTZn/CwLsZRQXIAVp4=";
    };
    date = "2024-12-04";
  };
  fingerpaint = {
    pname = "fingerpaint";
    version = "v1.2.7";
    src = fetchFromGitHub {
      owner = "Wazzaps";
      repo = "fingerpaint";
      rev = "v1.2.7";
      fetchSubmodules = false;
      sha256 = "sha256-BPpSAaWLmF0JkMijx7pI87tzO/rcjTryxdI2ekTavRY=";
    };
  };
  fish-abbreviation-tips = {
    pname = "fish-abbreviation-tips";
    version = "8ed76a62bb044ba4ad8e3e6832640178880df485";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fish-abbreviation-tips";
      rev = "8ed76a62bb044ba4ad8e3e6832640178880df485";
      fetchSubmodules = false;
      sha256 = "sha256-F1t81VliD+v6WEWqj1c1ehFBXzqLyumx5vV46s/FZRU=";
    };
    date = "2023-01-23";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "322e8bf03cb5c30215ce53d07f03c0584cd781b2";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "fish-bd";
      rev = "322e8bf03cb5c30215ce53d07f03c0584cd781b2";
      fetchSubmodules = false;
      sha256 = "sha256-mOJUdTWZKCtUaoGuL/dDb56eGEYtiRpkU38xIOJC4qs=";
    };
    date = "2024-11-20";
  };
  fish-color-scheme-switcher = {
    pname = "fish-color-scheme-switcher";
    version = "9f9720dbf06cd4690e6b78c3daa897ae05f792bb";
    src = fetchFromGitHub {
      owner = "h-matsuo";
      repo = "fish-color-scheme-switcher";
      rev = "9f9720dbf06cd4690e6b78c3daa897ae05f792bb";
      fetchSubmodules = false;
      sha256 = "sha256-9VOgPxCNfuyy9DlicaN6W2EQ6OQFq/z8oSx1l9RitP4=";
    };
    date = "2022-02-21";
  };
  fish-colored-man = {
    pname = "fish-colored-man";
    version = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-colored-man";
      rev = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
      fetchSubmodules = false;
      sha256 = "sha256-uoZ4eSFbZlsRfISIkJQp24qPUNqxeD0JbRb/gVdRYlA=";
    };
    date = "2021-07-16";
  };
  fish-f = {
    pname = "fish-f";
    version = "6099f3a4b5d148674106a264fffc84dd5a4dfe35";
    src = fetchFromGitHub {
      owner = "gokulsoumya";
      repo = "f";
      rev = "6099f3a4b5d148674106a264fffc84dd5a4dfe35";
      fetchSubmodules = false;
      sha256 = "sha256-NSp4TCWjsVboT0xI+5zbWx2xr+S4go4zbR6nyxbUz8g=";
    };
    date = "2021-05-09";
  };
  fish-gitnow = {
    pname = "fish-gitnow";
    version = "0cf3c89209305779e82d3b5cb956cf8b54025dd6";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "gitnow";
      rev = "0cf3c89209305779e82d3b5cb956cf8b54025dd6";
      fetchSubmodules = false;
      sha256 = "sha256-vNYUMzgBvPxHpeybhzBvyVL5RhM6qZlFtk3uZiiDvf8=";
    };
    date = "2024-10-12";
  };
  fish-ranger-cd = {
    pname = "fish-ranger-cd";
    version = "42d7e6cada419b681cdbf01723b1919968b7cae9";
    src = fetchFromGitHub {
      owner = "sei40kr";
      repo = "fish-ranger-cd";
      rev = "42d7e6cada419b681cdbf01723b1919968b7cae9";
      fetchSubmodules = false;
      sha256 = "sha256-Bs3chNFkCUNgfiDsg6wVMt071ZODDGFeqjxqh4X6KNA=";
    };
    date = "2018-11-04";
  };
  fishbang = {
    pname = "fishbang";
    version = "f8d2721ac5508dbda54a666ebf12f1492c478277";
    src = fetchFromGitHub {
      owner = "brewingweasel";
      repo = "fishbang";
      rev = "f8d2721ac5508dbda54a666ebf12f1492c478277";
      fetchSubmodules = false;
      sha256 = "sha256-VHtjt3Xobvs0DTXJ1mFU8i84EEsNQv3yqbhjs7c1mNE=";
    };
    date = "2025-01-09";
  };
  flatpak-compose = {
    pname = "flatpak-compose";
    version = "0.4.1";
    src = fetchFromGitHub {
      owner = "faan11";
      repo = "flatpak-compose";
      rev = "0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-lRjH9Kj8WuZdW5eQFmn5La3nmFznoQeRI4KrP64HhsE=";
    };
  };
  focus = {
    pname = "focus";
    version = "v1.4.3";
    src = fetchFromGitHub {
      owner = "ayoisaiah";
      repo = "focus";
      rev = "v1.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-p9gTFUYHdyOY2EFT/ZmBHT7dRNm64s/3ExUXG7bfQ70=";
    };
  };
  fortune-python = {
    pname = "fortune-python";
    version = "1.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/f/fortune-python/fortune-python-1.1.1.tar.gz";
      sha256 = "sha256-F0LrNesABYlUbxsWvM1XOhENhIyO3rZhbSYEymICkZc=";
    };
  };
  friendly-snippets = {
    pname = "friendly-snippets";
    version = "efff286dd74c22f731cdec26a70b46e5b203c619";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "efff286dd74c22f731cdec26a70b46e5b203c619";
      fetchSubmodules = false;
      sha256 = "sha256-I8SRZxnoNC6SOWW+scoA77Jwyxcb4eUczppLdyOiZe0=";
    };
    date = "2024-12-01";
  };
  fzf-help = {
    pname = "fzf-help";
    version = "v2.3.2";
    src = fetchFromGitHub {
      owner = "BartSte";
      repo = "fzf-help";
      rev = "v2.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-0URTNRDw6fKcpIvnKziIyk6TOjeFUYVfy+Yyh14oNt8=";
    };
  };
  fzf-kill = {
    pname = "fzf-kill";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "Zeioth";
      repo = "fzf-kill";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-Aa+jqcavFber+tAWUqPgV87sKKZS+5rGeJLS7RoYGLA=";
    };
  };
  game_2048_tui = {
    pname = "game_2048_tui";
    version = "v0.0.2";
    src = fetchFromGitHub {
      owner = "WanderHuang";
      repo = "game-2048-tui";
      rev = "v0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-/O548IEhGYSOSIG/xTGCi+P75poM5KY2AYW6lXRCtF0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./game_2048_tui-v0.0.2/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  gaze = {
    pname = "gaze";
    version = "v1.1.6";
    src = fetchFromGitHub {
      owner = "wtetsu";
      repo = "gaze";
      rev = "v1.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-5i61kaonTCVHCYwJ0C+bihxNTNNwyQ2XWSI85RMm2Hk=";
    };
  };
  geminicommit = {
    pname = "geminicommit";
    version = "v0.2.6";
    src = fetchFromGitHub {
      owner = "tfkhdyt";
      repo = "geminicommit";
      rev = "v0.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-7LZUfipJi6gR2zHSv9HoVvSSd+QWKnY0wn3US3vAifA=";
    };
  };
  geoip2fast = {
    pname = "geoip2fast";
    version = "1.2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/g/geoip2fast/geoip2fast-1.2.2.tar.gz";
      sha256 = "sha256-OIFXAM7f6xl9UbS4czsNT3lls23hUUfBJVJxJPi0XWs=";
    };
  };
  gg = {
    pname = "gg";
    version = "14e45a8e946eb7a04ebacc07e3a1f1f4235b1cd8";
    src = fetchFromGitHub {
      owner = "qw3rtman";
      repo = "gg";
      rev = "14e45a8e946eb7a04ebacc07e3a1f1f4235b1cd8";
      fetchSubmodules = false;
      sha256 = "sha256-+8WpnY9oBdDQ4fUj/xtsrx2w6LCfZIQjex+6BEk5qlk=";
    };
    date = "2022-12-27";
  };
  gh-branch = {
    pname = "gh-branch";
    version = "7ed0aff7601dc4162e0cac8835ecd73409d8a009";
    src = fetchFromGitHub {
      owner = "mislav";
      repo = "gh-branch";
      rev = "7ed0aff7601dc4162e0cac8835ecd73409d8a009";
      fetchSubmodules = false;
      sha256 = "sha256-yiRSXU/jLi067i+gBb3cEHTOuo+w3oEVsGL0NN6shl8=";
    };
    date = "2023-12-06";
  };
  gh-cp = {
    pname = "gh-cp";
    version = "58afdf5b5e1acfe71fce2390f6431003505ae0aa";
    src = fetchFromGitHub {
      owner = "mislav";
      repo = "gh-cp";
      rev = "58afdf5b5e1acfe71fce2390f6431003505ae0aa";
      fetchSubmodules = false;
      sha256 = "sha256-Ih3Wit0nnB8PrgbeZEuhTNVPCrwMWBmKMJSGmgLIrVY=";
    };
    date = "2021-11-08";
  };
  gh-poi = {
    pname = "gh-poi";
    version = "v0.13.0";
    src = fetchFromGitHub {
      owner = "seachicken";
      repo = "gh-poi";
      rev = "v0.13.0";
      fetchSubmodules = false;
      sha256 = "sha256-foUv6+QIfPlYwgTwxFvEgGeOw/mpC80+ntHo29LQbB8=";
    };
  };
  gh-screensaver = {
    pname = "gh-screensaver";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "vilmibm";
      repo = "gh-screensaver";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-MqwaqXGP4E+46vpgftZ9bttmMyENuojBnS6bWacmYLE=";
    };
  };
  gh-stars = {
    pname = "gh-stars";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "aymanbagabas";
      repo = "gh-stars";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-p1GLENa6UIXcasXbJtj5wpS2nMnJzT7V7k3pwfJOano=";
    };
  };
  gif-progress = {
    pname = "gif-progress";
    version = "release-fix-not-moving-progress-bar";
    src = fetchFromGitHub {
      owner = "nwtgck";
      repo = "gif-progress";
      rev = "release-fix-not-moving-progress-bar";
      fetchSubmodules = false;
      sha256 = "sha256-kNWTpvajuZZPSSZeJBP2N+z67OBPuYhaxydcETWDses=";
    };
  };
  git-cal = {
    pname = "git-cal";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "k4rthik";
      repo = "git-cal";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-fzzcxGre3YebvFrSRrul2L73mfQF/4ubsGVSPFzUSSM=";
    };
  };
  git-grab = {
    pname = "git-grab";
    version = "3.0.0";
    src = fetchFromGitHub {
      owner = "wezm";
      repo = "git-grab";
      rev = "3.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-MsJDfmWU6LyK7M0LjYQufIpKmtS4f2hgo4Yi/x1HsrU=";
    };
  };
  git-heatgrid = {
    pname = "git-heatgrid";
    version = "2263ce34d2929652e6cfe31fe076577dfcefd168";
    src = fetchFromGitHub {
      owner = "denshakhov";
      repo = "git-heatgrid";
      rev = "2263ce34d2929652e6cfe31fe076577dfcefd168";
      fetchSubmodules = false;
      sha256 = "sha256-nBiZfwiWmwM0a839NaDsCouJtL2d0HYHIZ+FFGrmzjM=";
    };
    date = "2024-05-13";
  };
  git-ink = {
    pname = "git-ink";
    version = "1.0.1";
    src = fetchFromGitHub {
      owner = "davidosomething";
      repo = "git-ink";
      rev = "1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-OiAajjMXyLezEXNxmHnwZZBP0lZEYmRGUkxh6xEoThw=";
    };
  };
  git-issue = {
    pname = "git-issue";
    version = "d056998566d30235072b97982756ff607e9ecce9";
    src = fetchFromGitHub {
      owner = "dspinellis";
      repo = "git-issue";
      rev = "d056998566d30235072b97982756ff607e9ecce9";
      fetchSubmodules = false;
      sha256 = "sha256-VYMIgJRcXKlhX05tfILA8dB8x3lcR6nX6vdls79cAgA=";
    };
    date = "2024-05-17";
  };
  git-lens-vim = {
    pname = "git-lens-vim";
    version = "6c22e05c3e43bbe6e2cdc02bbc2978886e50e27c";
    src = fetchFromGitHub {
      owner = "Eliot00";
      repo = "git-lens.vim";
      rev = "6c22e05c3e43bbe6e2cdc02bbc2978886e50e27c";
      fetchSubmodules = false;
      sha256 = "sha256-YZdiYB1YJFv/oCJSC/Ld0QBDTp+mqItwIWURbbN9yCw=";
    };
    date = "2024-04-14";
  };
  git-messenger-vim = {
    pname = "git-messenger-vim";
    version = "edc603d4cda7894a743e383e16c638e206d03148";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "git-messenger.vim";
      rev = "edc603d4cda7894a743e383e16c638e206d03148";
      fetchSubmodules = false;
      sha256 = "sha256-SgivafrSdql6yG0Nj2+zo0dWE7x3YigzD6kJRrucPC0=";
    };
    date = "2024-09-05";
  };
  git-mux = {
    pname = "git-mux";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "benelan";
      repo = "git-mux";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-rqWLnp8OaNFaM7jfplfsnVotkBpDhCfIVOk8W83GjPM=";
    };
  };
  git-of-theseus = {
    pname = "git-of-theseus";
    version = "961bda027ffa9fcd8bbe99d5b8809cc0eaa86464";
    src = fetchFromGitHub {
      owner = "erikbern";
      repo = "git-of-theseus";
      rev = "961bda027ffa9fcd8bbe99d5b8809cc0eaa86464";
      fetchSubmodules = false;
      sha256 = "sha256-FZXLJbximJWrDyuRril6whlOYWppGLns3k8sDNRmOuI=";
    };
    date = "2023-11-25";
  };
  git-playback = {
    pname = "git-playback";
    version = "0d4a51993b8a1b58579964e883fd344f6b92763b";
    src = fetchFromGitHub {
      owner = "jianli";
      repo = "git-playback";
      rev = "0d4a51993b8a1b58579964e883fd344f6b92763b";
      fetchSubmodules = false;
      sha256 = "sha256-lHqr+4dFFbktTI1J4Qu3t3BmV6xA32H2o5yOgaJJcNs=";
    };
    date = "2016-03-22";
  };
  git-spend = {
    pname = "git-spend";
    version = "1.2.1";
    src = fetchFromGitHub {
      owner = "Goutte";
      repo = "git-spend";
      rev = "1.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-4bR5CVM1zTSdLiHyigYgmvpO1VDM6rteeBHuADXq2pk=";
    };
  };
  git-stats = {
    pname = "git-stats";
    version = "3.2.0";
    src = fetchFromGitHub {
      owner = "IonicaBizau";
      repo = "git-stats";
      rev = "3.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-LhsesKHPggV7asOcJCPS/o4O5jP4WVlSiDXIWlyj8Yc=";
    };
  };
  git-sumi = {
    pname = "git-sumi";
    version = "v0.0.9";
    src = fetchFromGitHub {
      owner = "welpo";
      repo = "git-sumi";
      rev = "v0.0.9";
      fetchSubmodules = false;
      sha256 = "sha256-ZSpQJeiGn6J8G/35PTW6pRzPhTRW1Op3gakx/yXB3Zc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./git-sumi-v0.0.9/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  git-toolbelt = {
    pname = "git-toolbelt";
    version = "v1.9.3";
    src = fetchFromGitHub {
      owner = "nvie";
      repo = "git-toolbelt";
      rev = "v1.9.3";
      fetchSubmodules = false;
      sha256 = "sha256-ANqv/iIDUyy2G4pKSw+2sutMEA0WhPN3OKfPTm5lwDU=";
    };
  };
  github-dlr = {
    pname = "github-dlr";
    version = "0.1.2";
    src = fetchFromGitHub {
      owner = "rocktimsaikia";
      repo = "github-dlr";
      rev = "0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-vXLrX3gWx1K77TA79dOxaC2U59ZWpS0PGQnUHIb+BxI=";
    };
  };
  gitty = {
    pname = "gitty";
    version = "v0.1.4";
    src = fetchFromGitHub {
      owner = "worlpaker";
      repo = "gitty";
      rev = "v0.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-fJIJHq/6ZvJa2uPvllqJhINzMFwGfrtNHmXZ/HmpZ5w=";
    };
  };
  gogitmoji = {
    pname = "gogitmoji";
    version = "v1.1.5";
    src = fetchFromGitHub {
      owner = "jamesdobson";
      repo = "gogitmoji";
      rev = "v1.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-mXJga9Y1ZA7htzCEyMIuyj2oMjyFOj/Z/2U/yzLfQPw=";
    };
  };
  goji = {
    pname = "goji";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "muandane";
      repo = "goji";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-By4BQN7ftja4VMdxaksbQqtUcgjaQhF0ORUWZspmho8=";
    };
  };
  goodls = {
    pname = "goodls";
    version = "v2.0.5";
    src = fetchFromGitHub {
      owner = "tanaikech";
      repo = "goodls";
      rev = "v2.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-SrDDRQvogsYtdp8El/NOeeTOg0RKqaR3m7dq4Lhqrps=";
    };
  };
  grip-grab = {
    pname = "grip-grab";
    version = "v0.5.5";
    src = fetchFromGitHub {
      owner = "alexpasmantier";
      repo = "grip-grab";
      rev = "v0.5.5";
      fetchSubmodules = false;
      sha256 = "sha256-T3tla6Gf9lUQ+F8D57glzmfsmuX5FV806zuKQxYt2lw=";
    };
  };
  gtm = {
    pname = "gtm";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "git-time-metric";
      repo = "gtm";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-O09wFBT45ExkIYVhnVVOAcHbB4SHeaA+SaDilA8qW3g=";
    };
  };
  gtm-vim-plugin = {
    pname = "gtm-vim-plugin";
    version = "ebd33f7d01a7ac9b2695f71b1136d6b89a0d5d44";
    src = fetchFromGitHub {
      owner = "git-time-metric";
      repo = "gtm-vim-plugin";
      rev = "ebd33f7d01a7ac9b2695f71b1136d6b89a0d5d44";
      fetchSubmodules = false;
      sha256 = "sha256-rAbcwJ6Frgj6s1lPP0iUVJn39w0vzCvg2ImOaQD2+2w=";
    };
    date = "2017-04-16";
  };
  gw = {
    pname = "gw";
    version = "v0.4.1";
    src = fetchFromGitHub {
      owner = "daniel7grant";
      repo = "gw";
      rev = "v0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-tyZEGGX9Vr1T/U6Gea3Ku1dbHu4s2RY3u+jacrxn0Zo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./gw-v0.4.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  hatsune-miku-windows-linux-cursors = {
    pname = "hatsune-miku-windows-linux-cursors";
    version = "1.2.6";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "1.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-OQjjOc9VnxJ7tWNmpHIMzNWX6WsavAOkgPwK1XAMwtE=";
    };
  };
  hexpatch = {
    pname = "hexpatch";
    version = "v1.9.5";
    src = fetchFromGitHub {
      owner = "Etto48";
      repo = "HexPatch";
      rev = "v1.9.5";
      fetchSubmodules = false;
      sha256 = "sha256-DRuknqj4E+G4ChN5CH5N4Zrl3btSo1HdqiRPfLC5YTE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./hexpatch-v1.9.5/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  hl = {
    pname = "hl";
    version = "v0.30.3";
    src = fetchFromGitHub {
      owner = "pamburus";
      repo = "hl";
      rev = "v0.30.3";
      fetchSubmodules = false;
      sha256 = "sha256-18FzXUvpMHu3EfECgcslhReinMM6Oa1qdTKbbqFiv1w=";
    };
  };
  hledger-fmt = {
    pname = "hledger-fmt";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "mondeja";
      repo = "hledger-fmt";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-qzjdTEsFfZyYMqWDy6QgLI3TiAMI1PQfBoEweIj6nkU=";
    };
  };
  hssp = {
    pname = "hssp";
    version = "a08b37f4faca8b4269531be375c046f9beede0a0";
    src = fetchFromGitHub {
      owner = "sterchelen";
      repo = "hssp";
      rev = "a08b37f4faca8b4269531be375c046f9beede0a0";
      fetchSubmodules = false;
      sha256 = "sha256-y6k2Jcx6NZKU4i7OghWPlqEW/gZkDJtw5Rhqx+7SRyU=";
    };
    date = "2023-02-09";
  };
  html-to-markdown = {
    pname = "html-to-markdown";
    version = "v2.2.2";
    src = fetchFromGitHub {
      owner = "JohannesKaufmann";
      repo = "html-to-markdown";
      rev = "v2.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-RiMQsWuPzmWJf5MpF+fhsitc2qKGkOYYpoLjWVIQtf8=";
    };
  };
  hypergrep = {
    pname = "hypergrep";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "p-ranav";
      repo = "hypergrep";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-kzM8MGic/bGGKr7CdCCFbmpVR4TA356lDFMDa+9U25Q=";
    };
  };
  images-upload-cli = {
    pname = "images-upload-cli";
    version = "v3.0.5";
    src = fetchFromGitHub {
      owner = "DeadNews";
      repo = "images-upload-cli";
      rev = "v3.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-iK1pB8MTCEXttZU9RdYeF2mmj4FwF5svbxLH5ekQ/cc=";
    };
  };
  is = {
    pname = "is";
    version = "v0.6.1";
    src = fetchFromGitHub {
      owner = "oalders";
      repo = "is";
      rev = "v0.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-DkCyymyAoo16ocfLgfdlFSaeadBcdP9QZSWSBQpwql0=";
    };
  };
  jalm = {
    pname = "jalm";
    version = "f1e79605af1b4852b2a5dbfcc4674a5c14fc551d";
    src = fetchFromGitHub {
      owner = "neelkarma";
      repo = "jalm";
      rev = "f1e79605af1b4852b2a5dbfcc4674a5c14fc551d";
      fetchSubmodules = false;
      sha256 = "sha256-xwB6IXQX4bch+j+VhWicEz4MIsdjld29q0CJZvAhulI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./jalm-f1e79605af1b4852b2a5dbfcc4674a5c14fc551d/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2022-10-08";
  };
  jerry = {
    pname = "jerry";
    version = "f997596fc14fed328968f3ab27c777d001830efd";
    src = fetchFromGitHub {
      owner = "justchokingaround";
      repo = "Jerry";
      rev = "f997596fc14fed328968f3ab27c777d001830efd";
      fetchSubmodules = false;
      sha256 = "sha256-IZ1+P7RrTO3NgKxZx62Cbjm7z/AWfz3MghnleHw98/4=";
    };
    date = "2024-12-04";
  };
  jj-fzf = {
    pname = "jj-fzf";
    version = "v0.25.0";
    src = fetchFromGitHub {
      owner = "tim-janik";
      repo = "jj-fzf";
      rev = "v0.25.0";
      fetchSubmodules = false;
      sha256 = "sha256-StF0TKXTgtglFDbNTAU1c7Vw+6m70Mz2RvFon3difsk=";
    };
  };
  kbgrep = {
    pname = "kbgrep";
    version = "v0.2.2";
    src = fetchFromGitHub {
      owner = "pcrockett";
      repo = "kbgrep";
      rev = "v0.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-5Pd0C1Dl/1lZ+FXbmu1nVV40HysXXLeVROtfRjqEuT4=";
    };
  };
  kdtree = {
    pname = "kdtree";
    version = "0.16";
    src = fetchurl {
      url = "https://pypi.org/packages/source/k/kdtree/kdtree-0.16.tar.gz";
      sha256 = "sha256-OG32x4FqBeD6uXTjA135RPme9otWFfSkFncTkeM9dTQ=";
    };
  };
  lain = {
    pname = "lain";
    version = "88f5a8abd2649b348ffec433a24a263b37f122c0";
    src = fetchFromGitHub {
      owner = "lcpz";
      repo = "lain";
      rev = "88f5a8abd2649b348ffec433a24a263b37f122c0";
      fetchSubmodules = false;
      sha256 = "sha256-MH/aiYfcO3lrcuNbnIu4QHqPq25LwzTprOhEJUJBJ7I=";
    };
    date = "2023-01-12";
  };
  lib-x = {
    pname = "lib-x";
    version = "bbcba99072d9164a0360e72fbdac79f9664c979d";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "lib-x";
      rev = "bbcba99072d9164a0360e72fbdac79f9664c979d";
      fetchSubmodules = false;
      sha256 = "sha256-aCVZiSG9XGeT3dkJr+B844aaxDCFf71QzRX/u8jj05M=";
    };
    date = "2024-11-15";
  };
  lisp-format = {
    pname = "lisp-format";
    version = "088c8f78ca41204b44f2636275517ac09a2de6a9";
    src = fetchFromGitHub {
      owner = "eschulte";
      repo = "lisp-format";
      rev = "088c8f78ca41204b44f2636275517ac09a2de6a9";
      fetchSubmodules = false;
      sha256 = "sha256-L2Wl+UWQSiJYvzctyXrMQNViZiZ6Q5vgek1PWkIaTn4=";
    };
    date = "2022-02-16";
  };
  lite-xl-vibe = {
    pname = "lite-xl-vibe";
    version = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
    src = fetchFromGitHub {
      owner = "eugenpt";
      repo = "lite-xl-vibe";
      rev = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
      fetchSubmodules = false;
      sha256 = "sha256-JSTYmfiy0BeBCVXxOLkXf9SaxPTWrsAam2ZQKn0hk4M=";
    };
    date = "2023-10-31";
  };
  lobster = {
    pname = "lobster";
    version = "v4.3.0";
    src = fetchFromGitHub {
      owner = "justchokingaround";
      repo = "Lobster";
      rev = "v4.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-ch91LYKs6MswTC08Xi8VcIxooWvDprGuIn0B2Yo3ufo=";
    };
  };
  lobtui = {
    pname = "lobtui";
    version = "v0.3";
    src = fetchFromGitHub {
      owner = "pythops";
      repo = "lobtui";
      rev = "v0.3";
      fetchSubmodules = false;
      sha256 = "sha256-Vc6fh0XbSYNCQWosP7cOfphJin6Z5AJdcfSNdd38cKs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./lobtui-v0.3/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  lookatme = {
    pname = "lookatme";
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "d0c-s4vage";
      repo = "lookatme";
      rev = "v2.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-mn28OLIlxk97aDow1dTBsMRxVTkCqVeiAtrlyh8zJTg=";
    };
  };
  lssh = {
    pname = "lssh";
    version = "v0.6.13";
    src = fetchFromGitHub {
      owner = "blacknon";
      repo = "lssh";
      rev = "v0.6.13";
      fetchSubmodules = false;
      sha256 = "sha256-0dxkFOXNaOmIjKuhmTsfQmS+Nf8QiM5txmI8p1XcqTQ=";
    };
  };
  machma = {
    pname = "machma";
    version = "9ab93d72e36fe2cbb15af37c914605212ac28642";
    src = fetchFromGitHub {
      owner = "fd0";
      repo = "machma";
      rev = "9ab93d72e36fe2cbb15af37c914605212ac28642";
      fetchSubmodules = false;
      sha256 = "sha256-VmyWAsWIe6dhLq7UEit389v3fnQqRwZYk5gY6gj6Q3M=";
    };
    date = "2021-01-02";
  };
  makedown = {
    pname = "makedown";
    version = "4418bd111b4f86d0e35038d45332153c263c2d06";
    src = fetchFromGitHub {
      owner = "tzador";
      repo = "makedown";
      rev = "4418bd111b4f86d0e35038d45332153c263c2d06";
      fetchSubmodules = false;
      sha256 = "sha256-6oZawRzQ/Q++ydqDZ2CfYyxLz9xQO8IdB/qR5JgmD8A=";
    };
    date = "2024-10-18";
  };
  manga-tui = {
    pname = "manga-tui";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "josueBarretogit";
      repo = "manga-tui";
      rev = "v0.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-kmJrr1Gi1z9v2gkFmvcCAtBST+AkofVJSxyvAFnUZKQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./manga-tui-v0.5.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  mdformat-config = {
    pname = "mdformat-config";
    version = "0.2.1";
    src = fetchFromGitHub {
      owner = "hukkin";
      repo = "mdformat-config";
      rev = "0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-v6xtU6qZMhUnWFcCJOm9CcmLe6nKxmV9qGDM8o8MPe4=";
    };
  };
  mdsf = {
    pname = "mdsf";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "hougesen";
      repo = "mdsf";
      rev = "v0.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-/aVP+JOnX19RNRBBorC5TFqMf46rRi5I698NmKFL1fg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./mdsf-v0.5.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  mdtt = {
    pname = "mdtt";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "szktkfm";
      repo = "mdtt";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-OFS/ZhXdvdmlpfCNutsvlhMv1krFlx4Xju8RSl3GS2s=";
    };
  };
  miniflux-sync = {
    pname = "miniflux-sync";
    version = "0.1.1";
    src = fetchFromGitHub {
      owner = "revett";
      repo = "miniflux-sync";
      rev = "0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-XQc6RJLGkGKSkTEjd9E7CIDvjA6LNQNor+ilNBQoUbM=";
    };
  };
  minimal-tmux-status = {
    pname = "minimal-tmux-status";
    version = "d7188c1aeb1c7dd03230982445b7360f5e230131";
    src = fetchFromGitHub {
      owner = "niksingh710";
      repo = "minimal-tmux-status";
      rev = "d7188c1aeb1c7dd03230982445b7360f5e230131";
      fetchSubmodules = false;
      sha256 = "sha256-JtbuSxWFR94HiUdQL9uIm2V/kwGz0gbVbqvYWmEncbc=";
    };
    date = "2024-11-04";
  };
  miru = {
    pname = "miru";
    version = "5.5.9";
    src = fetchurl {
      url = "https://github.com/ThaUnknown/miru/releases/download/v5.5.9/linux-Miru-5.5.9.AppImage";
      sha256 = "sha256-AhaGiZ/Vx9nJmIXrzZ1JMLqjWfQDyoKpzl55NT712Ro=";
    };
  };
  mosdns-cn = {
    pname = "mosdns-cn";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "IrineSistiana";
      repo = "mosdns-cn";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-l2jqy2rtiQTIHNVR9LoNhTszmhTd8g3JQedbZK9E6hM=";
    };
  };
  mpv-M-x = {
    pname = "mpv-M-x";
    version = "e691bcebad9a352d31c42d3f1c9cc00a43ee14ca";
    src = fetchFromGitHub {
      owner = "Seme4eg";
      repo = "mpv-scripts";
      rev = "e691bcebad9a352d31c42d3f1c9cc00a43ee14ca";
      fetchSubmodules = false;
      sha256 = "sha256-FJw8FTFYTW6qYGOnQchqKpdr2+VIyJufqcOmhLeMchQ=";
    };
    date = "2025-01-07";
  };
  mpv-autoloop = {
    pname = "mpv-autoloop";
    version = "a8920592a4dbda574b51ddc6c2000851a13549a5";
    src = fetchFromGitHub {
      owner = "zc62";
      repo = "mpv-scripts";
      rev = "a8920592a4dbda574b51ddc6c2000851a13549a5";
      fetchSubmodules = false;
      sha256 = "sha256-pot53UjIJjzehLGxku16dNG1DBwXuOZ7FXQtmnezhwY=";
    };
    date = "2020-08-28";
  };
  mpv-blur-edges = {
    pname = "mpv-blur-edges";
    version = "d0390c8e802c2e888ff4a2e1d5e4fb040f855b89";
    src = fetchFromGitHub {
      owner = "occivink";
      repo = "mpv-scripts";
      rev = "d0390c8e802c2e888ff4a2e1d5e4fb040f855b89";
      fetchSubmodules = false;
      sha256 = "sha256-pc2aaO7lZaoYMEXv5M0WI7PtmqgkNbdtNiLZZwVzppM=";
    };
    date = "2024-01-11";
  };
  mpv-btfs-stream = {
    pname = "mpv-btfs-stream";
    version = "47004fb3d176fe83c58220dd34264c720320522a";
    src = fetchFromGitHub {
      owner = "noctuid";
      repo = "mpv-btfs-stream";
      rev = "47004fb3d176fe83c58220dd34264c720320522a";
      fetchSubmodules = false;
      sha256 = "sha256-IAzbH4TrlKQtZEUqSSK/8z2ahY4d5Lb0XuiO2aZtkKo=";
    };
    date = "2021-07-16";
  };
  mpv-smartcopypaste_ii = {
    pname = "mpv-smartcopypaste_ii";
    version = "48d68283cea47ff8e904decc9003b3abc3e2123e";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "48d68283cea47ff8e904decc9003b3abc3e2123e";
      fetchSubmodules = false;
      sha256 = "sha256-95CAKjBRELX2f7oWSHFWJnI0mikAoxhfUphe9k51Qf4=";
    };
    date = "2023-11-25";
  };
  mpv-smartskip = {
    pname = "mpv-smartskip";
    version = "48d68283cea47ff8e904decc9003b3abc3e2123e";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "48d68283cea47ff8e904decc9003b3abc3e2123e";
      fetchSubmodules = false;
      sha256 = "sha256-95CAKjBRELX2f7oWSHFWJnI0mikAoxhfUphe9k51Qf4=";
    };
    date = "2023-11-25";
  };
  mpv-webtorrent-hook = {
    pname = "mpv-webtorrent-hook";
    version = "eb2da86b628c512184818b19307632fa71fe7fb9";
    src = fetchFromGitHub {
      owner = "noctuid";
      repo = "mpv-webtorrent-hook";
      rev = "eb2da86b628c512184818b19307632fa71fe7fb9";
      fetchSubmodules = false;
      sha256 = "sha256-udKOyX0/R47wXSmYndhhq38D94gksxZbhx50VjG1HhY=";
    };
  };
  neonmodem = {
    pname = "neonmodem";
    version = "v1.0.6";
    src = fetchFromGitHub {
      owner = "mrusme";
      repo = "neonmodem";
      rev = "v1.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-VLR6eicffA0IXVwEZMvgpm1kVmrLYVZOtq7MSy+vIw8=";
    };
  };
  nix-auto-follow = {
    pname = "nix-auto-follow";
    version = "21646a12a47769707d46be8ab7be5e22c4f3224a";
    src = fetchFromGitHub {
      owner = "fzakaria";
      repo = "nix-auto-follow";
      rev = "21646a12a47769707d46be8ab7be5e22c4f3224a";
      fetchSubmodules = false;
      sha256 = "sha256-UaTTuBs+3+jT360fyfHdjpa4MhSFoMz+D1kp0rr+FwM=";
    };
    date = "2025-01-07";
  };
  nrf-udev = {
    pname = "nrf-udev";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "NordicSemiconductor";
      repo = "nrf-udev";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-bEIAsz9ZwX6RTzhv5/waFZ5a3KlnwX4kQs29+475zN0=";
    };
  };
  numara = {
    pname = "numara";
    version = "5.7.5";
    src = fetchurl {
      url = "https://github.com/bornova/numara-calculator/releases/download/v5.7.5/Numara-5.7.5-x86_64.AppImage";
      sha256 = "sha256-70kc7uPINoSnO8vASiApnzyDOq+bXruOonO7xiRq68w=";
    };
  };
  org-export = {
    pname = "org-export";
    version = "64ac299c041877620c2cadba83ded44f46c4e124";
    src = fetchFromGitHub {
      owner = "nhoffman";
      repo = "org-export";
      rev = "64ac299c041877620c2cadba83ded44f46c4e124";
      fetchSubmodules = false;
      sha256 = "sha256-GIkkYary9R3mf9r9QW0fgmnutMlhIp7PhM9KX7kXiuQ=";
    };
    date = "2023-10-25";
  };
  otree = {
    pname = "otree";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "fioncat";
      repo = "otree";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-CYobQppNsTg53a/+jVL8kqzfNnTVwW7VTgT+amW+lns=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./otree-v0.3.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  paclear = {
    pname = "paclear";
    version = "v0.0.13";
    src = fetchFromGitHub {
      owner = "orangekame3";
      repo = "paclear";
      rev = "v0.0.13";
      fetchSubmodules = false;
      sha256 = "sha256-Q4uY5aEcQKKLxhBGzmLdOy/bLG0/hpFRkF10wA68Ic0=";
    };
  };
  pangu-vim = {
    pname = "pangu-vim";
    version = "b7210117695dca05d94de1ac2108401f8eff0a2d";
    src = fetchFromGitHub {
      owner = "hotoo";
      repo = "pangu.vim";
      rev = "b7210117695dca05d94de1ac2108401f8eff0a2d";
      fetchSubmodules = false;
      sha256 = "sha256-MvT/3keKv05ZetWnKRA9nD2AyJKoyeLV7rtPlCCl98Q=";
    };
    date = "2023-02-19";
  };
  parinfer-rust = {
    pname = "parinfer-rust";
    version = "a1ec39b047da610f0797328582e7da0ffcab050e";
    src = fetchFromGitHub {
      owner = "eraserhd";
      repo = "parinfer-rust";
      rev = "a1ec39b047da610f0797328582e7da0ffcab050e";
      fetchSubmodules = false;
      sha256 = "sha256-lj01B7avPqxPgA9V3FMFAjY+fIxLa+EjuDmz4wWVuAw=";
    };
    date = "2025-02-01";
  };
  pik = {
    pname = "pik";
    version = "fcb9d7eb7dfcb62d0c93e32dd462be1728c3096e";
    src = fetchFromGitHub {
      owner = "immanelg";
      repo = "pik";
      rev = "fcb9d7eb7dfcb62d0c93e32dd462be1728c3096e";
      fetchSubmodules = false;
      sha256 = "sha256-s13olb4J3f9DZpGqi3CRwx7Q7zWIe6PyLZmnBI+USnk=";
    };
    date = "2024-08-28";
  };
  play = {
    pname = "play";
    version = "v0.3.5";
    src = fetchFromGitHub {
      owner = "paololazzari";
      repo = "play";
      rev = "v0.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-31naTjYwCytytKXg9tQo2qx0hVoBwBwL7nVeoAV+/go=";
    };
  };
  pls = {
    pname = "pls";
    version = "f860b1c7b9fce9800538d5b54dfb0dcd93370604";
    src = fetchFromGitHub {
      owner = "codevogel";
      repo = "pls";
      rev = "f860b1c7b9fce9800538d5b54dfb0dcd93370604";
      fetchSubmodules = false;
      sha256 = "sha256-wCz91oV1njVVWb1cBEoElsPyTP9Vwkhs1LVD/FbYDeQ=";
    };
    date = "2024-11-18";
  };
  pmark = {
    pname = "pmark";
    version = "b35e8a8c52b1bb2f879753ee8871af2961e4afe1";
    src = fetchFromGitHub {
      owner = "purarue";
      repo = "pmark";
      rev = "b35e8a8c52b1bb2f879753ee8871af2961e4afe1";
      fetchSubmodules = false;
      sha256 = "sha256-XoqDBgvPMpy4c3/OBUZa2+jmxZ2SwLCXP2bWORRBuLk=";
    };
    date = "2024-11-11";
  };
  pnut = {
    pname = "pnut";
    version = "e2a3c773da0f7e90def8696b0b2e4c62651a74de";
    src = fetchFromGitHub {
      owner = "udem-dlteam";
      repo = "pnut";
      rev = "e2a3c773da0f7e90def8696b0b2e4c62651a74de";
      fetchSubmodules = false;
      sha256 = "sha256-Ly/eAgirH4b+dtuphlW/TfsrKPeckfgFxkydScO3lgc=";
    };
    date = "2025-02-04";
  };
  posting = {
    pname = "posting";
    version = "2.3.0";
    src = fetchFromGitHub {
      owner = "darrenburns";
      repo = "posting";
      rev = "2.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-lL85gJxFw8/e8Js+UCE9VxBMcmWRUkHh8Cq5wTC93KA=";
    };
  };
  powershell-beautifier = {
    pname = "powershell-beautifier";
    version = "V1.2.5";
    src = fetchFromGitHub {
      owner = "DTW-DanWard";
      repo = "PowerShell-Beautifier";
      rev = "V1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-N/Wz2TDgQFEW//QR5SwzFFJAiRx8+RoMS842m27mYjM=";
    };
  };
  proji = {
    pname = "proji";
    version = "v0.20.0";
    src = fetchFromGitHub {
      owner = "proji-rocks";
      repo = "proji";
      rev = "v0.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-6nclWKouYp6ENGK23DQ6Wq9gpIQQjXHyLSOxyKV1i8A=";
    };
  };
  pryrite = {
    pname = "pryrite";
    version = "0.10.20";
    src = fetchFromGitHub {
      owner = "1xyz";
      repo = "pryrite";
      rev = "0.10.20";
      fetchSubmodules = false;
      sha256 = "sha256-mhdS4Wnb0DseddrofyEQZed9VcbfQj0MpoXXOQY2Ct8=";
    };
  };
  pydantic = {
    pname = "pydantic";
    version = "2.10.6";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic/pydantic-2.10.6.tar.gz";
      sha256 = "sha256-yl2qgnzOM956Qr4UJUiwCWvwWn57Nlrr+l+O7scSgjY=";
    };
  };
  pydantic-core = {
    pname = "pydantic-core";
    version = "2.28.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic_core/pydantic_core-2.28.0.tar.gz";
      sha256 = "sha256-SuphUw+f3I8SikdywP286RWezqAyAcFv4uS6fr0RsXM=";
    };
  };
  pydantic-settings = {
    pname = "pydantic-settings";
    version = "2.7.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic_settings/pydantic_settings-2.7.1.tar.gz";
      sha256 = "sha256-EMnKrTXmS/s8L79woHjA4lzJJJl4LlIAdH+UKgZd7JM=";
    };
  };
  pyjokes = {
    pname = "pyjokes";
    version = "v0.6.0";
    src = fetchFromGitHub {
      owner = "pyjokes";
      repo = "pyjokes";
      rev = "v0.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-HJlzGI7OPjAeLvriWi2ieflP2LIKxRYRaPOG1hXn8qg=";
    };
  };
  pypipe = {
    pname = "pypipe";
    version = "v0.4.1";
    src = fetchFromGitHub {
      owner = "bugen";
      repo = "pypipe";
      rev = "v0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-QHQZbjrKU0lE89L/13ukjXqZ2I/8XR9Hz5/YjmiXQhk=";
    };
  };
  qman = {
    pname = "qman";
    version = "7ae948ca9783423df41394f4ee9f0ed044383efc";
    src = fetchFromGitHub {
      owner = "plp13";
      repo = "qman";
      rev = "7ae948ca9783423df41394f4ee9f0ed044383efc";
      fetchSubmodules = false;
      sha256 = "sha256-rpjswApQTJe5A4wOqR5erGjUmHQG9SIB/LdpkXWa3GE=";
    };
    date = "2025-02-04";
  };
  quartz = {
    pname = "quartz";
    version = "87e0bd6813cb9cc66b353bb286b4032f447620c2";
    src = fetchFromGitHub {
      owner = "vimpostor";
      repo = "quartz";
      rev = "87e0bd6813cb9cc66b353bb286b4032f447620c2";
      fetchSubmodules = false;
      sha256 = "sha256-1nZFWCuT8k9siQoIxo4lFzjiFfs3lx2f9bVZjtChdw0=";
    };
    date = "2024-12-20";
  };
  radio-go-go = {
    pname = "radio-go-go";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "matteo-pacini";
      repo = "RadioGoGo";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-vEZUBA+KeDHgqZvzrAN6ramZ5D4iqQdVU+qFOK/39co=";
    };
  };
  ranger-archives = {
    pname = "ranger-archives";
    version = "b4e136b24fdca7670e0c6105fb496e5df356ef25";
    src = fetchFromGitHub {
      owner = "maximtrp";
      repo = "ranger-archives";
      rev = "b4e136b24fdca7670e0c6105fb496e5df356ef25";
      fetchSubmodules = false;
      sha256 = "sha256-QJu5G2AYtwcaE355yhiG4wxGFMQvmBWvaPQGLsi5x9Q=";
    };
    date = "2024-04-18";
  };
  ranger-devicons2 = {
    pname = "ranger-devicons2";
    version = "94bdcc19218681debb252475fd9d11cfd274d9b1";
    src = fetchFromGitHub {
      owner = "cdump";
      repo = "ranger-devicons2";
      rev = "94bdcc19218681debb252475fd9d11cfd274d9b1";
      fetchSubmodules = false;
      sha256 = "sha256-aJCIoDfzmOnzMLlbOe+dy6129n5Dc4OrefhHnPsgI8k=";
    };
    date = "2024-11-06";
  };
  ranger-zoxide = {
    pname = "ranger-zoxide";
    version = "281828de060299f73fe0b02fcabf4f2f2bd78ab3";
    src = fetchFromGitHub {
      owner = "jchook";
      repo = "ranger-zoxide";
      rev = "281828de060299f73fe0b02fcabf4f2f2bd78ab3";
      fetchSubmodules = false;
      sha256 = "sha256-JEuyYSVa1NS3aftezEJx/k19lwwzf7XhqBCL0jH6VT4=";
    };
    date = "2024-02-08";
  };
  rat = {
    pname = "rat";
    version = "397b4d7faabc59c9da6ae1abbff877f8ae83fc4b";
    src = fetchFromGitHub {
      owner = "ericfreese";
      repo = "rat";
      rev = "397b4d7faabc59c9da6ae1abbff877f8ae83fc4b";
      fetchSubmodules = false;
      sha256 = "sha256-/DAK2lc/4Vh1+fJa6blUBdoWWrnftBy9lcR7xx48WQM=";
    };
    date = "2021-09-23";
  };
  reader = {
    pname = "reader";
    version = "v0.4.6";
    src = fetchFromGitHub {
      owner = "mrusme";
      repo = "reader";
      rev = "v0.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-Z0mDRL02wZfmPRVDTDV85MqI5Ztctqen7PmOSW5Ee48=";
    };
  };
  recoverpy = {
    pname = "recoverpy";
    version = "2.2.0";
    src = fetchFromGitHub {
      owner = "PabloLec";
      repo = "RecoverPy";
      rev = "2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-VLZNXgn53x5t1JUH8W9Gj9IrAXrXac8OOsNaFkIbI+4=";
    };
  };
  render = {
    pname = "render";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "VirtusLab";
      repo = "render";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-BA9kwNWKH1JzVDi+gWkEN19VoTZnuLyGATAzOVtnIXs=";
    };
  };
  repoblame = {
    pname = "repoblame";
    version = "20ca80088e5ee838dc23f0fc467b8db28fcbab8c";
    src = fetchFromGitHub {
      owner = "martinn";
      repo = "repoblame";
      rev = "20ca80088e5ee838dc23f0fc467b8db28fcbab8c";
      fetchSubmodules = false;
      sha256 = "sha256-xInbq62VpjYOMquD1x8ky0v/YdpwYE3Sy3calyJm0Bk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./repoblame-20ca80088e5ee838dc23f0fc467b8db28fcbab8c/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-01-04";
  };
  rexi = {
    pname = "rexi";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "royreznik";
      repo = "rexi";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-tag2/QTM6tDCU3qr4e1GqRYAZgpvEgtA+FtR4P7WdiU=";
    };
  };
  "rgg.fish" = {
    pname = "rgg.fish";
    version = "00a852b7d62553b24b8f1bf65d63744ff40c0e5c";
    src = fetchFromGitHub {
      owner = "soraxas";
      repo = "rgg.fish";
      rev = "00a852b7d62553b24b8f1bf65d63744ff40c0e5c";
      fetchSubmodules = false;
      sha256 = "sha256-PjQpoORrYxgt2/2gonOZDambOq4ZMtLmijxwZYlISIk=";
    };
    date = "2024-07-21";
  };
  rimage = {
    pname = "rimage";
    version = "v0.10.3";
    src = fetchFromGitHub {
      owner = "SalOne22";
      repo = "rimage";
      rev = "v0.10.3";
      fetchSubmodules = false;
      sha256 = "sha256-GfxnZ9fuok4/6BGrCZHD+hslCaHYUv16/8jreK+9JEI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rimage-v0.10.3/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  rsv = {
    pname = "rsv";
    version = "v0.4.14";
    src = fetchFromGitHub {
      owner = "ribbondz";
      repo = "rsv";
      rev = "v0.4.14";
      fetchSubmodules = false;
      sha256 = "sha256-LKom7cLu4P95Vg9m/cP/CfWjeU5tcenejgNQhKPs8uM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rsv-v0.4.14/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  rust-kanban = {
    pname = "rust-kanban";
    version = "v0.10.5";
    src = fetchFromGitHub {
      owner = "yashs662";
      repo = "rust_kanban";
      rev = "v0.10.5";
      fetchSubmodules = false;
      sha256 = "sha256-fwKXH99P3KBiZdCgTBnuF2ovlefX3l06rzyTSeYty9Q=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rust-kanban-v0.10.5/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  rustywatch = {
    pname = "rustywatch";
    version = "v0.2.11";
    src = fetchFromGitHub {
      owner = "ak9024";
      repo = "rustywatch";
      rev = "v0.2.11";
      fetchSubmodules = false;
      sha256 = "sha256-UzMLSPBH/ElpEWnPV2zD1+2Pt6pO4cG7CmgJvy1MawM=";
    };
  };
  s = {
    pname = "s";
    version = "v0.7.1";
    src = fetchFromGitHub {
      owner = "zquestz";
      repo = "s";
      rev = "v0.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-cu2XGA5rRO+cHZ9QkJvMBjbxNZigxsx12ziCJG1LCQs=";
    };
  };
  sake = {
    pname = "sake";
    version = "v0.15.1";
    src = fetchFromGitHub {
      owner = "alajmo";
      repo = "sake";
      rev = "v0.15.1";
      fetchSubmodules = false;
      sha256 = "sha256-aTbom8J4S0ZCiHPfAPeFKZ+15PxG64dGqQtOKXuEBo8=";
    };
  };
  sauce = {
    pname = "sauce";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "cadecuddy";
      repo = "sauce";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-DqJirsbNl8bJuuYZN9nKHMDCgs6agkdx7s0o7h90So8=";
    };
  };
  sbsrf-rime-data = {
    pname = "sbsrf-rime-data";
    version = "20250126";
    src = fetchFromGitHub {
      owner = "sbsrf";
      repo = "sbsrf";
      rev = "20250126";
      fetchSubmodules = false;
      sha256 = "sha256-wyz6r3HLP2ttzzgbSAThvvIqKAgYFGtZ0/MM3rJek2g=";
    };
  };
  sequin = {
    pname = "sequin";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "charmbracelet";
      repo = "sequin";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-rszK2UZ3Eq9g+Di1lncDQIT4TlUcWZEu1SU2aE2uFHY=";
    };
  };
  servicer = {
    pname = "servicer";
    version = "v0.1.13";
    src = fetchFromGitHub {
      owner = "servicer-labs";
      repo = "servicer";
      rev = "v0.1.13";
      fetchSubmodules = false;
      sha256 = "sha256-4/6vu/iIZ7ZHHgi3eMshCIygO3ynFSHoiSGWjHzEcZw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./servicer-v0.1.13/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  shipit = {
    pname = "shipit";
    version = "0.4.0";
    src = fetchFromGitHub {
      owner = "sapegin";
      repo = "shipit";
      rev = "0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-gT+4b1D4kfy39CuFIR/eF316Ep8E1Ef74wuebljfhI4=";
    };
  };
  simple-completion-language-server = {
    pname = "simple-completion-language-server";
    version = "9fc165dbf67321ebb798302ccc1f8ca6748be920";
    src = fetchFromGitHub {
      owner = "estin";
      repo = "simple-completion-language-server";
      rev = "9fc165dbf67321ebb798302ccc1f8ca6748be920";
      fetchSubmodules = false;
      sha256 = "sha256-wzYoCDUx5OdGKE2GqavZW62Pr7vsEXoyPE2kOHnoK08=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./simple-completion-language-server-9fc165dbf67321ebb798302ccc1f8ca6748be920/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-02-04";
  };
  simple-websocket-server = {
    pname = "simple-websocket-server";
    version = "7a9b03766d3a9b1dbbdf671a3bbc6f555806dffe";
    src = fetchFromGitHub {
      owner = "dpallot";
      repo = "simple-websocket-server";
      rev = "7a9b03766d3a9b1dbbdf671a3bbc6f555806dffe";
      fetchSubmodules = false;
      sha256 = "sha256-KWkXLc9k00GHbmz+U8QR4LMiDg7NIItYJajVYeP6SXY=";
    };
    date = "2022-10-21";
  };
  sing-box-fork = {
    pname = "sing-box-fork";
    version = "067c81a73e1fb7b6edbc58e6b06b8b943fa6c40a";
    src = fetchFromGitHub {
      owner = "PuerNya";
      repo = "sing-box";
      rev = "067c81a73e1fb7b6edbc58e6b06b8b943fa6c40a";
      fetchSubmodules = false;
      sha256 = "sha256-03mkClYVAfAatfYJ1OuM1OvABj/fgbseqK8jPbBtI8g=";
    };
    date = "2024-08-16";
  };
  slashslash-fish = {
    pname = "slashslash-fish";
    version = "64d29b229f77e5f01562370f310edc3fcaa5ca1c";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "slashslash.fish";
      rev = "64d29b229f77e5f01562370f310edc3fcaa5ca1c";
      fetchSubmodules = false;
      sha256 = "sha256-5MyDN3NyDKcEn5zUNDq3VZaBM9Mm3wCBuCLTbHP65O4=";
    };
    date = "2025-01-01";
  };
  soba = {
    pname = "soba";
    version = "1.3.1";
    src = fetchFromGitHub {
      owner = "jonhadfield";
      repo = "soba";
      rev = "1.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-RAtfTuL+PqU8jM7wCsjicyBbTXhcXCtDMbYiS6T0VGs=";
    };
  };
  sonicradio = {
    pname = "sonicradio";
    version = "v0.5.8";
    src = fetchFromGitHub {
      owner = "dancnb";
      repo = "sonicradio";
      rev = "v0.5.8";
      fetchSubmodules = false;
      sha256 = "sha256-tKdBw1IR1q9DF2V6kLBQCUz/Yet8/bRnVUQcy6owc1o=";
    };
  };
  sprite-dicing = {
    pname = "sprite-dicing";
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "elringus";
      repo = "sprite-dicing";
      rev = "v2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-Wyws9I/ITdswUqxdmckXtutr5FK8ocsvQRIcMlASiLo=";
    };
  };
  stardict-cn-dicts = {
    pname = "stardict-cn-dicts";
    version = "3d14395f2ad47d20874ace4835c63f6cb5b2f7f4";
    src = fetchFromGitHub {
      owner = "shanyouli";
      repo = "stardict";
      rev = "3d14395f2ad47d20874ace4835c63f6cb5b2f7f4";
      fetchSubmodules = false;
      sha256 = "sha256-0m1f2UenJhIyJ8qLK4Alq0zV40LF76BfRdJKi4KSPMg=";
    };
    date = "2019-11-19";
  };
  stego = {
    pname = "stego";
    version = "d9d5911f4d2d141fea74936f235a74bf03961c71";
    src = fetchFromGitHub {
      owner = "ajmwagar";
      repo = "stego";
      rev = "d9d5911f4d2d141fea74936f235a74bf03961c71";
      fetchSubmodules = false;
      sha256 = "sha256-fChtlJqzI2gTbdN374e3ZQntCHiaknWgrDFSD8+Ee5M=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./stego-d9d5911f4d2d141fea74936f235a74bf03961c71/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2019-10-22";
  };
  subtotxt = {
    pname = "subtotxt";
    version = "2025-02-03";
    src = fetchFromGitHub {
      owner = "NebularNerd";
      repo = "subtotxt";
      rev = "2025-02-03";
      fetchSubmodules = false;
      sha256 = "sha256-/VFzyjzxU3h4xN346euSiOx0jYerJGN6ABR27gnV6cc=";
    };
  };
  sunbeam = {
    pname = "sunbeam";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "pomdtr";
      repo = "sunbeam";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-OKdJHSeZJ39FSOPd/y27g+5NPEMbP9HFN57v+XA9/TA=";
    };
  };
  superwhich = {
    pname = "superwhich";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "DarkCeptor44";
      repo = "superwhich";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-gy9l0831QWdnQMYXNpsHixKgovhTlzCeUXpTGZVG1Kc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./superwhich-v1.1.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  svgshift = {
    pname = "svgshift";
    version = "2cb42460e223b878bff97011da879e964cd5cad3";
    src = fetchFromGitHub {
      owner = "10xJSChad";
      repo = "svgshift";
      rev = "2cb42460e223b878bff97011da879e964cd5cad3";
      fetchSubmodules = false;
      sha256 = "sha256-bJjbWRSgJy1HIWpwSJ6jfezzTfz+obo0S0JJZ7zGh9c=";
    };
    date = "2024-12-27";
  };
  tabry-rs = {
    pname = "tabry-rs";
    version = "d24f00a7fd927aa33c5542b8d37c38aabba65a96";
    src = fetchFromGitHub {
      owner = "evanbattaglia";
      repo = "tabry-rs";
      rev = "d24f00a7fd927aa33c5542b8d37c38aabba65a96";
      fetchSubmodules = false;
      sha256 = "sha256-G1lwV5xafd45ZB2kZUlrY4EOYMnTsSeuew3QwbqAt+8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./tabry-rs-d24f00a7fd927aa33c5542b8d37c38aabba65a96/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-01-04";
  };
  tach = {
    pname = "tach";
    version = "v0.24.1";
    src = fetchFromGitHub {
      owner = "gauge-sh";
      repo = "tach";
      rev = "v0.24.1";
      fetchSubmodules = false;
      sha256 = "sha256-ZyYPnwJiqTRLHA2NHxDN2L2fV7kS0TsdhYwUmuFCwe8=";
    };
  };
  task-relative-recur = {
    pname = "task-relative-recur";
    version = "5d4ab7d0a5e3f697fb2a00790972e6f3f705fe42";
    src = fetchFromGitHub {
      owner = "mlaradji";
      repo = "task-relative-recur";
      rev = "5d4ab7d0a5e3f697fb2a00790972e6f3f705fe42";
      fetchSubmodules = false;
      sha256 = "sha256-oPK67wG0wiUZCgCMtdwvK8w/WKjq3fMbZ9G1HVuVO6Q=";
    };
    date = "2023-02-06";
  };
  taskwarrior-better-recur = {
    pname = "taskwarrior-better-recur";
    version = "2731e1c441d81a3b2217b132e1f40ce4ea49ec5f";
    src = fetchFromGitHub {
      owner = "scottyob";
      repo = "taskwarrior-better-recur";
      rev = "2731e1c441d81a3b2217b132e1f40ce4ea49ec5f";
      fetchSubmodules = false;
      sha256 = "sha256-FpUX+6cOZUhv2ZDHwqlwyl1413RJaekvBADZ4486YPU=";
    };
    date = "2024-07-04";
  };
  templify = {
    pname = "templify";
    version = "2.0.0";
    src = fetchFromGitHub {
      owner = "cophilot";
      repo = "templify";
      rev = "2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-j6utB5Ry/b8P82PwMpzj0Bx1x/I5b065okMMZpEjYTs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./templify-2.0.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  termsand = {
    pname = "termsand";
    version = "75a50ba82ed299047cd5d0cd53b6fce390cfc6e8";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "termsand";
      rev = "75a50ba82ed299047cd5d0cd53b6fce390cfc6e8";
      fetchSubmodules = false;
      sha256 = "sha256-tylzyjg3AJutwnrxjxzshEfuTD14VegCIMb/wroGpj0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./termsand-75a50ba82ed299047cd5d0cd53b6fce390cfc6e8/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-08-15";
  };
  tewi = {
    pname = "tewi";
    version = "v0.6.0";
    src = fetchFromGitHub {
      owner = "anlar";
      repo = "tewi";
      rev = "v0.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-JMVsmu98WJaeFGAzIKb+dwQ4a70M9ZuaSGYqZ3Tku9M=";
    };
  };
  textimg = {
    pname = "textimg";
    version = "v3.1.10";
    src = fetchFromGitHub {
      owner = "jiro4989";
      repo = "textimg";
      rev = "v3.1.10";
      fetchSubmodules = false;
      sha256 = "sha256-6lmGuqXuK0ROf24wLEEeGIK0Etk1qMtsmT52LCnmWQc=";
    };
  };
  textpod = {
    pname = "textpod";
    version = "0.1.4";
    src = fetchFromGitHub {
      owner = "freetonik";
      repo = "textpod";
      rev = "0.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-d0CjHtzWHJYqWts1WiulIZebZwiAls36VpYOi0qwv/k=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./textpod-0.1.4/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  textual = {
    pname = "textual";
    version = "1.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/textual/textual-1.0.0.tar.gz";
      sha256 = "sha256-vsn+Y1R8HFUladG3XTCQOLfUVsA/ht+jcG3bCZsVE5k=";
    };
  };
  timewarrior = {
    pname = "timewarrior";
    version = "v1.7.1";
    src = fetchFromGitHub {
      owner = "GothenburgBitFactory";
      repo = "timewarrior";
      rev = "v1.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-wuSKZh46B6hufwnVP/FIT9LW67Wp2qyV+0xczhU4a0U=";
    };
  };
  tmux-auto-renumber-session = {
    pname = "tmux-auto-renumber-session";
    version = "19fead0395afdc36830d840249c0c7190ccd8bb9";
    src = fetchFromGitHub {
      owner = "T1erno";
      repo = "tmux-auto-renumber-session";
      rev = "19fead0395afdc36830d840249c0c7190ccd8bb9";
      fetchSubmodules = false;
      sha256 = "sha256-An92IORTC2aeKGkUcAEj8gLPd9t5V3FE4EaAHF4LDoA=";
    };
    date = "2023-03-01";
  };
  tmux-buoyshell = {
    pname = "tmux-buoyshell";
    version = "d0c01edb1f720aadf9b52db1db26e3cdc81f689d";
    src = fetchFromGitHub {
      owner = "cnavajas4";
      repo = "tmux-buoyshell";
      rev = "d0c01edb1f720aadf9b52db1db26e3cdc81f689d";
      fetchSubmodules = false;
      sha256 = "sha256-ojNq6q2yJO6zF1Ara/dsc0QfBm703HeeHVNzjQp+vkQ=";
    };
    date = "2025-02-05";
  };
  tmux-continuum = {
    pname = "tmux-continuum";
    version = "c7ae4f4f4a1c5b7a00718f71742eb3d3ebd9b82a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-continuum";
      rev = "c7ae4f4f4a1c5b7a00718f71742eb3d3ebd9b82a";
      fetchSubmodules = false;
      sha256 = "sha256-YqQvKWQ+nPxGJoA4LQVWAuRt9gzLsF7bi/KB4uofpe8=";
    };
    date = "2024-07-08";
  };
  tmux-edgelord = {
    pname = "tmux-edgelord";
    version = "a390528534bf8e0f050daa1776db555eba4fadd9";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-edgelord";
      rev = "a390528534bf8e0f050daa1776db555eba4fadd9";
      fetchSubmodules = false;
      sha256 = "sha256-jermraRckdUz3BQCJVKcF1DyuKhnUzfSBJcCicXC7Q4=";
    };
    date = "2024-07-08";
  };
  tmux-floax = {
    pname = "tmux-floax";
    version = "61c7f466b9a4ceed56f99d403250164170d586cd";
    src = fetchFromGitHub {
      owner = "omerxx";
      repo = "tmux-floax";
      rev = "61c7f466b9a4ceed56f99d403250164170d586cd";
      fetchSubmodules = false;
      sha256 = "sha256-DOwn7XEg/L95YieUAyZU0FJ49vm2xKGUclm8WCKDizU=";
    };
    date = "2024-11-21";
  };
  tmux-fzf-url = {
    pname = "tmux-fzf-url";
    version = "16381dce1c30fedd75fc775f887be7ea6c7cbf55";
    src = fetchFromGitHub {
      owner = "wfxr";
      repo = "tmux-fzf-url";
      rev = "16381dce1c30fedd75fc775f887be7ea6c7cbf55";
      fetchSubmodules = false;
      sha256 = "sha256-n3dEUnu0jd1MiWKRCr3HpWlq6Lw4eCYOKLbG30QgSx0=";
    };
    date = "2025-01-07";
  };
  tmux-kanagawa = {
    pname = "tmux-kanagawa";
    version = "0d2db8d95e1b74643a06802043c7000a79ba0a0a";
    src = fetchFromGitHub {
      owner = "Nybkox";
      repo = "tmux-kanagawa";
      rev = "0d2db8d95e1b74643a06802043c7000a79ba0a0a";
      fetchSubmodules = false;
      sha256 = "sha256-9S4HQHuECGLPLdPishmwEO0twdeQ6mZQfIMNFFDkgQ8=";
    };
    date = "2024-12-02";
  };
  tmux-loadavg = {
    pname = "tmux-loadavg";
    version = "91319eff74ee677efb77c882dcc8e3b8780dc3a2";
    src = fetchFromGitHub {
      owner = "jamesoff";
      repo = "tmux-loadavg";
      rev = "91319eff74ee677efb77c882dcc8e3b8780dc3a2";
      fetchSubmodules = false;
      sha256 = "sha256-JW/O/bVryDILlFCnWYRC+B7nrCIsGYEJDozzu0odX+U=";
    };
    date = "2018-05-30";
  };
  tmux-mouse-swipe = {
    pname = "tmux-mouse-swipe";
    version = "ecc540e96eb005578e6731d456df5a17d8301c8e";
    src = fetchFromGitHub {
      owner = "jaclu";
      repo = "tmux-mouse-swipe";
      rev = "ecc540e96eb005578e6731d456df5a17d8301c8e";
      fetchSubmodules = false;
      sha256 = "sha256-SRYroDifMxdUFEnKE3ObdfACoFjZyzL7FIEDIeZWF6k=";
    };
    date = "2024-12-21";
  };
  tmux-pane-focus = {
    pname = "tmux-pane-focus";
    version = "94adfd620bee88b9262fe28df6b07a23e82f3a5c";
    src = fetchFromGitHub {
      owner = "graemedavidson";
      repo = "tmux-pane-focus";
      rev = "94adfd620bee88b9262fe28df6b07a23e82f3a5c";
      fetchSubmodules = false;
      sha256 = "sha256-Aur7OkJ8De6BDtSJHSfO1LLpbCfjWsxXi8jh5HNlUbo=";
    };
    date = "2024-03-05";
  };
  tmux-power-zoom = {
    pname = "tmux-power-zoom";
    version = "3a1de2280e9b7ffcb8efd009fc87fd34ecbb14ac";
    src = fetchFromGitHub {
      owner = "jaclu";
      repo = "tmux-power-zoom";
      rev = "3a1de2280e9b7ffcb8efd009fc87fd34ecbb14ac";
      fetchSubmodules = false;
      sha256 = "sha256-WdA4QwqPkUPrCzb/qm3kSKSDD0DtDMIzkwC5wXQ0oKE=";
    };
    date = "2024-12-21";
  };
  tmux-tea = {
    pname = "tmux-tea";
    version = "345af747c36e94344cbb360310f1d746f1517b6a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-tea";
      rev = "345af747c36e94344cbb360310f1d746f1517b6a";
      fetchSubmodules = false;
      sha256 = "sha256-CgPn+VZmaMm8lxJlgzQRLdhwHM/XA+KSIr/qwQdf5bs=";
    };
    date = "2024-09-10";
  };
  tmux-tome = {
    pname = "tmux-tome";
    version = "122fd17d2bd915dfd489cbf6308eaf60d3273c57";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "tome";
      rev = "122fd17d2bd915dfd489cbf6308eaf60d3273c57";
      fetchSubmodules = false;
      sha256 = "sha256-osrQM5eyzCGTD/8utKU4HE1ammoxSzIbgJpM+hbXeKE=";
    };
    date = "2025-01-08";
  };
  tmux-transient-status = {
    pname = "tmux-transient-status";
    version = "c3fcd5180999a7afc075d2dd37d37d1b1b82f7e8";
    src = fetchFromGitHub {
      owner = "TheSast";
      repo = "tmux-transient-status";
      rev = "c3fcd5180999a7afc075d2dd37d37d1b1b82f7e8";
      fetchSubmodules = false;
      sha256 = "sha256-fOIn8hVVBDFVLwzmPZP+Bf3ccxy/hsAnKIXYD9yv3BE=";
    };
    date = "2023-12-26";
  };
  tmux-which-key = {
    pname = "tmux-which-key";
    version = "1f419775caf136a60aac8e3a269b51ad10b51eb6";
    src = fetchFromGitHub {
      owner = "alexwforsythe";
      repo = "tmux-which-key";
      rev = "1f419775caf136a60aac8e3a269b51ad10b51eb6";
      fetchSubmodules = false;
      sha256 = "sha256-X7FunHrAexDgAlZfN+JOUJvXFZeyVj9yu6WRnxMEA8E=";
    };
    date = "2024-07-08";
  };
  "tmux.fish" = {
    pname = "tmux.fish";
    version = "e27bb956e1a39c041a151f3a2a6bb3861e265e7a";
    src = fetchFromGitHub {
      owner = "budimanjojo";
      repo = "tmux.fish";
      rev = "e27bb956e1a39c041a151f3a2a6bb3861e265e7a";
      fetchSubmodules = false;
      sha256 = "sha256-oREvB4jfmk1EH9yry7u0GkmJty0vCUxFtLgZxFMSWf4=";
    };
    date = "2025-01-18";
  };
  tmux2k = {
    pname = "tmux2k";
    version = "5e11cd8ead1e8c7e375c6808489e06be1de403f4";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "tmux2k";
      rev = "5e11cd8ead1e8c7e375c6808489e06be1de403f4";
      fetchSubmodules = false;
      sha256 = "sha256-4JVNJ7Lcvr93UM8zq0K9RcAnQcBkfh6SnRyT8qBqZRo=";
    };
    date = "2025-01-02";
  };
  to-fish = {
    pname = "to-fish";
    version = "52b151cfe67c00cb64d80ccc6dae398f20364938";
    src = fetchFromGitHub {
      owner = "joehillen";
      repo = "to-fish";
      rev = "52b151cfe67c00cb64d80ccc6dae398f20364938";
      fetchSubmodules = false;
      sha256 = "sha256-DfDsU/qY2XdYlkLISIOv02ggHfKEpb+YompNWWjs5/A=";
    };
    date = "2023-04-24";
  };
  "todo-comments.fish" = {
    pname = "todo-comments.fish";
    version = "fb818507c2b95e498495fb73206eb101566d71ee";
    src = fetchFromGitHub {
      owner = "kpbaks";
      repo = "todo-comments.fish";
      rev = "fb818507c2b95e498495fb73206eb101566d71ee";
      fetchSubmodules = false;
      sha256 = "sha256-x6B1qm1sEODBus6Dd30iifcOMj/q+8DA3pKzKQ7zzlc=";
    };
    date = "2024-02-11";
  };
  tokyonight-vim = {
    pname = "tokyonight-vim";
    version = "4e82e0f0452a6ce8f387828ec71013015515035a";
    src = fetchFromGitHub {
      owner = "ghifarit53";
      repo = "tokyonight-vim";
      rev = "4e82e0f0452a6ce8f387828ec71013015515035a";
      fetchSubmodules = false;
      sha256 = "sha256-ui/6xv8PH6KuQ4hG1FNMf6EUdF2wfWPNgG/GMXYvn/8=";
    };
    date = "2021-04-23";
  };
  toru = {
    pname = "toru";
    version = "v0.3.3";
    src = fetchFromGitHub {
      owner = "sweetbbak";
      repo = "toru";
      rev = "v0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-hFs/CJHWgfy/KCp7lC8u8YrclQk0RWhrSe4IXbsJL3I=";
    };
  };
  tp = {
    pname = "tp";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "minefuto";
      repo = "tp";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-e/G0cN0HKzpgBRajztp/DucgO0JWW/jqi/omvLWsVyQ=";
    };
  };
  treegen = {
    pname = "treegen";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "bilbilak";
      repo = "treegen";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-PPWUEfX7OXKZnghiVXU+eCjveA1VszA3uS8C3uI3pFM=";
    };
  };
  trzsz-go = {
    pname = "trzsz-go";
    version = "v1.1.8";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-go";
      rev = "v1.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-g1fbgKTFS9aPAmnTeFYoymrDEoZ6BtzUhA2Z9SNYbsU=";
    };
  };
  trzsz-ssh = {
    pname = "trzsz-ssh";
    version = "v0.1.22";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-ssh";
      rev = "v0.1.22";
      fetchSubmodules = false;
      sha256 = "sha256-VvPdWRP+lrhho+Bk5rT9pktEvKe01512WoDfAu5d868=";
    };
  };
  tui-network = {
    pname = "tui-network";
    version = "e1c932daf532805b522201383984da4a29e156fe";
    src = fetchFromGitHub {
      owner = "Zatfer17";
      repo = "tui-network";
      rev = "e1c932daf532805b522201383984da4a29e156fe";
      fetchSubmodules = false;
      sha256 = "sha256-JfgUvgQ0eGqt/l6JN6Tfmtr0tVbbbNKJzv+RFIyEhMs=";
    };
    date = "2025-01-02";
  };
  tuime = {
    pname = "tuime";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "nate-sys";
      repo = "tuime";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-9CGktRXx7IZ0yv/U78SWSifJ6YBIiV8cf5Dq60PPCcQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./tuime-v1.0.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  updo = {
    pname = "updo";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "Owloops";
      repo = "updo";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-AkzniJ58tcesLSsOaJW1n1z4cavo2O8DUD0+ImBBLgM=";
    };
  };
  v = {
    pname = "v";
    version = "353a0e7620294d840bdffcf0e7c5e287625a9709";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "v";
      rev = "353a0e7620294d840bdffcf0e7c5e287625a9709";
      fetchSubmodules = false;
      sha256 = "sha256-urXj1+UTwc6yFxThSm/05HQ2A+N9xuiZHfyDA2BhQ/w=";
    };
    date = "2024-11-03";
  };
  v2dat = {
    pname = "v2dat";
    version = "47b8ee51fb528e11e1a83453b7e767a18d20d1f7";
    src = fetchFromGitHub {
      owner = "urlesistiana";
      repo = "v2dat";
      rev = "47b8ee51fb528e11e1a83453b7e767a18d20d1f7";
      fetchSubmodules = false;
      sha256 = "sha256-dJld4hYdfnpphIEJvYsj5VvEF4snLvXZ059HJ2BXwok=";
    };
    date = "2022-12-15";
  };
  v2ray-rules-dat-geoip = {
    pname = "v2ray-rules-dat-geoip";
    version = "202502062212";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202502062212/geoip.dat";
      sha256 = "sha256-UIdnS3nXNIEpMnd1rDu/yqPPsNKdrs90JPhjYNrxhX4=";
    };
  };
  v2ray-rules-dat-geosite = {
    pname = "v2ray-rules-dat-geosite";
    version = "202502062212";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202502062212/geosite.dat";
      sha256 = "sha256-g6F76TgaPvimeL7fVMGoHUGhJVpg+dJm3UZzibZ6kSQ=";
    };
  };
  vim-auto-save = {
    pname = "vim-auto-save";
    version = "6697e84b25f6a56c36d0c5ae9004b8b9247662ea";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-auto-save";
      rev = "6697e84b25f6a56c36d0c5ae9004b8b9247662ea";
      fetchSubmodules = false;
      sha256 = "sha256-hP3s7iIfGjLMYF6lqnL6ORGqmPfM0d2BCdW4OSqg4ac=";
    };
    date = "2024-07-15";
  };
  vim-cycle = {
    pname = "vim-cycle";
    version = "57a2a7ca9451f47146a829cc74c1c950a855329e";
    src = fetchFromGitHub {
      owner = "zef";
      repo = "vim-cycle";
      rev = "57a2a7ca9451f47146a829cc74c1c950a855329e";
      fetchSubmodules = false;
      sha256 = "sha256-PwLM6QCHDq3I9FR6sslvZjQ+a0qLVrZH3gie1KnFIFA=";
    };
    date = "2025-01-23";
  };
  vim-dirvish-dovish = {
    pname = "vim-dirvish-dovish";
    version = "04c77b6010f7e45e72b4d3c399c120d42f7c5d47";
    src = fetchFromGitHub {
      owner = "roginfarrer";
      repo = "vim-dirvish-dovish";
      rev = "04c77b6010f7e45e72b4d3c399c120d42f7c5d47";
      fetchSubmodules = false;
      sha256 = "sha256-8uw1Ft48JVphhdhd9TBcB3b9NFBRkwdEQH2LZblE1dk=";
    };
    date = "2022-06-10";
  };
  vim-floaterm = {
    pname = "vim-floaterm";
    version = "4e28c8dd0271e10a5f55142fb6fe9b1599ee6160";
    src = fetchFromGitHub {
      owner = "voldikss";
      repo = "vim-floaterm";
      rev = "4e28c8dd0271e10a5f55142fb6fe9b1599ee6160";
      fetchSubmodules = false;
      sha256 = "sha256-wIgcBcdxJsT+qrsC5Boj6hp0xpp5gFeQFhK7yyC5a1o=";
    };
    date = "2024-04-08";
  };
  vim-ghost = {
    pname = "vim-ghost";
    version = "115e2600481c92c0bfb69d82ccbd8af7dc052a03";
    src = fetchFromGitHub {
      owner = "raghur";
      repo = "vim-ghost";
      rev = "115e2600481c92c0bfb69d82ccbd8af7dc052a03";
      fetchSubmodules = false;
      sha256 = "sha256-sC83gfCY3vtHDQ5iKV2Ax9DqES2qBz6a4Hro1TDsd5U=";
    };
    date = "2021-09-26";
  };
  vim-github-link = {
    pname = "vim-github-link";
    version = "9df238dbf150417772f2a1b7748750cfeda3d167";
    src = fetchFromGitHub {
      owner = "knsh14";
      repo = "vim-github-link";
      rev = "9df238dbf150417772f2a1b7748750cfeda3d167";
      fetchSubmodules = false;
      sha256 = "sha256-FGPtU+/sEULde5G2xwqVqf9kIWwUE426/Ot7uZoW8Pk=";
    };
    date = "2024-11-01";
  };
  vim-hug-neovim-rpc = {
    pname = "vim-hug-neovim-rpc";
    version = "93ae38792bc197c3bdffa2716ae493c67a5e7957";
    src = fetchFromGitHub {
      owner = "roxma";
      repo = "vim-hug-neovim-rpc";
      rev = "93ae38792bc197c3bdffa2716ae493c67a5e7957";
      fetchSubmodules = false;
      sha256 = "sha256-XX+0FUk2tXG7fklGT2pNsa4vUG+qYSDUMhB5HSAg6Ww=";
    };
    date = "2021-05-15";
  };
  vim-mkdir = {
    pname = "vim-mkdir";
    version = "f0ba7a7dc190a0cedf1d827958c99f3718109cf0";
    src = fetchFromGitHub {
      owner = "pbrisbin";
      repo = "vim-mkdir";
      rev = "f0ba7a7dc190a0cedf1d827958c99f3718109cf0";
      fetchSubmodules = false;
      sha256 = "sha256-3GZFp6Q6ZM48b4Qxy3BpsMGI9K9vmIsvZ53R6niw4k4=";
    };
    date = "2019-04-29";
  };
  vim-silicon = {
    pname = "vim-silicon";
    version = "4a93122ae2139a12e2a56f064d086c05160b6835";
    src = fetchFromGitHub {
      owner = "segeljakt";
      repo = "vim-silicon";
      rev = "4a93122ae2139a12e2a56f064d086c05160b6835";
      fetchSubmodules = false;
      sha256 = "sha256-8pCHtApD/xXav2UBVOVhkaHg3YS4aNCZ73mog04bYuA=";
    };
    date = "2020-12-01";
  };
  vim-snipewin = {
    pname = "vim-snipewin";
    version = "9616fd4564d61c78947e3dda53ef9ac61cce032c";
    src = fetchFromGitHub {
      owner = "4513ECHO";
      repo = "vim-snipewin";
      rev = "9616fd4564d61c78947e3dda53ef9ac61cce032c";
      fetchSubmodules = false;
      sha256 = "sha256-dUOP8/NBwAhie0DUdkjyCUuoQ9q1UD1PJm02zzz9BNg=";
    };
    date = "2024-03-28";
  };
  vim-templates = {
    pname = "vim-templates";
    version = "c4ce1903fc458688bc421f0cb4572af8a8977cdb";
    src = fetchFromGitHub {
      owner = "tibabit";
      repo = "vim-templates";
      rev = "c4ce1903fc458688bc421f0cb4572af8a8977cdb";
      fetchSubmodules = false;
      sha256 = "sha256-p0TEJr/2TBoOk48xgtrqwnAtQlYRkz/NEKcadLAJoCA=";
    };
    date = "2024-04-26";
  };
  vim-tome = {
    pname = "vim-tome";
    version = "122fd17d2bd915dfd489cbf6308eaf60d3273c57";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "tome";
      rev = "122fd17d2bd915dfd489cbf6308eaf60d3273c57";
      fetchSubmodules = false;
      sha256 = "sha256-osrQM5eyzCGTD/8utKU4HE1ammoxSzIbgJpM+hbXeKE=";
    };
    date = "2025-01-08";
  };
  vim-toop = {
    pname = "vim-toop";
    version = "836c043756b57770068186886b72cbb2fef0d0eb";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-toop";
      rev = "836c043756b57770068186886b72cbb2fef0d0eb";
      fetchSubmodules = false;
      sha256 = "sha256-+z/4uAIUMqaoXxzqF9qVZsPIWh04zkfybZT+opeJOXg=";
    };
    date = "2024-10-16";
  };
  vim-visual-star-search = {
    pname = "vim-visual-star-search";
    version = "3ea07a973a8f3cb2b714c50ac0adca35da157631";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-visual-star-search";
      rev = "3ea07a973a8f3cb2b714c50ac0adca35da157631";
      fetchSubmodules = false;
      sha256 = "sha256-hiL9DuvQl4wUSZWCLJjGZYWLzIRXqbVCtZ1GLJTKFp4=";
    };
    date = "2024-07-16";
  };
  vim-workspace = {
    pname = "vim-workspace";
    version = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
    src = fetchFromGitHub {
      owner = "thaerkh";
      repo = "vim-workspace";
      rev = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
      fetchSubmodules = false;
      sha256 = "sha256-2Brx098dk5THiieBiW71FG9mUUwS1CSY9mpOPWA/Tq4=";
    };
    date = "2023-05-28";
  };
  vim-zoom = {
    pname = "vim-zoom";
    version = "65145acd49c62e042502e6f9a5b9b468006c768f";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-zoom";
      rev = "65145acd49c62e042502e6f9a5b9b468006c768f";
      fetchSubmodules = false;
      sha256 = "sha256-mTcqxP9mr9P14d7fCUWhIY7Zu4ehjwLJbjMrBsNBUHc=";
    };
    date = "2024-07-17";
  };
  vimsuggest = {
    pname = "vimsuggest";
    version = "512cf5727e6594b8b5b897173c2b0af61104ec05";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "vimsuggest";
      rev = "512cf5727e6594b8b5b897173c2b0af61104ec05";
      fetchSubmodules = false;
      sha256 = "sha256-mCyNxOLeqKTsvG+9oaCHSQlwwbxZj1T2E5UGWWAXPoE=";
    };
    date = "2025-02-05";
  };
  visual-split-vim = {
    pname = "visual-split-vim";
    version = "423a25911b3e8da04a28d29f205e1059a06e6afa";
    src = fetchFromGitHub {
      owner = "wellle";
      repo = "visual-split.vim";
      rev = "423a25911b3e8da04a28d29f205e1059a06e6afa";
      fetchSubmodules = false;
      sha256 = "sha256-v0j6AExrOJIgde/Aphr7lvonZptMwYQLCB6E+2YsiVg=";
    };
    date = "2017-01-29";
  };
  vl = {
    pname = "vl";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "ellisonleao";
      repo = "vl";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-zmSwlZwbPNafe2PyvFHMeQuJNJvs/c3zsMfVagcVXlU=";
    };
  };
  vlime = {
    pname = "vlime";
    version = "f57518bf6ac1b6c5e10db6a9259016b84ff81d8b";
    src = fetchFromGitHub {
      owner = "vlime";
      repo = "vlime";
      rev = "f57518bf6ac1b6c5e10db6a9259016b84ff81d8b";
      fetchSubmodules = false;
      sha256 = "sha256-034h9L9k+X3b+Z1Kt6HGiteYbHajoo8wu5zgh7RIjv8=";
    };
    date = "2023-10-08";
  };
  vsc-fugitive = {
    pname = "vsc-fugitive";
    version = "0.0.26";
    src = fetchurl {
      url = "https://hnrk-str.gallery.vsassets.io/_apis/public/gallery/publisher/hnrk-str/extension/vscode-fugitive/0.0.26/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-fugitive-0.0.26.zip";
      sha256 = "sha256-bKgPlfI+f/RpsbNJvlP78jubgQrztloTjxroCWaCFSQ=";
    };
  };
  wait-for = {
    pname = "wait-for";
    version = "v2.2.4";
    src = fetchFromGitHub {
      owner = "eficode";
      repo = "wait-for";
      rev = "v2.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-lPJahbaS/YGVqFUvP6AcpDeQXh2yq7GgicADMcH7fKs=";
    };
  };
  "web-search.fish" = {
    pname = "web-search.fish";
    version = "29d3027685cdc7f8ed857e3888733c6d5b5458fb";
    src = fetchFromGitHub {
      owner = "veirt";
      repo = "web-search.fish";
      rev = "29d3027685cdc7f8ed857e3888733c6d5b5458fb";
      fetchSubmodules = false;
      sha256 = "sha256-bGgdO3jS+kYaTQBhfw9bGke1S6egg9S4fmEe0buf684=";
    };
    date = "2024-10-14";
  };
  whitespace-format = {
    pname = "whitespace-format";
    version = "0.0.6";
    src = fetchFromGitHub {
      owner = "DavidPal";
      repo = "whitespace-format";
      rev = "0.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-PaFZst2O8pNI+LSws31nrbs4ih76r5ouJhFi/cgst80=";
    };
  };
  x = {
    pname = "x";
    version = "v1.1.4";
    src = fetchFromGitHub {
      owner = "devhindo";
      repo = "x";
      rev = "v1.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-sAmyZFX9lZ6UXVCt7st187Ie6aVW0dSUlQQQmLiHUlM=";
    };
  };
  ynk = {
    pname = "ynk";
    version = "a7eebd75f6179420207a9247f1524198880f8335";
    src = fetchFromGitHub {
      owner = "newtoallofthis123";
      repo = "ynk";
      rev = "a7eebd75f6179420207a9247f1524198880f8335";
      fetchSubmodules = false;
      sha256 = "sha256-tEqrl8FGhojrrgru7R9Ttslla65q/AIYxAJJKCEINSk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./ynk-a7eebd75f6179420207a9247f1524198880f8335/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-01-06";
  };
  ytui = {
    pname = "ytui";
    version = "v0.2.2";
    src = fetchFromGitHub {
      owner = "Banh-Canh";
      repo = "ytui";
      rev = "v0.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-SxgjyplbxevXVp4r3HOZE0odzBCtfbO3IeNXB3M+8W8=";
    };
  };
}
