# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  adl = {
    pname = "adl";
    version = "3cbacf34728ca2bb8056865cff78d6f3b54688c8";
    src = fetchFromGitHub {
      owner = "RaitaroH";
      repo = "adl";
      rev = "3cbacf34728ca2bb8056865cff78d6f3b54688c8";
      fetchSubmodules = false;
      sha256 = "sha256-LJ+awJHXOYSGuuvD/jq1zO26aKYAsK6hoVkcsmfArZI=";
    };
    date = "2024-09-02";
  };
  advance-touch = {
    pname = "advance-touch";
    version = "1.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/advance-touch/advance-touch-1.0.2.tar.gz";
      sha256 = "sha256-I4wF4PuhDUnM7YluERJzMWysUODtfUTPOo4nvNSGZ8U=";
    };
  };
  ahoy = {
    pname = "ahoy";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "ahoy-cli";
      repo = "ahoy";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-xwjfY9HudxVz3xEEyRPtWysbojtan56ABBL3KgG0J/8=";
    };
  };
  akuse = {
    pname = "akuse";
    version = "1.9.0";
    src = fetchFromGitHub {
      owner = "akuse-app";
      repo = "akuse";
      rev = "1.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-+d2OjkzQspwcEaacIOxN07V4H3vXJyrKmDM0y8WCBlc=";
    };
  };
  animdl = {
    pname = "animdl";
    version = "c7c3b79198e66695e0bbbc576f9d9b788616957f";
    src = fetchFromGitHub {
      owner = "justfoolingaround";
      repo = "animdl";
      rev = "c7c3b79198e66695e0bbbc576f9d9b788616957f";
      fetchSubmodules = false;
      sha256 = "sha256-kn6vCCFhJNlruxoO+PTHVIwTf1E5j1aSdBhrFuGzUq4=";
    };
    date = "2023-10-17";
  };
  antifennel = {
    pname = "antifennel";
    version = "a135f016414517ecb624bad26b39ed56d256beaa";
    src = fetchgit {
      url = "https://git.sr.ht/~technomancy/antifennel";
      rev = "a135f016414517ecb624bad26b39ed56d256beaa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XynKKDyykyPM4z2ZLp9Oy8KFlEZG2iHXKMkajaS/DaE=";
    };
    date = "2024-09-25";
  };
  argparse = {
    pname = "argparse";
    version = "1.4.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/argparse/argparse-1.4.0.tar.gz";
      sha256 = "sha256-YrCJpVvh2JSc0rx+DfC9254Cj678jDIDjMhIYq791uQ=";
    };
  };
  autocrop = {
    pname = "autocrop";
    version = "2afe00ed87fb10a6d368d0d4140307dc99b1a545";
    src = fetchFromGitHub {
      owner = "mandykoh";
      repo = "autocrop";
      rev = "2afe00ed87fb10a6d368d0d4140307dc99b1a545";
      fetchSubmodules = false;
      sha256 = "sha256-oxvu0P0LmusFQ5qX557pgyiq+eslWwfCaoEAkxJnqOA=";
    };
    date = "2021-06-03";
  };
  "autopair.fish" = {
    pname = "autopair.fish";
    version = "ec7ccf41eb945657a829338e85c88ad3353f961a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "autopair.fish";
      rev = "ec7ccf41eb945657a829338e85c88ad3353f961a";
      fetchSubmodules = false;
      sha256 = "sha256-hM2J82NHe5LPSHZ+yYHZNWAjif0vbwerloHIvTUT+tQ=";
    };
    date = "2024-07-08";
  };
  av = {
    pname = "av";
    version = "v0.0.43";
    src = fetchFromGitHub {
      owner = "aviator-co";
      repo = "av";
      rev = "v0.0.43";
      fetchSubmodules = false;
      sha256 = "sha256-zfS7yfsKvfWQXRx4yYrWIbB9ak/hTs+Gq3UH6o7PkKE=";
    };
  };
  awesome-freedesktop = {
    pname = "awesome-freedesktop";
    version = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
    src = fetchFromGitHub {
      owner = "lcpz";
      repo = "awesome-freedesktop";
      rev = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
      fetchSubmodules = false;
      sha256 = "sha256-lQstCcTPUYUt5hzAJIyQ16crPngeOnUla7I4QiG6gEs=";
    };
    date = "2022-06-23";
  };
  baca = {
    pname = "baca";
    version = "v0.1.17";
    src = fetchFromGitHub {
      owner = "wustho";
      repo = "baca";
      rev = "v0.1.17";
      fetchSubmodules = false;
      sha256 = "sha256-uiMzXqA52atees5tHC5Vqk3ALojkJZ8ouivo+omBnlM=";
    };
  };
  bafi = {
    pname = "bafi";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "mmalcek";
      repo = "bafi";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-mYfnHb6Gin2e+Zjvo87ZzTp1/mnDG42UDl99zncB3O0=";
    };
  };
  baidupcs-go = {
    pname = "baidupcs-go";
    version = "v3.9.5";
    src = fetchFromGitHub {
      owner = "qjfoidnh";
      repo = "BaiduPCS-Go";
      rev = "v3.9.5";
      fetchSubmodules = false;
      sha256 = "sha256-zNodRQzflOOB3hAeq4KbjRFlHQwknVy+4ucipUcoufY=";
    };
  };
  blendr = {
    pname = "blendr";
    version = "v1.3.3";
    src = fetchFromGitHub {
      owner = "dmtrKovalenko";
      repo = "blendr";
      rev = "v1.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-6QRI1MQnoppzlVfRV/bfqfTnBjC0/haFm52Ez9nltzw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./blendr-v1.3.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  bling = {
    pname = "bling";
    version = "19ccfc0daf5edda8bbc508487616d00277a9d954";
    src = fetchFromGitHub {
      owner = "BlingCorp";
      repo = "bling";
      rev = "19ccfc0daf5edda8bbc508487616d00277a9d954";
      fetchSubmodules = false;
      sha256 = "sha256-6NZSUb7sSBUegSIPIubQUOZG3knzXfnyfEbCoEyggtc=";
    };
    date = "2024-06-02";
  };
  blobdrop = {
    pname = "blobdrop";
    version = "v2.1";
    src = fetchFromGitHub {
      owner = "vimpostor";
      repo = "blobdrop";
      rev = "v2.1";
      fetchSubmodules = false;
      sha256 = "sha256-o2+qtkyu2qcwXpum3KiogyO8D6aY7bRJ6y4FWQKQY/o=";
    };
  };
  bluetui = {
    pname = "bluetui";
    version = "v0.5.1";
    src = fetchFromGitHub {
      owner = "pythops";
      repo = "bluetui";
      rev = "v0.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-9svPIZzKuI4XBlxBsKucGLdX2dkfAy9ERT5oj8Su9TM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./bluetui-v0.5.1/Cargo.lock;
      outputHashes = {

      };
    };
  };
  boilr = {
    pname = "boilr";
    version = "0.3.0";
    src = fetchurl {
      url = "https://github.com/tmrts/boilr/releases/download/0.3.0/boilr-0.3.0-linux_amd64.tgz";
      sha256 = "sha256-vJTN8g2XcXJjekmV6g3hezck0pgNP6pRSrbulHbqwFU=";
    };
  };
  bt = {
    pname = "bt";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "LeperGnome";
      repo = "bt";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-6hNdAmAflPcky1QxQvZCo+ffprRuIn2NPZYlS4wurww=";
    };
  };
  c = {
    pname = "c";
    version = "7cdc09e69d2f7fc49f70c80c565aa09b19e666db";
    src = fetchFromGitHub {
      owner = "ryanmjacobs";
      repo = "c";
      rev = "7cdc09e69d2f7fc49f70c80c565aa09b19e666db";
      fetchSubmodules = false;
      sha256 = "sha256-dOFM9wQzoEsuBwWb/FfxGDW07oyRXyGRH7lpscoSgUY=";
    };
    date = "2023-11-24";
  };
  cache = {
    pname = "cache";
    version = "0.2.0";
    src = fetchFromGitHub {
      owner = "Hejsil";
      repo = "cache";
      rev = "0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-9SvKw096yvLG4eYnNfIgHpgc5VceXqKkALSEBVuqfi0=";
    };
  };
  cat_win = {
    pname = "cat_win";
    version = "v1.9.2";
    src = fetchFromGitHub {
      owner = "SilenZcience";
      repo = "cat_win";
      rev = "v1.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-PfGhd8mI3vccUg9XykR3NRHS6GKd1P4tfLqEmEizUkU=";
    };
  };
  cdo = {
    pname = "cdo";
    version = "8aefae7fcac56615a053fc99fd5f977328ceea2b";
    src = fetchFromGitHub {
      owner = "dotboris";
      repo = "cdo";
      rev = "8aefae7fcac56615a053fc99fd5f977328ceea2b";
      fetchSubmodules = false;
      sha256 = "sha256-rPhaVlHFTFThu+QC4GAFNLijpOC26NYVKFn371hUPLw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cdo-8aefae7fcac56615a053fc99fd5f977328ceea2b/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2024-11-09";
  };
  chezmoi-vim = {
    pname = "chezmoi-vim";
    version = "abf37336437867cbd99ce2f8849b717415391cc3";
    src = fetchFromGitHub {
      owner = "alker0";
      repo = "chezmoi.vim";
      rev = "abf37336437867cbd99ce2f8849b717415391cc3";
      fetchSubmodules = false;
      sha256 = "sha256-S1/myC1dEydi1F9a6XV0lJW3S/wWQe+A2ZXPo8GbtQo=";
    };
    date = "2024-07-26";
  };
  cidr = {
    pname = "cidr";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "bschaatsbergen";
      repo = "cidr";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-8Tf7He7pY5A5UqpQ9lwJTW8DC4qBu0AEuGOXHpYo6bQ=";
    };
  };
  clashctl = {
    pname = "clashctl";
    version = "0.3.3";
    src = fetchFromGitHub {
      owner = "George-Miao";
      repo = "clashctl";
      rev = "0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-7XVMtl6yFxT9fy205sZL8eJ711NXdmYIMFVBbF0RoPc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./clashctl-0.3.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  classifier = {
    pname = "classifier";
    version = "09e958baeedeb6eed0fb1e048ed820888c5dbb84";
    src = fetchFromGitHub {
      owner = "bhrigu123";
      repo = "classifier";
      rev = "09e958baeedeb6eed0fb1e048ed820888c5dbb84";
      fetchSubmodules = false;
      sha256 = "sha256-nj+PlZpz8M2lvxsEa8RulWEb+aGN7ez7uF+iM9IhGKQ=";
    };
    date = "2017-05-23";
  };
  climage = {
    pname = "climage";
    version = "0.2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/c/climage/climage-0.2.2.tar.gz";
      sha256 = "sha256-5hFrL189MTrbCFZlfv5KbRGeIhjN7yPCipk9lLhxq44=";
    };
  };
  cloneit = {
    pname = "cloneit";
    version = "6198556e810d964cc5938c446ef42fc21b55fe0b";
    src = fetchFromGitHub {
      owner = "alok8bb";
      repo = "cloneit";
      rev = "6198556e810d964cc5938c446ef42fc21b55fe0b";
      fetchSubmodules = false;
      sha256 = "sha256-RP0/kquAlSwRMeB6cjvS5JB9qfdkT8IKLVxaxrmzJ+0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cloneit-6198556e810d964cc5938c446ef42fc21b55fe0b/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2024-07-28";
  };
  cmdx = {
    pname = "cmdx";
    version = "v1.7.4";
    src = fetchurl {
      url = "https://github.com/suzuki-shunsuke/cmdx/releases/download/v1.7.4/cmdx_linux_amd64.tar.gz";
      sha256 = "sha256-z2tkKCkXW9xk3xbQS3+qlTtoT0KQVXreS++bZh8/RFI=";
    };
  };
  code-radio-cli = {
    pname = "code-radio-cli";
    version = "v1.0.5";
    src = fetchFromGitHub {
      owner = "JasonWei512";
      repo = "code-radio-cli";
      rev = "v1.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-H2mnMWMJcFZIWHRz4QzM7ZwfbJ0N/ycu4g2W7187E3A=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./code-radio-cli-v1.0.5/Cargo.lock;
      outputHashes = {

      };
    };
  };
  comigo = {
    pname = "comigo";
    version = "v0.9.11.1";
    src = fetchurl {
      url = "https://github.com/yumenaka/comigo/releases/download/v0.9.11.1/comi_v0.9.11_Linux_x86_64.tar.gz";
      sha256 = "sha256-2mVp3TwcdS9HB9vzz3MshK0HFJr5DIUlTDsegjlkw6Q=";
    };
  };
  complate = {
    pname = "complate";
    version = "0.14.0";
    src = fetchFromGitHub {
      owner = "replicadse";
      repo = "complate";
      rev = "0.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-X/uFpfHz0DCj0KFR2IcV6vhSkP0sSX0MsEBDmw0nan0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./complate-0.14.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  compose2nix = {
    pname = "compose2nix";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "aksiksi";
      repo = "compose2nix";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-rFnnbRVVv/N5021Al3vmjFAui1cTp8NBZDBNQo8CsXM=";
    };
  };
  config-file-validator = {
    pname = "config-file-validator";
    version = "v1.7.1";
    src = fetchFromGitHub {
      owner = "Boeing";
      repo = "config-file-validator";
      rev = "v1.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-WloMMnSxJUKfRHodLYEbxD2adOfRcu7aOud1ziZaUfY=";
    };
  };
  convfmt = {
    pname = "convfmt";
    version = "0.1.6";
    src = fetchFromGitHub {
      owner = "oriontvv";
      repo = "convfmt";
      rev = "0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-k2Qj6/dllArP6jIDyiHA7luudsdQgipZMYY6Hm5hqEs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./convfmt-0.1.6/Cargo.lock;
      outputHashes = {

      };
    };
  };
  corgi = {
    pname = "corgi";
    version = "0.2.4";
    src = fetchurl {
      url = "https://github.com/junyu-w/corgi/releases/download/v0.2.4/corgi_v0.2.4_linux_64-bit.tar.gz";
      sha256 = "sha256-DYYU02p6/rO6sY1B1BKI/h+IhSdCRQl+YTuor5+dl1M=";
    };
  };
  "ctrl-z.fish" = {
    pname = "ctrl-z.fish";
    version = "82448a44c9ba8e2d8a5c7394184e977f5f76e0b8";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "ctrl-z.fish";
      rev = "82448a44c9ba8e2d8a5c7394184e977f5f76e0b8";
      fetchSubmodules = false;
      sha256 = "sha256-JXy5y0FXLvgdqgkwqGFkv2aqV40AHWRq9mq/EhsTEyo=";
    };
    date = "2024-10-20";
  };
  curd = {
    pname = "curd";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "Wraient";
      repo = "curd";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-202Cb/b2PomoKAGrVf8UofTt8JQq0puV/xRAVUu+GqQ=";
    };
  };
  datadash = {
    pname = "datadash";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "keithknott26";
      repo = "datadash";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-WEB1MVG2aGvKnkMAgF7nxKHgA05VRJONoNdsBpXM2Wk=";
    };
  };
  devdocs-vim = {
    pname = "devdocs-vim";
    version = "ae7e029c1fc1d89c3a18f1244a6747ad3ddfc271";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "devdocs.vim";
      rev = "ae7e029c1fc1d89c3a18f1244a6747ad3ddfc271";
      fetchSubmodules = false;
      sha256 = "sha256-Q+e9pwvmNfBPewT3mfAHH5fZh+VVY7mXELbMI41WkqY=";
    };
    date = "2024-10-18";
  };
  dext = {
    pname = "dext";
    version = "03691dfc96c99a5dddc7171bae5d19739aac2b82";
    src = fetchFromGitHub {
      owner = "AfzGit";
      repo = "dext";
      rev = "03691dfc96c99a5dddc7171bae5d19739aac2b82";
      fetchSubmodules = false;
      sha256 = "sha256-xR6r+zAGDcmwBDPu/euni9qzYtugq8HxSfBoXuu7qnM=";
    };
    date = "2023-04-23";
  };
  diffnav = {
    pname = "diffnav";
    version = "v0.2.8";
    src = fetchFromGitHub {
      owner = "dlvhdr";
      repo = "diffnav";
      rev = "v0.2.8";
      fetchSubmodules = false;
      sha256 = "sha256-xZAi/Ky1RjOxjhQKHvozaPTqDPcrGfhMemGWzi7WyW4=";
    };
  };
  dlorg = {
    pname = "dlorg";
    version = "d4966d6d1e4384e8f6c7f33b473a24cf6cdd0617";
    src = fetchFromGitHub {
      owner = "deepspeccode";
      repo = "dlorg";
      rev = "d4966d6d1e4384e8f6c7f33b473a24cf6cdd0617";
      fetchSubmodules = false;
      sha256 = "sha256-yu+m1HGFSex/S1ik47ee8tGCFjTDkgfHqMmVNW2lQgY=";
    };
    date = "2024-08-18";
  };
  dnspyre = {
    pname = "dnspyre";
    version = "v3.5.0";
    src = fetchFromGitHub {
      owner = "Tantalor93";
      repo = "dnspyre";
      rev = "v3.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-bcBVpCX7n0IpdLn5VqG+1yDiH5Yy8Kn9UGd8KVwDYhI=";
    };
  };
  docker-alist = {
    pname = "docker-alist";
    version = "v3.39.1";
    src = dockerTools.pullImage {
      imageName = "xhofe/alist-aria2";
      imageDigest = "sha256:2d547feef90c6e944c71d34fa6065c534ca8853eed750dbbbbbb0b477b5e1b51";
      sha256 = "sha256-Va6Ufelujtv7J2l5tIse+vwlDuom/zUblS2QuJt1J2A=";
      finalImageTag = "v3.39.1";
    };
  };
  docker-flaresolverr = {
    pname = "docker-flaresolverr";
    version = "v3.3.21";
    src = dockerTools.pullImage {
      imageName = "flaresolverr/flaresolverr";
      imageDigest = "sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b";
      sha256 = "sha256-unGzkgDG5RvVPz+cHdNqizBjEf9FCHSMwi7PbRgjETI=";
      finalImageTag = "v3.3.21";
    };
  };
  docker-qd = {
    pname = "docker-qd";
    version = "20240210";
    src = dockerTools.pullImage {
      imageName = "qdtoday/qd";
      imageDigest = "sha256:7d9a54588876203720d7638cd0ca5e25897d3c8993fcfa9f9c0c59a91cf8ed9f";
      sha256 = "sha256-vxZHuExbVwA4HyXzrXgogomxRg3EaHaEwBG1BH/gvnI=";
      finalImageTag = "20240210";
    };
  };
  docker-subconverter = {
    pname = "docker-subconverter";
    version = "0.9.0";
    src = dockerTools.pullImage {
      imageName = "tindy2013/subconverter";
      imageDigest = "sha256:41899af10188ce83f6359eacc3d12f33c74b423c35b37bcd09b686575e9e10ad";
      sha256 = "sha256-PiCD+jyQRhzbHKQeJxJiyUd+TZRG3OZHRkV97ITlI9w=";
      finalImageTag = "0.9.0";
    };
  };
  dra = {
    pname = "dra";
    version = "0.6.3";
    src = fetchFromGitHub {
      owner = "devmatteini";
      repo = "dra";
      rev = "0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-C+BEvRBm8f9rtcNQi86x4RHZiMsPl8dZNJToxG7MUxM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./dra-0.6.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  easyjump-vim = {
    pname = "easyjump-vim";
    version = "7be7e1b6e8000971d0f6ef9e8480f86094f56635";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "easyjump.vim";
      rev = "7be7e1b6e8000971d0f6ef9e8480f86094f56635";
      fetchSubmodules = false;
      sha256 = "sha256-SuvbOOp0G+V0X4G++HkiGO0SWaZvCMd7/Y8q9gWvUYE=";
    };
    date = "2024-06-06";
  };
  eg = {
    pname = "eg";
    version = "1.2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/eg/eg-1.2.2.tar.gz";
      sha256 = "sha256-jTdF7OsqTJFQexkjGTdHt66IiI5iV+uKrM996uKjAKc=";
    };
  };
  ehh = {
    pname = "ehh";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "lennardv2";
      repo = "ehh";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-mXDive5yHac2MdAsDrMsp0QzcrhnIS805yt7AkpXnwM=";
    };
  };
  eleventy = {
    pname = "eleventy";
    version = "v3.0.0";
    src = fetchFromGitHub {
      owner = "11ty";
      repo = "eleventy";
      rev = "v3.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-0xyVski+WTfTdYfNUBMKX4fnorGSsbi95WMR8ocSU2Q=";
    };
  };
  enhancd = {
    pname = "enhancd";
    version = "v2.5.1";
    src = fetchFromGitHub {
      owner = "babarot";
      repo = "enhancd";
      rev = "v2.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-kaintLXSfLH7zdLtcoZfVNobCJCap0S/Ldq85wd3krI=";
    };
  };
  envset = {
    pname = "envset";
    version = "v0.1.17";
    src = fetchFromGitHub {
      owner = "schpet";
      repo = "envset";
      rev = "v0.1.17";
      fetchSubmodules = false;
      sha256 = "sha256-d2cStBjI2heQyP0cODRYQPvZJ4frFw7w5lsSdyvi5y8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./envset-v0.1.17/Cargo.lock;
      outputHashes = {

      };
    };
  };
  facad = {
    pname = "facad";
    version = "v2.18.0";
    src = fetchFromGitHub {
      owner = "yellow-footed-honeyguide";
      repo = "facad";
      rev = "v2.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-0Z8CDHLWAighRhcVZIlSQAWb9CpeMpmw9ASy9ACep4Q=";
    };
  };
  fast-anime = {
    pname = "fast-anime";
    version = "v2.7.3";
    src = fetchFromGitHub {
      owner = "Benex254";
      repo = "FastAnime";
      rev = "v2.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-5e9x90IpgBm1C1JKJ8SmfKwuqmmBgqBx7vIRZKMtLig=";
    };
  };
  fc-fish = {
    pname = "fc-fish";
    version = "9457a9c47391ff712696bbef0e4a109de2a653d1";
    src = fetchFromGitHub {
      owner = "lengyijun";
      repo = "fc-fish";
      rev = "9457a9c47391ff712696bbef0e4a109de2a653d1";
      fetchSubmodules = false;
      sha256 = "sha256-DQQofY5FPdy5kWctlKmi2SRTH7zL9ZpBdrdMx+iX+dA=";
    };
    date = "2023-04-07";
  };
  fetch = {
    pname = "fetch";
    version = "v0.4.6";
    src = fetchFromGitHub {
      owner = "gruntwork-io";
      repo = "fetch";
      rev = "v0.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-otHsP3Y8FZqB9omNYuM7gZfolqFiDwlXLEXeJB3pefI=";
    };
  };
  fgit = {
    pname = "fgit";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "fastgh";
      repo = "fgit";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-27GZp1qd0pJg9usIxj8wl1Dz+4ZC0273bb1tJ4Hhc9s=";
    };
  };
  fifc = {
    pname = "fifc";
    version = "e953fcd521f34651d4eabedcc08cfdef7945b31d";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fifc";
      rev = "e953fcd521f34651d4eabedcc08cfdef7945b31d";
      fetchSubmodules = false;
      sha256 = "sha256-VmeVVwX5/rPZr98vaitvw6bqcZgaBNc+mEYkDRjFBXA=";
    };
    date = "2024-10-16";
  };
  fingerpaint = {
    pname = "fingerpaint";
    version = "v1.2.7";
    src = fetchFromGitHub {
      owner = "Wazzaps";
      repo = "fingerpaint";
      rev = "v1.2.7";
      fetchSubmodules = false;
      sha256 = "sha256-BPpSAaWLmF0JkMijx7pI87tzO/rcjTryxdI2ekTavRY=";
    };
  };
  fish-abbreviation-tips = {
    pname = "fish-abbreviation-tips";
    version = "8ed76a62bb044ba4ad8e3e6832640178880df485";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fish-abbreviation-tips";
      rev = "8ed76a62bb044ba4ad8e3e6832640178880df485";
      fetchSubmodules = false;
      sha256 = "sha256-F1t81VliD+v6WEWqj1c1ehFBXzqLyumx5vV46s/FZRU=";
    };
    date = "2023-01-23";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  fish-color-scheme-switcher = {
    pname = "fish-color-scheme-switcher";
    version = "9f9720dbf06cd4690e6b78c3daa897ae05f792bb";
    src = fetchFromGitHub {
      owner = "h-matsuo";
      repo = "fish-color-scheme-switcher";
      rev = "9f9720dbf06cd4690e6b78c3daa897ae05f792bb";
      fetchSubmodules = false;
      sha256 = "sha256-9VOgPxCNfuyy9DlicaN6W2EQ6OQFq/z8oSx1l9RitP4=";
    };
    date = "2022-02-21";
  };
  fish-colored-man = {
    pname = "fish-colored-man";
    version = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-colored-man";
      rev = "1ad8fff696d48c8bf173aa98f9dff39d7916de0e";
      fetchSubmodules = false;
      sha256 = "sha256-uoZ4eSFbZlsRfISIkJQp24qPUNqxeD0JbRb/gVdRYlA=";
    };
    date = "2021-07-16";
  };
  fish-done = {
    pname = "fish-done";
    version = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
      fetchSubmodules = false;
      sha256 = "sha256-DMIRKRAVOn7YEnuAtz4hIxrU93ULxNoQhW6juxCoh4o=";
    };
    date = "2024-04-11";
  };
  fish-f = {
    pname = "fish-f";
    version = "6099f3a4b5d148674106a264fffc84dd5a4dfe35";
    src = fetchFromGitHub {
      owner = "gokulsoumya";
      repo = "f";
      rev = "6099f3a4b5d148674106a264fffc84dd5a4dfe35";
      fetchSubmodules = false;
      sha256 = "sha256-NSp4TCWjsVboT0xI+5zbWx2xr+S4go4zbR6nyxbUz8g=";
    };
    date = "2021-05-09";
  };
  fish-fzf = {
    pname = "fish-fzf";
    version = "479fa67d7439b23095e01b64987ae79a91a4e283";
    src = fetchFromGitHub {
      owner = "jethrokuan";
      repo = "fzf";
      rev = "479fa67d7439b23095e01b64987ae79a91a4e283";
      fetchSubmodules = false;
      sha256 = "sha256-28QW/WTLckR4lEfHv6dSotwkAKpNJFCShxmKFGQQ1Ew=";
    };
    date = "2021-05-12";
  };
  fish-gitnow = {
    pname = "fish-gitnow";
    version = "0cf3c89209305779e82d3b5cb956cf8b54025dd6";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "gitnow";
      rev = "0cf3c89209305779e82d3b5cb956cf8b54025dd6";
      fetchSubmodules = false;
      sha256 = "sha256-vNYUMzgBvPxHpeybhzBvyVL5RhM6qZlFtk3uZiiDvf8=";
    };
    date = "2024-10-12";
  };
  fish-sponge = {
    pname = "fish-sponge";
    version = "384299545104d5256648cee9d8b117aaa9a6d7be";
    src = fetchFromGitHub {
      owner = "meaningful-ooo";
      repo = "sponge";
      rev = "384299545104d5256648cee9d8b117aaa9a6d7be";
      fetchSubmodules = false;
      sha256 = "sha256-MdcZUDRtNJdiyo2l9o5ma7nAX84xEJbGFhAVhK+Zm1w=";
    };
    date = "2022-10-05";
  };
  fishbang = {
    pname = "fishbang";
    version = "0b5ef82ead524a7dd0da5760d8f677b02b35f654";
    src = fetchFromGitHub {
      owner = "brewingweasel";
      repo = "fishbang";
      rev = "0b5ef82ead524a7dd0da5760d8f677b02b35f654";
      fetchSubmodules = false;
      sha256 = "sha256-AbFSUz2C4ru0jclF60JOpzf7xWo0ffahEsM5hkNNtGw=";
    };
    date = "2023-08-04";
  };
  flatpak-compose = {
    pname = "flatpak-compose";
    version = "0.4.0";
    src = fetchFromGitHub {
      owner = "faan11";
      repo = "flatpak-compose";
      rev = "0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-BpsEelrtb5yWRiP70/wIsrYWS2aFl6tUFbQ8ChTrj+s=";
    };
  };
  focus = {
    pname = "focus";
    version = "v1.4.3";
    src = fetchFromGitHub {
      owner = "ayoisaiah";
      repo = "focus";
      rev = "v1.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-p9gTFUYHdyOY2EFT/ZmBHT7dRNm64s/3ExUXG7bfQ70=";
    };
  };
  friendly-snippets = {
    pname = "friendly-snippets";
    version = "de8fce94985873666bd9712ea3e49ee17aadb1ed";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "de8fce94985873666bd9712ea3e49ee17aadb1ed";
      fetchSubmodules = false;
      sha256 = "sha256-H94Ryad0ZsSg/gioUgW+7sowij7GgtEUMNFi1IOZAys=";
    };
    date = "2024-10-07";
  };
  fzf-help = {
    pname = "fzf-help";
    version = "v2.3.0";
    src = fetchFromGitHub {
      owner = "BartSte";
      repo = "fzf-help";
      rev = "v2.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-gM+5TQYJp69OOusM+6CO4EXtjexGlfx4rzZFo/+8vv0=";
    };
  };
  fzf-kill = {
    pname = "fzf-kill";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "Zeioth";
      repo = "fzf-kill";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-Aa+jqcavFber+tAWUqPgV87sKKZS+5rGeJLS7RoYGLA=";
    };
  };
  game_2048_tui = {
    pname = "game_2048_tui";
    version = "v0.0.2";
    src = fetchFromGitHub {
      owner = "WanderHuang";
      repo = "game-2048-tui";
      rev = "v0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-/O548IEhGYSOSIG/xTGCi+P75poM5KY2AYW6lXRCtF0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./game_2048_tui-v0.0.2/Cargo.lock;
      outputHashes = {

      };
    };
  };
  gaze = {
    pname = "gaze";
    version = "v1.1.6";
    src = fetchFromGitHub {
      owner = "wtetsu";
      repo = "gaze";
      rev = "v1.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-5i61kaonTCVHCYwJ0C+bihxNTNNwyQ2XWSI85RMm2Hk=";
    };
  };
  geminicommit = {
    pname = "geminicommit";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "tfkhdyt";
      repo = "geminicommit";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-wfSYR458uK47JtsiNrD3f6bD5HcfFf5WxlKdx8oLidY=";
    };
  };
  geoip2fast = {
    pname = "geoip2fast";
    version = "1.2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/g/geoip2fast/geoip2fast-1.2.2.tar.gz";
      sha256 = "sha256-OIFXAM7f6xl9UbS4czsNT3lls23hUUfBJVJxJPi0XWs=";
    };
  };
  gg = {
    pname = "gg";
    version = "14e45a8e946eb7a04ebacc07e3a1f1f4235b1cd8";
    src = fetchFromGitHub {
      owner = "qw3rtman";
      repo = "gg";
      rev = "14e45a8e946eb7a04ebacc07e3a1f1f4235b1cd8";
      fetchSubmodules = false;
      sha256 = "sha256-+8WpnY9oBdDQ4fUj/xtsrx2w6LCfZIQjex+6BEk5qlk=";
    };
    date = "2022-12-27";
  };
  gh-branch = {
    pname = "gh-branch";
    version = "7ed0aff7601dc4162e0cac8835ecd73409d8a009";
    src = fetchFromGitHub {
      owner = "mislav";
      repo = "gh-branch";
      rev = "7ed0aff7601dc4162e0cac8835ecd73409d8a009";
      fetchSubmodules = false;
      sha256 = "sha256-yiRSXU/jLi067i+gBb3cEHTOuo+w3oEVsGL0NN6shl8=";
    };
    date = "2023-12-06";
  };
  gh-cp = {
    pname = "gh-cp";
    version = "58afdf5b5e1acfe71fce2390f6431003505ae0aa";
    src = fetchFromGitHub {
      owner = "mislav";
      repo = "gh-cp";
      rev = "58afdf5b5e1acfe71fce2390f6431003505ae0aa";
      fetchSubmodules = false;
      sha256 = "sha256-Ih3Wit0nnB8PrgbeZEuhTNVPCrwMWBmKMJSGmgLIrVY=";
    };
    date = "2021-11-08";
  };
  gh-screensaver = {
    pname = "gh-screensaver";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "vilmibm";
      repo = "gh-screensaver";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-MqwaqXGP4E+46vpgftZ9bttmMyENuojBnS6bWacmYLE=";
    };
  };
  gh-stars = {
    pname = "gh-stars";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "aymanbagabas";
      repo = "gh-stars";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-p1GLENa6UIXcasXbJtj5wpS2nMnJzT7V7k3pwfJOano=";
    };
  };
  gif-progress = {
    pname = "gif-progress";
    version = "release-fix-not-moving-progress-bar";
    src = fetchurl {
      url = "https://github.com/nwtgck/gif-progress/releases/download/release-fix-not-moving-progress-bar/gif-progress-linux-amd64.tar.gz";
      sha256 = "sha256-dpPWs7S/iRUe2U91DN/+T/HyKtRZOl9FsV7ZulaqP40=";
    };
  };
  git-cal = {
    pname = "git-cal";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "k4rthik";
      repo = "git-cal";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-fzzcxGre3YebvFrSRrul2L73mfQF/4ubsGVSPFzUSSM=";
    };
  };
  git-grab = {
    pname = "git-grab";
    version = "3.0.0";
    src = fetchFromGitHub {
      owner = "wezm";
      repo = "git-grab";
      rev = "3.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-MsJDfmWU6LyK7M0LjYQufIpKmtS4f2hgo4Yi/x1HsrU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./git-grab-3.0.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  git-heatgrid = {
    pname = "git-heatgrid";
    version = "2263ce34d2929652e6cfe31fe076577dfcefd168";
    src = fetchFromGitHub {
      owner = "denshakhov";
      repo = "git-heatgrid";
      rev = "2263ce34d2929652e6cfe31fe076577dfcefd168";
      fetchSubmodules = false;
      sha256 = "sha256-nBiZfwiWmwM0a839NaDsCouJtL2d0HYHIZ+FFGrmzjM=";
    };
    date = "2024-05-13";
  };
  git-ink = {
    pname = "git-ink";
    version = "1.0.1";
    src = fetchFromGitHub {
      owner = "davidosomething";
      repo = "git-ink";
      rev = "1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-OiAajjMXyLezEXNxmHnwZZBP0lZEYmRGUkxh6xEoThw=";
    };
  };
  git-issue = {
    pname = "git-issue";
    version = "d056998566d30235072b97982756ff607e9ecce9";
    src = fetchFromGitHub {
      owner = "dspinellis";
      repo = "git-issue";
      rev = "d056998566d30235072b97982756ff607e9ecce9";
      fetchSubmodules = false;
      sha256 = "sha256-VYMIgJRcXKlhX05tfILA8dB8x3lcR6nX6vdls79cAgA=";
    };
    date = "2024-05-17";
  };
  git-lens-vim = {
    pname = "git-lens-vim";
    version = "6c22e05c3e43bbe6e2cdc02bbc2978886e50e27c";
    src = fetchFromGitHub {
      owner = "Eliot00";
      repo = "git-lens.vim";
      rev = "6c22e05c3e43bbe6e2cdc02bbc2978886e50e27c";
      fetchSubmodules = false;
      sha256 = "sha256-YZdiYB1YJFv/oCJSC/Ld0QBDTp+mqItwIWURbbN9yCw=";
    };
    date = "2024-04-14";
  };
  git-messenger-vim = {
    pname = "git-messenger-vim";
    version = "edc603d4cda7894a743e383e16c638e206d03148";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "git-messenger.vim";
      rev = "edc603d4cda7894a743e383e16c638e206d03148";
      fetchSubmodules = false;
      sha256 = "sha256-SgivafrSdql6yG0Nj2+zo0dWE7x3YigzD6kJRrucPC0=";
    };
    date = "2024-09-05";
  };
  git-mux = {
    pname = "git-mux";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "benelan";
      repo = "git-mux";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-rqWLnp8OaNFaM7jfplfsnVotkBpDhCfIVOk8W83GjPM=";
    };
  };
  git-of-theseus = {
    pname = "git-of-theseus";
    version = "961bda027ffa9fcd8bbe99d5b8809cc0eaa86464";
    src = fetchFromGitHub {
      owner = "erikbern";
      repo = "git-of-theseus";
      rev = "961bda027ffa9fcd8bbe99d5b8809cc0eaa86464";
      fetchSubmodules = false;
      sha256 = "sha256-FZXLJbximJWrDyuRril6whlOYWppGLns3k8sDNRmOuI=";
    };
    date = "2023-11-25";
  };
  git-playback = {
    pname = "git-playback";
    version = "0d4a51993b8a1b58579964e883fd344f6b92763b";
    src = fetchFromGitHub {
      owner = "jianli";
      repo = "git-playback";
      rev = "0d4a51993b8a1b58579964e883fd344f6b92763b";
      fetchSubmodules = false;
      sha256 = "sha256-lHqr+4dFFbktTI1J4Qu3t3BmV6xA32H2o5yOgaJJcNs=";
    };
    date = "2016-03-22";
  };
  git-spend = {
    pname = "git-spend";
    version = "1.2.1";
    src = fetchFromGitHub {
      owner = "Goutte";
      repo = "git-spend";
      rev = "1.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-4bR5CVM1zTSdLiHyigYgmvpO1VDM6rteeBHuADXq2pk=";
    };
  };
  git-stats = {
    pname = "git-stats";
    version = "3.2.0";
    src = fetchFromGitHub {
      owner = "IonicaBizau";
      repo = "git-stats";
      rev = "3.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-LhsesKHPggV7asOcJCPS/o4O5jP4WVlSiDXIWlyj8Yc=";
    };
  };
  git-sumi = {
    pname = "git-sumi";
    version = "v0.0.9";
    src = fetchFromGitHub {
      owner = "welpo";
      repo = "git-sumi";
      rev = "v0.0.9";
      fetchSubmodules = false;
      sha256 = "sha256-ZSpQJeiGn6J8G/35PTW6pRzPhTRW1Op3gakx/yXB3Zc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./git-sumi-v0.0.9/Cargo.lock;
      outputHashes = {

      };
    };
  };
  git-toolbelt = {
    pname = "git-toolbelt";
    version = "v1.9.3";
    src = fetchFromGitHub {
      owner = "nvie";
      repo = "git-toolbelt";
      rev = "v1.9.3";
      fetchSubmodules = false;
      sha256 = "sha256-ANqv/iIDUyy2G4pKSw+2sutMEA0WhPN3OKfPTm5lwDU=";
    };
  };
  gitcs = {
    pname = "gitcs";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "knbr13";
      repo = "gitcs";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-IyhVVRTKftZIzqMH5pBUMLPIk8bk0rVAxPKD6bABP68=";
    };
  };
  github-dlr = {
    pname = "github-dlr";
    version = "0.1.2";
    src = fetchFromGitHub {
      owner = "rocktimsaikia";
      repo = "github-dlr";
      rev = "0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-vXLrX3gWx1K77TA79dOxaC2U59ZWpS0PGQnUHIb+BxI=";
    };
  };
  gitty = {
    pname = "gitty";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "worlpaker";
      repo = "gitty";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-TVNZSKg/BiQAOy3Natw3WrvDUdv7SwpG+I4P/i5O/WA=";
    };
  };
  gogitmoji = {
    pname = "gogitmoji";
    version = "v1.1.5";
    src = fetchFromGitHub {
      owner = "jamesdobson";
      repo = "gogitmoji";
      rev = "v1.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-mXJga9Y1ZA7htzCEyMIuyj2oMjyFOj/Z/2U/yzLfQPw=";
    };
  };
  goji = {
    pname = "goji";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "muandane";
      repo = "goji";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-By4BQN7ftja4VMdxaksbQqtUcgjaQhF0ORUWZspmho8=";
    };
  };
  goodls = {
    pname = "goodls";
    version = "v2.0.5";
    src = fetchFromGitHub {
      owner = "tanaikech";
      repo = "goodls";
      rev = "v2.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-SrDDRQvogsYtdp8El/NOeeTOg0RKqaR3m7dq4Lhqrps=";
    };
  };
  grip-grab = {
    pname = "grip-grab";
    version = "v0.5.5";
    src = fetchFromGitHub {
      owner = "alexpasmantier";
      repo = "grip-grab";
      rev = "v0.5.5";
      fetchSubmodules = false;
      sha256 = "sha256-T3tla6Gf9lUQ+F8D57glzmfsmuX5FV806zuKQxYt2lw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./grip-grab-v0.5.5/Cargo.lock;
      outputHashes = {

      };
    };
  };
  gtm = {
    pname = "gtm";
    version = "v1.3.5";
    src = fetchurl {
      url = "https://github.com/git-time-metric/gtm/releases/download/v1.3.5/gtm.v1.3.5.linux.tar.gz";
      sha256 = "sha256-e0Pk06MCCSnh4bqK94xh4C37eooK9Vj70ndGqey1B0M=";
    };
  };
  gtm-vim-plugin = {
    pname = "gtm-vim-plugin";
    version = "ebd33f7d01a7ac9b2695f71b1136d6b89a0d5d44";
    src = fetchFromGitHub {
      owner = "git-time-metric";
      repo = "gtm-vim-plugin";
      rev = "ebd33f7d01a7ac9b2695f71b1136d6b89a0d5d44";
      fetchSubmodules = false;
      sha256 = "sha256-rAbcwJ6Frgj6s1lPP0iUVJn39w0vzCvg2ImOaQD2+2w=";
    };
    date = "2017-04-16";
  };
  gw = {
    pname = "gw";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "daniel7grant";
      repo = "gw";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-hJf2u3CnkZ2kysEksdmxfLX+J6GK5Qd/Ntr2cHKphXU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./gw-v0.4.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  hatsune-miku-windows-linux-cursors = {
    pname = "hatsune-miku-windows-linux-cursors";
    version = "1.2.4";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "1.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-PB8b/hGH5HtCEPOVPTtObWYOj520TqBpoxavA8Tfx2s=";
    };
  };
  hexpatch = {
    pname = "hexpatch";
    version = "v1.9.3";
    src = fetchFromGitHub {
      owner = "Etto48";
      repo = "HexPatch";
      rev = "v1.9.3";
      fetchSubmodules = false;
      sha256 = "sha256-UhenCrCVUL6mdEpmTU4e1sIHBS8QXVRtKTMlLah56Zs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./hexpatch-v1.9.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  hl = {
    pname = "hl";
    version = "v0.29.9";
    src = fetchurl {
      url = "https://github.com/pamburus/hl/releases/download/v0.29.9/hl-linux-x86_64-gnu.tar.gz";
      sha256 = "sha256-JKdH6jR4c2IOdWM+Yq37ltN383hQlE99NYW/OpeiO3g=";
    };
  };
  hledger-fmt = {
    pname = "hledger-fmt";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "mondeja";
      repo = "hledger-fmt";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-LAlI/QFrKJTB1fDuNSOrf1u5nB1w3vNAYixYiUnYg0o=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./hledger-fmt-v0.2.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  hssp = {
    pname = "hssp";
    version = "a08b37f4faca8b4269531be375c046f9beede0a0";
    src = fetchFromGitHub {
      owner = "sterchelen";
      repo = "hssp";
      rev = "a08b37f4faca8b4269531be375c046f9beede0a0";
      fetchSubmodules = false;
      sha256 = "sha256-y6k2Jcx6NZKU4i7OghWPlqEW/gZkDJtw5Rhqx+7SRyU=";
    };
    date = "2023-02-09";
  };
  hypergrep = {
    pname = "hypergrep";
    version = "0.1.1";
    src = fetchurl {
      url = "https://github.com/p-ranav/hypergrep/releases/download/v0.1.1/hg_0.1.1.zip";
      sha256 = "sha256-TfxEO2rhOvDmtUJn/xTDSOBOWUkJViUM6iR4QBsXJ5s=";
    };
  };
  images-upload-cli = {
    pname = "images-upload-cli";
    version = "v3.0.4";
    src = fetchFromGitHub {
      owner = "DeadNews";
      repo = "images-upload-cli";
      rev = "v3.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-UHXhudNqyL/efA+7D2BZYsKPHVJ5/ObTH6gEnOn/+bI=";
    };
  };
  impala = {
    pname = "impala";
    version = "v0.2.3";
    src = fetchFromGitHub {
      owner = "pythops";
      repo = "Impala";
      rev = "v0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-4LQmM4VTW3ykh6eDWKxBe3jxlJphgAytgeaQZNwivsQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./impala-v0.2.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  jalm = {
    pname = "jalm";
    version = "f1e79605af1b4852b2a5dbfcc4674a5c14fc551d";
    src = fetchFromGitHub {
      owner = "neelkarma";
      repo = "jalm";
      rev = "f1e79605af1b4852b2a5dbfcc4674a5c14fc551d";
      fetchSubmodules = false;
      sha256 = "sha256-xwB6IXQX4bch+j+VhWicEz4MIsdjld29q0CJZvAhulI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./jalm-f1e79605af1b4852b2a5dbfcc4674a5c14fc551d/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2022-10-08";
  };
  jerry = {
    pname = "jerry";
    version = "e8d15983a90a0be583419637b46723192ef5c1d3";
    src = fetchFromGitHub {
      owner = "justchokingaround";
      repo = "Jerry";
      rev = "e8d15983a90a0be583419637b46723192ef5c1d3";
      fetchSubmodules = false;
      sha256 = "sha256-VEb9mrAXGmD9EYzU/W/E7sPoWw4eMBd2q0n2s8dqLls=";
    };
    date = "2024-09-29";
  };
  jtbl = {
    pname = "jtbl";
    version = "v1.6.0";
    src = fetchFromGitHub {
      owner = "kellyjonbrazil";
      repo = "Jtbl";
      rev = "v1.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-ILQwUpjNueaYR5hxOWd5kZSPhVoFnnS2FcttyKSTPr8=";
    };
  };
  kbgrep = {
    pname = "kbgrep";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "pcrockett";
      repo = "kbgrep";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-dDGOrfEiihFtHeAkVaeMr9rzVqBvwtSE6KqWHjVrEWg=";
    };
  };
  kdtree = {
    pname = "kdtree";
    version = "0.16";
    src = fetchurl {
      url = "https://pypi.org/packages/source/k/kdtree/kdtree-0.16.tar.gz";
      sha256 = "sha256-OG32x4FqBeD6uXTjA135RPme9otWFfSkFncTkeM9dTQ=";
    };
  };
  koji = {
    pname = "koji";
    version = "2.2.0";
    src = fetchFromGitHub {
      owner = "cococonscious";
      repo = "Koji";
      rev = "2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-2kBjHX7izo4loJ8oyPjE9FtCvUODC3Sm4T8ETIdeGZM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./koji-2.2.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  lain = {
    pname = "lain";
    version = "88f5a8abd2649b348ffec433a24a263b37f122c0";
    src = fetchFromGitHub {
      owner = "lcpz";
      repo = "lain";
      rev = "88f5a8abd2649b348ffec433a24a263b37f122c0";
      fetchSubmodules = false;
      sha256 = "sha256-MH/aiYfcO3lrcuNbnIu4QHqPq25LwzTprOhEJUJBJ7I=";
    };
    date = "2023-01-12";
  };
  lite-xl-vibe = {
    pname = "lite-xl-vibe";
    version = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
    src = fetchFromGitHub {
      owner = "eugenpt";
      repo = "lite-xl-vibe";
      rev = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
      fetchSubmodules = false;
      sha256 = "sha256-JSTYmfiy0BeBCVXxOLkXf9SaxPTWrsAam2ZQKn0hk4M=";
    };
    date = "2023-10-31";
  };
  lobster = {
    pname = "lobster";
    version = "v4.3.0";
    src = fetchFromGitHub {
      owner = "justchokingaround";
      repo = "Lobster";
      rev = "v4.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-ch91LYKs6MswTC08Xi8VcIxooWvDprGuIn0B2Yo3ufo=";
    };
  };
  lobtui = {
    pname = "lobtui";
    version = "v0.3";
    src = fetchFromGitHub {
      owner = "pythops";
      repo = "lobtui";
      rev = "v0.3";
      fetchSubmodules = false;
      sha256 = "sha256-Vc6fh0XbSYNCQWosP7cOfphJin6Z5AJdcfSNdd38cKs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./lobtui-v0.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  lookatme = {
    pname = "lookatme";
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "d0c-s4vage";
      repo = "lookatme";
      rev = "v2.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-mn28OLIlxk97aDow1dTBsMRxVTkCqVeiAtrlyh8zJTg=";
    };
  };
  lssh = {
    pname = "lssh";
    version = "v0.6.13";
    src = fetchFromGitHub {
      owner = "blacknon";
      repo = "lssh";
      rev = "v0.6.13";
      fetchSubmodules = false;
      sha256 = "sha256-0dxkFOXNaOmIjKuhmTsfQmS+Nf8QiM5txmI8p1XcqTQ=";
    };
  };
  machma = {
    pname = "machma";
    version = "9ab93d72e36fe2cbb15af37c914605212ac28642";
    src = fetchFromGitHub {
      owner = "fd0";
      repo = "machma";
      rev = "9ab93d72e36fe2cbb15af37c914605212ac28642";
      fetchSubmodules = false;
      sha256 = "sha256-VmyWAsWIe6dhLq7UEit389v3fnQqRwZYk5gY6gj6Q3M=";
    };
    date = "2021-01-02";
  };
  makedown = {
    pname = "makedown";
    version = "4418bd111b4f86d0e35038d45332153c263c2d06";
    src = fetchFromGitHub {
      owner = "tzador";
      repo = "makedown";
      rev = "4418bd111b4f86d0e35038d45332153c263c2d06";
      fetchSubmodules = false;
      sha256 = "sha256-6oZawRzQ/Q++ydqDZ2CfYyxLz9xQO8IdB/qR5JgmD8A=";
    };
    date = "2024-10-18";
  };
  manga-tui = {
    pname = "manga-tui";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "josueBarretogit";
      repo = "manga-tui";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-Se0f5jfYBmvemrYRKduDr1yT3fB2wfQP1fDpa/qrYlI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./manga-tui-v0.4.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  mdformat-config = {
    pname = "mdformat-config";
    version = "0.2.1";
    src = fetchFromGitHub {
      owner = "hukkin";
      repo = "mdformat-config";
      rev = "0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-v6xtU6qZMhUnWFcCJOm9CcmLe6nKxmV9qGDM8o8MPe4=";
    };
  };
  mdsf = {
    pname = "mdsf";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/hougesen/mdsf/releases/download/v0.3.0/mdsf-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-l8NCTQwBOC6FfUT7sYDZGNgjEQj8GXi6IctApvz+ZdY=";
    };
  };
  mdtt = {
    pname = "mdtt";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "szktkfm";
      repo = "mdtt";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-OFS/ZhXdvdmlpfCNutsvlhMv1krFlx4Xju8RSl3GS2s=";
    };
  };
  mergiraf = {
    pname = "mergiraf";
    version = "1ba7d8dd1e92583e0fadc2a25fc1cfecfce5e13e";
    src = fetchgit {
      url = "https://codeberg.org/mergiraf/mergiraf";
      rev = "1ba7d8dd1e92583e0fadc2a25fc1cfecfce5e13e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ChOYmrRfkyfVm4NylJqUIz1vEpoVMDQPsKZCm1GJjE8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./mergiraf-1ba7d8dd1e92583e0fadc2a25fc1cfecfce5e13e/Cargo.lock;
      outputHashes = {
        "tree-sitter-xml-0.7.0" = "sha256-RTWvOUAs3Uql9DKsP1jf9FZZHaZORE40GXd+6g6RQZw=";
      };
    };
    date = "2024-11-12";
  };
  minimal-tmux-status = {
    pname = "minimal-tmux-status";
    version = "d7188c1aeb1c7dd03230982445b7360f5e230131";
    src = fetchFromGitHub {
      owner = "niksingh710";
      repo = "minimal-tmux-status";
      rev = "d7188c1aeb1c7dd03230982445b7360f5e230131";
      fetchSubmodules = false;
      sha256 = "sha256-JtbuSxWFR94HiUdQL9uIm2V/kwGz0gbVbqvYWmEncbc=";
    };
    date = "2024-11-04";
  };
  miru = {
    pname = "miru";
    version = "v5.5.8";
    src = fetchFromGitHub {
      owner = "ThaUnknown";
      repo = "miru";
      rev = "v5.5.8";
      fetchSubmodules = false;
      sha256 = "sha256-IMoB1VUPmIx+wQ6QZJvF1WdVfjRM+hCaKQn17tLb37U=";
    };
  };
  mosdns-cn = {
    pname = "mosdns-cn";
    version = "v1.4.0";
    src = fetchurl {
      url = "https://github.com/IrineSistiana/mosdns-cn/releases/download/v1.4.0/mosdns-cn-linux-arm64.zip";
      sha256 = "sha256-EMWm3EFtIvyBmnLniH9xD4cJacuN5gQWDXRudiMB06I=";
    };
  };
  mpv-M-x = {
    pname = "mpv-M-x";
    version = "b2fac4ad7c9e762196de3eeea5c5c884b5e9a05b";
    src = fetchFromGitHub {
      owner = "Seme4eg";
      repo = "mpv-scripts";
      rev = "b2fac4ad7c9e762196de3eeea5c5c884b5e9a05b";
      fetchSubmodules = false;
      sha256 = "sha256-hxodo/40Ipj7pSHowDxywCdMo/wTzWLnJU+zhgjYqlc=";
    };
    date = "2024-11-04";
  };
  mpv-autoloop = {
    pname = "mpv-autoloop";
    version = "a8920592a4dbda574b51ddc6c2000851a13549a5";
    src = fetchFromGitHub {
      owner = "zc62";
      repo = "mpv-scripts";
      rev = "a8920592a4dbda574b51ddc6c2000851a13549a5";
      fetchSubmodules = false;
      sha256 = "sha256-pot53UjIJjzehLGxku16dNG1DBwXuOZ7FXQtmnezhwY=";
    };
    date = "2020-08-28";
  };
  mpv-blur-edges = {
    pname = "mpv-blur-edges";
    version = "d0390c8e802c2e888ff4a2e1d5e4fb040f855b89";
    src = fetchFromGitHub {
      owner = "occivink";
      repo = "mpv-scripts";
      rev = "d0390c8e802c2e888ff4a2e1d5e4fb040f855b89";
      fetchSubmodules = false;
      sha256 = "sha256-pc2aaO7lZaoYMEXv5M0WI7PtmqgkNbdtNiLZZwVzppM=";
    };
    date = "2024-01-11";
  };
  mpv-btfs-stream = {
    pname = "mpv-btfs-stream";
    version = "47004fb3d176fe83c58220dd34264c720320522a";
    src = fetchFromGitHub {
      owner = "noctuid";
      repo = "mpv-btfs-stream";
      rev = "47004fb3d176fe83c58220dd34264c720320522a";
      fetchSubmodules = false;
      sha256 = "sha256-IAzbH4TrlKQtZEUqSSK/8z2ahY4d5Lb0XuiO2aZtkKo=";
    };
    date = "2021-07-16";
  };
  mpv-smartcopypaste_ii = {
    pname = "mpv-smartcopypaste_ii";
    version = "48d68283cea47ff8e904decc9003b3abc3e2123e";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "48d68283cea47ff8e904decc9003b3abc3e2123e";
      fetchSubmodules = false;
      sha256 = "sha256-95CAKjBRELX2f7oWSHFWJnI0mikAoxhfUphe9k51Qf4=";
    };
    date = "2023-11-25";
  };
  mpv-smartskip = {
    pname = "mpv-smartskip";
    version = "48d68283cea47ff8e904decc9003b3abc3e2123e";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "48d68283cea47ff8e904decc9003b3abc3e2123e";
      fetchSubmodules = false;
      sha256 = "sha256-95CAKjBRELX2f7oWSHFWJnI0mikAoxhfUphe9k51Qf4=";
    };
    date = "2023-11-25";
  };
  mpv-webtorrent-hook = {
    pname = "mpv-webtorrent-hook";
    version = "eb2da86b628c512184818b19307632fa71fe7fb9";
    src = fetchFromGitHub {
      owner = "noctuid";
      repo = "mpv-webtorrent-hook";
      rev = "eb2da86b628c512184818b19307632fa71fe7fb9";
      fetchSubmodules = false;
      sha256 = "sha256-udKOyX0/R47wXSmYndhhq38D94gksxZbhx50VjG1HhY=";
    };
  };
  neonmodem = {
    pname = "neonmodem";
    version = "v1.0.6";
    src = fetchFromGitHub {
      owner = "mrusme";
      repo = "neonmodem";
      rev = "v1.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-VLR6eicffA0IXVwEZMvgpm1kVmrLYVZOtq7MSy+vIw8=";
    };
  };
  nix-auto-follow = {
    pname = "nix-auto-follow";
    version = "b6b221222552c7301a1242430d83317a20a5e5f8";
    src = fetchFromGitHub {
      owner = "fzakaria";
      repo = "nix-auto-follow";
      rev = "b6b221222552c7301a1242430d83317a20a5e5f8";
      fetchSubmodules = false;
      sha256 = "sha256-B5OB97AujLCBah0c1vYAUq4IGDtWRR0DwBqrXS8XJlU=";
    };
    date = "2024-11-03";
  };
  nrf-udev = {
    pname = "nrf-udev";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "NordicSemiconductor";
      repo = "nrf-udev";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-bEIAsz9ZwX6RTzhv5/waFZ5a3KlnwX4kQs29+475zN0=";
    };
  };
  numara = {
    pname = "numara";
    version = "v5.6.0";
    src = fetchFromGitHub {
      owner = "bornova";
      repo = "numara-calculator";
      rev = "v5.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-Pn2h9Z+PDEyvhtZemfUeCW6zx0E6Ccam9GCELdHsgBs=";
    };
  };
  org-export = {
    pname = "org-export";
    version = "64ac299c041877620c2cadba83ded44f46c4e124";
    src = fetchFromGitHub {
      owner = "nhoffman";
      repo = "org-export";
      rev = "64ac299c041877620c2cadba83ded44f46c4e124";
      fetchSubmodules = false;
      sha256 = "sha256-GIkkYary9R3mf9r9QW0fgmnutMlhIp7PhM9KX7kXiuQ=";
    };
    date = "2023-10-25";
  };
  otree = {
    pname = "otree";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "fioncat";
      repo = "otree";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-WvoiTu6erNI5Cb9PSoHgL6+coIGWLe46pJVXBZHOLTE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./otree-v0.3.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  paclear = {
    pname = "paclear";
    version = "v0.0.13";
    src = fetchFromGitHub {
      owner = "orangekame3";
      repo = "paclear";
      rev = "v0.0.13";
      fetchSubmodules = false;
      sha256 = "sha256-Q4uY5aEcQKKLxhBGzmLdOy/bLG0/hpFRkF10wA68Ic0=";
    };
  };
  pangu-vim = {
    pname = "pangu-vim";
    version = "b7210117695dca05d94de1ac2108401f8eff0a2d";
    src = fetchFromGitHub {
      owner = "hotoo";
      repo = "pangu.vim";
      rev = "b7210117695dca05d94de1ac2108401f8eff0a2d";
      fetchSubmodules = false;
      sha256 = "sha256-MvT/3keKv05ZetWnKRA9nD2AyJKoyeLV7rtPlCCl98Q=";
    };
    date = "2023-02-19";
  };
  parinfer-rust = {
    pname = "parinfer-rust";
    version = "d84828b453e158d06406f6b5e9056f6b54ff76c9";
    src = fetchFromGitHub {
      owner = "eraserhd";
      repo = "parinfer-rust";
      rev = "d84828b453e158d06406f6b5e9056f6b54ff76c9";
      fetchSubmodules = false;
      sha256 = "sha256-Q2fYogfn5QcNDEie4sUaVydAmDmcFXnsvz35cxPCf+M=";
    };
    date = "2024-05-07";
  };
  pik = {
    pname = "pik";
    version = "fcb9d7eb7dfcb62d0c93e32dd462be1728c3096e";
    src = fetchFromGitHub {
      owner = "immanelg";
      repo = "pik";
      rev = "fcb9d7eb7dfcb62d0c93e32dd462be1728c3096e";
      fetchSubmodules = false;
      sha256 = "sha256-s13olb4J3f9DZpGqi3CRwx7Q7zWIe6PyLZmnBI+USnk=";
    };
    date = "2024-08-28";
  };
  play = {
    pname = "play";
    version = "v0.3.3";
    src = fetchFromGitHub {
      owner = "paololazzari";
      repo = "play";
      rev = "v0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-l6nYyfNqm3hunNQqteQWAVJSdeJG2O2FPb6IypHw6CA=";
    };
  };
  pls = {
    pname = "pls";
    version = "a1adfd5dce13d7467f389074fd23b1d3748b7ae0";
    src = fetchFromGitHub {
      owner = "codevogel";
      repo = "pls";
      rev = "a1adfd5dce13d7467f389074fd23b1d3748b7ae0";
      fetchSubmodules = false;
      sha256 = "sha256-g/ZYf8t7NtRLsCZJaFMWNPjqoCKkw8jIydC56+90G1E=";
    };
    date = "2024-08-06";
  };
  pmark = {
    pname = "pmark";
    version = "b35e8a8c52b1bb2f879753ee8871af2961e4afe1";
    src = fetchFromGitHub {
      owner = "purarue";
      repo = "pmark";
      rev = "b35e8a8c52b1bb2f879753ee8871af2961e4afe1";
      fetchSubmodules = false;
      sha256 = "sha256-XoqDBgvPMpy4c3/OBUZa2+jmxZ2SwLCXP2bWORRBuLk=";
    };
    date = "2024-11-11";
  };
  pnut = {
    pname = "pnut";
    version = "44ddd5e976a826aa6e974d8a35f6bd440aea1888";
    src = fetchFromGitHub {
      owner = "udem-dlteam";
      repo = "pnut";
      rev = "44ddd5e976a826aa6e974d8a35f6bd440aea1888";
      fetchSubmodules = false;
      sha256 = "sha256-DeJNk3BLyHhngZRQbjPRLm8kxXRyFl354to6W36IZWI=";
    };
    date = "2024-11-04";
  };
  posting = {
    pname = "posting";
    version = "2.1.1";
    src = fetchFromGitHub {
      owner = "darrenburns";
      repo = "posting";
      rev = "2.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-i3wftbQTg0zD7dLQhEFIoBX+ehMpHk15W1kQqbWkv7Q=";
    };
  };
  pot = {
    pname = "pot";
    version = "3.0.6";
    src = fetchFromGitHub {
      owner = "pot-app";
      repo = "pot-desktop";
      rev = "3.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-PUXZT1kiInM/CXUoRko/5qlrRurGpQ4ym5YMTgFwuxE=";
    };
  };
  proji = {
    pname = "proji";
    version = "v0.20.0";
    src = fetchFromGitHub {
      owner = "proji-rocks";
      repo = "proji";
      rev = "v0.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-6nclWKouYp6ENGK23DQ6Wq9gpIQQjXHyLSOxyKV1i8A=";
    };
  };
  pryrite = {
    pname = "pryrite";
    version = "0.10.20";
    src = fetchFromGitHub {
      owner = "1xyz";
      repo = "pryrite";
      rev = "0.10.20";
      fetchSubmodules = false;
      sha256 = "sha256-mhdS4Wnb0DseddrofyEQZed9VcbfQj0MpoXXOQY2Ct8=";
    };
  };
  puffer-fish = {
    pname = "puffer-fish";
    version = "12d062eae0ad24f4ec20593be845ac30cd4b5923";
    src = fetchFromGitHub {
      owner = "nickeb96";
      repo = "puffer-fish";
      rev = "12d062eae0ad24f4ec20593be845ac30cd4b5923";
      fetchSubmodules = false;
      sha256 = "sha256-2niYj0NLfmVIQguuGTA7RrPIcorJEPkxhH6Dhcy+6Bk=";
    };
    date = "2024-03-03";
  };
  pydantic = {
    pname = "pydantic";
    version = "2.9.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic/pydantic-2.9.2.tar.gz";
      sha256 = "sha256-0VXO9xJl0emAftHDK0yN7sBCpEpQpBiLJaxn7NganA8=";
    };
  };
  pydantic-core = {
    pname = "pydantic-core";
    version = "2.26.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic_core/pydantic_core-2.26.0.tar.gz";
      sha256 = "sha256-RXjUkUvbvRiWO0xhH6OdkS0Nvu/++CEftUbkUXanLR0=";
    };
  };
  pydantic-settings = {
    pname = "pydantic-settings";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pydantic_settings/pydantic_settings-2.6.1.tar.gz";
      sha256 = "sha256-4PklRtipkjy4lBaJq/hdZgGowZoj6Xo0spZKLj+BPKA=";
    };
  };
  pyjokes = {
    pname = "pyjokes";
    version = "v0.6.0";
    src = fetchFromGitHub {
      owner = "pyjokes";
      repo = "pyjokes";
      rev = "v0.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-HJlzGI7OPjAeLvriWi2ieflP2LIKxRYRaPOG1hXn8qg=";
    };
  };
  pypipe = {
    pname = "pypipe";
    version = "v0.4.1";
    src = fetchFromGitHub {
      owner = "bugen";
      repo = "pypipe";
      rev = "v0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-QHQZbjrKU0lE89L/13ukjXqZ2I/8XR9Hz5/YjmiXQhk=";
    };
  };
  quartz = {
    pname = "quartz";
    version = "f434332abba5341d4e520f2fe18710fff6089089";
    src = fetchFromGitHub {
      owner = "vimpostor";
      repo = "quartz";
      rev = "f434332abba5341d4e520f2fe18710fff6089089";
      fetchSubmodules = false;
      sha256 = "sha256-czg17UhEuvQvhPh7j0CsWtaCNszXqFxf6jPyKvM5HIY=";
    };
    date = "2024-11-10";
  };
  radio-go-go = {
    pname = "radio-go-go";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "matteo-pacini";
      repo = "RadioGoGo";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-vEZUBA+KeDHgqZvzrAN6ramZ5D4iqQdVU+qFOK/39co=";
    };
  };
  ranger-devicons2 = {
    pname = "ranger-devicons2";
    version = "94bdcc19218681debb252475fd9d11cfd274d9b1";
    src = fetchFromGitHub {
      owner = "cdump";
      repo = "ranger-devicons2";
      rev = "94bdcc19218681debb252475fd9d11cfd274d9b1";
      fetchSubmodules = false;
      sha256 = "sha256-aJCIoDfzmOnzMLlbOe+dy6129n5Dc4OrefhHnPsgI8k=";
    };
    date = "2024-11-06";
  };
  ranger-zoxide = {
    pname = "ranger-zoxide";
    version = "281828de060299f73fe0b02fcabf4f2f2bd78ab3";
    src = fetchFromGitHub {
      owner = "jchook";
      repo = "ranger-zoxide";
      rev = "281828de060299f73fe0b02fcabf4f2f2bd78ab3";
      fetchSubmodules = false;
      sha256 = "sha256-JEuyYSVa1NS3aftezEJx/k19lwwzf7XhqBCL0jH6VT4=";
    };
    date = "2024-02-08";
  };
  rat = {
    pname = "rat";
    version = "397b4d7faabc59c9da6ae1abbff877f8ae83fc4b";
    src = fetchFromGitHub {
      owner = "ericfreese";
      repo = "rat";
      rev = "397b4d7faabc59c9da6ae1abbff877f8ae83fc4b";
      fetchSubmodules = false;
      sha256 = "sha256-/DAK2lc/4Vh1+fJa6blUBdoWWrnftBy9lcR7xx48WQM=";
    };
    date = "2021-09-23";
  };
  reader = {
    pname = "reader";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "mrusme";
      repo = "reader";
      rev = "v0.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-9hZ7ZS+p6PoLKcuHS2re537wxojN2SzhOm5gBuRX9Xc=";
    };
  };
  render = {
    pname = "render";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "VirtusLab";
      repo = "render";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-BA9kwNWKH1JzVDi+gWkEN19VoTZnuLyGATAzOVtnIXs=";
    };
  };
  repoblame = {
    pname = "repoblame";
    version = "66c7eb2ce6a62f60be1711e8975c1b582ec39045";
    src = fetchFromGitHub {
      owner = "martinn";
      repo = "repoblame";
      rev = "66c7eb2ce6a62f60be1711e8975c1b582ec39045";
      fetchSubmodules = false;
      sha256 = "sha256-CjjDh0Go4gEDFdUHEsTtnIdwR8Aokz0DIMzu/h7tIOA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./repoblame-66c7eb2ce6a62f60be1711e8975c1b582ec39045/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2024-09-15";
  };
  rexi = {
    pname = "rexi";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "royreznik";
      repo = "rexi";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-tag2/QTM6tDCU3qr4e1GqRYAZgpvEgtA+FtR4P7WdiU=";
    };
  };
  "rgg.fish" = {
    pname = "rgg.fish";
    version = "00a852b7d62553b24b8f1bf65d63744ff40c0e5c";
    src = fetchFromGitHub {
      owner = "soraxas";
      repo = "rgg.fish";
      rev = "00a852b7d62553b24b8f1bf65d63744ff40c0e5c";
      fetchSubmodules = false;
      sha256 = "sha256-PjQpoORrYxgt2/2gonOZDambOq4ZMtLmijxwZYlISIk=";
    };
    date = "2024-07-21";
  };
  rimage = {
    pname = "rimage";
    version = "v0.10.3";
    src = fetchFromGitHub {
      owner = "SalOne22";
      repo = "rimage";
      rev = "v0.10.3";
      fetchSubmodules = false;
      sha256 = "sha256-GfxnZ9fuok4/6BGrCZHD+hslCaHYUv16/8jreK+9JEI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rimage-v0.10.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  rsv = {
    pname = "rsv";
    version = "v0.4.14";
    src = fetchFromGitHub {
      owner = "ribbondz";
      repo = "rsv";
      rev = "v0.4.14";
      fetchSubmodules = false;
      sha256 = "sha256-LKom7cLu4P95Vg9m/cP/CfWjeU5tcenejgNQhKPs8uM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rsv-v0.4.14/Cargo.lock;
      outputHashes = {

      };
    };
  };
  rust-kanban = {
    pname = "rust-kanban";
    version = "v0.10.5";
    src = fetchFromGitHub {
      owner = "yashs662";
      repo = "rust_kanban";
      rev = "v0.10.5";
      fetchSubmodules = false;
      sha256 = "sha256-fwKXH99P3KBiZdCgTBnuF2ovlefX3l06rzyTSeYty9Q=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rust-kanban-v0.10.5/Cargo.lock;
      outputHashes = {

      };
    };
  };
  rustywatch = {
    pname = "rustywatch";
    version = "0.2.11";
    src = fetchurl {
      url = "https://github.com/ak9024/rustywatch/releases/download/v0.2.11/rustywatch-0.2.11-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-VSxQttHLlCv7u0GEjnO236yWsdo6ocBOBb/v5tFf/WA=";
    };
  };
  s = {
    pname = "s";
    version = "v0.7.1";
    src = fetchFromGitHub {
      owner = "zquestz";
      repo = "s";
      rev = "v0.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-cu2XGA5rRO+cHZ9QkJvMBjbxNZigxsx12ziCJG1LCQs=";
    };
  };
  sake = {
    pname = "sake";
    version = "v0.15.1";
    src = fetchFromGitHub {
      owner = "alajmo";
      repo = "sake";
      rev = "v0.15.1";
      fetchSubmodules = false;
      sha256 = "sha256-aTbom8J4S0ZCiHPfAPeFKZ+15PxG64dGqQtOKXuEBo8=";
    };
  };
  sauce = {
    pname = "sauce";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "cadecuddy";
      repo = "sauce";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-DqJirsbNl8bJuuYZN9nKHMDCgs6agkdx7s0o7h90So8=";
    };
  };
  sbsrf-rime-data = {
    pname = "sbsrf-rime-data";
    version = "20241016";
    src = fetchurl {
      url = "https://github.com/sbsrf/sbsrf/releases/download/20241016/sbsrf.zip";
      sha256 = "sha256-DfDtdudaqXQAO+wIfaAUGzGgXlggt3teDOoFoTr2v+A=";
    };
  };
  serie = {
    pname = "serie";
    version = "0.4.0";
    src = fetchurl {
      url = "https://github.com/lusingander/serie/releases/download/v0.4.0/serie-0.4.0-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-BFxd+UVx4KhER/9p0PP8DuArLjVVC9QWcsECm6OnnrE=";
    };
  };
  serpl = {
    pname = "serpl";
    version = "0.3.3";
    src = fetchFromGitHub {
      owner = "yassinebridi";
      repo = "serpl";
      rev = "0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-koD5aFqL+XVxc5Iq3reTYIHiPm0z7hAQ4K59IfbY4Hg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./serpl-0.3.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  servicer = {
    pname = "servicer";
    version = "v0.1.13";
    src = fetchFromGitHub {
      owner = "servicer-labs";
      repo = "servicer";
      rev = "v0.1.13";
      fetchSubmodules = false;
      sha256 = "sha256-4/6vu/iIZ7ZHHgi3eMshCIygO3ynFSHoiSGWjHzEcZw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./servicer-v0.1.13/Cargo.lock;
      outputHashes = {

      };
    };
  };
  shipit = {
    pname = "shipit";
    version = "0.4.0";
    src = fetchFromGitHub {
      owner = "sapegin";
      repo = "shipit";
      rev = "0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-gT+4b1D4kfy39CuFIR/eF316Ep8E1Ef74wuebljfhI4=";
    };
  };
  sig = {
    pname = "sig";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "ynqa";
      repo = "sig";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-nt/KV4ohFNZTJTwbNoSxb5v9zQwp+7ypvfMthL1yMus=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./sig-v0.1.3/Cargo.lock;
      outputHashes = {

      };
    };
  };
  simple-completion-language-server = {
    pname = "simple-completion-language-server";
    version = "b79a66085ca03b01652a0668d22e21c337b4c8e6";
    src = fetchFromGitHub {
      owner = "estin";
      repo = "simple-completion-language-server";
      rev = "b79a66085ca03b01652a0668d22e21c337b4c8e6";
      fetchSubmodules = false;
      sha256 = "sha256-2LQ5R76raLJT2SV2BcDLRI/gag0YIQvd5vX8aISixrk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./simple-completion-language-server-b79a66085ca03b01652a0668d22e21c337b4c8e6/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2024-11-12";
  };
  soba = {
    pname = "soba";
    version = "1.2.21";
    src = fetchFromGitHub {
      owner = "jonhadfield";
      repo = "soba";
      rev = "1.2.21";
      fetchSubmodules = false;
      sha256 = "sha256-QWo5POFYlWJOLfW3arayY2gTgjTCqDs701NpZZV098o=";
    };
  };
  sonicradio = {
    pname = "sonicradio";
    version = "v0.3.3";
    src = fetchFromGitHub {
      owner = "dancnb";
      repo = "sonicradio";
      rev = "v0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-ZACLTBKHM6wjN+LtV6hlxaffEY/tuCPMzOzyjfeBf8E=";
    };
  };
  sprite-dicing = {
    pname = "sprite-dicing";
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "elringus";
      repo = "sprite-dicing";
      rev = "v2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-Wyws9I/ITdswUqxdmckXtutr5FK8ocsvQRIcMlASiLo=";
    };
    cargoLock."crates/Cargo.lock" = {
      lockFile = ./sprite-dicing-v2.1.0/crates/Cargo.lock;
      outputHashes = {

      };
    };
  };
  ssh-tpm-agent = {
    pname = "ssh-tpm-agent";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "Foxboron";
      repo = "ssh-tpm-agent";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-yK7G+wZIn+kJazKOFOs8EYlRWZkCQuT0qZfmdqbcOnM=";
    };
  };
  stego = {
    pname = "stego";
    version = "d9d5911f4d2d141fea74936f235a74bf03961c71";
    src = fetchFromGitHub {
      owner = "ajmwagar";
      repo = "stego";
      rev = "d9d5911f4d2d141fea74936f235a74bf03961c71";
      fetchSubmodules = false;
      sha256 = "sha256-fChtlJqzI2gTbdN374e3ZQntCHiaknWgrDFSD8+Ee5M=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./stego-d9d5911f4d2d141fea74936f235a74bf03961c71/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2019-10-22";
  };
  sunbeam = {
    pname = "sunbeam";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "pomdtr";
      repo = "sunbeam";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-X5LPRrI5VVCLnZLrjLyocexmReS5RdmQyJbbAvwFxs0=";
    };
  };
  superwhich = {
    pname = "superwhich";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "DarkCeptor44";
      repo = "superwhich";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-mRdfulh1o4YBAcyQmFr0ydqIgk6GrorClJhp6Z7sz6U=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./superwhich-v1.0.1/Cargo.lock;
      outputHashes = {

      };
    };
  };
  svgshift = {
    pname = "svgshift";
    version = "5a24a7e661a6056c994d1bf1b4ef63b8dd506ada";
    src = fetchFromGitHub {
      owner = "10xJSChad";
      repo = "svgshift";
      rev = "5a24a7e661a6056c994d1bf1b4ef63b8dd506ada";
      fetchSubmodules = false;
      sha256 = "sha256-je9ZbXTFKq3tA3aE0QTu70Sco45rQyLW+lS6//zNCmw=";
    };
    date = "2024-08-20";
  };
  tabry-rs = {
    pname = "tabry-rs";
    version = "58bf619e2f90102d0678de056d9b9088ad7d179a";
    src = fetchFromGitHub {
      owner = "evanbattaglia";
      repo = "tabry-rs";
      rev = "58bf619e2f90102d0678de056d9b9088ad7d179a";
      fetchSubmodules = false;
      sha256 = "sha256-iWl16BEYMSQ1cvJJqkJ8anhrJui033NZeoLmockyarw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./tabry-rs-58bf619e2f90102d0678de056d9b9088ad7d179a/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2024-10-11";
  };
  tach = {
    pname = "tach";
    version = "v0.14.3";
    src = fetchFromGitHub {
      owner = "gauge-sh";
      repo = "tach";
      rev = "v0.14.3";
      fetchSubmodules = false;
      sha256 = "sha256-tZN3GtjO6lcd6CGQQXfAe3lxP6v4q1ear3HLTdFYpr4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./tach-v0.14.3/Cargo.lock;
      outputHashes = {
        "ruff_python_ast-0.0.0" = "sha256-+8JKzKKWPQEanU2mh8p5sRjnoU6DawTQQi43qRXVXIg=";
      };
    };
  };
  task-relative-recur = {
    pname = "task-relative-recur";
    version = "5d4ab7d0a5e3f697fb2a00790972e6f3f705fe42";
    src = fetchFromGitHub {
      owner = "mlaradji";
      repo = "task-relative-recur";
      rev = "5d4ab7d0a5e3f697fb2a00790972e6f3f705fe42";
      fetchSubmodules = false;
      sha256 = "sha256-oPK67wG0wiUZCgCMtdwvK8w/WKjq3fMbZ9G1HVuVO6Q=";
    };
    date = "2023-02-06";
  };
  taskwarrior-better-recur = {
    pname = "taskwarrior-better-recur";
    version = "2731e1c441d81a3b2217b132e1f40ce4ea49ec5f";
    src = fetchFromGitHub {
      owner = "scottyob";
      repo = "taskwarrior-better-recur";
      rev = "2731e1c441d81a3b2217b132e1f40ce4ea49ec5f";
      fetchSubmodules = false;
      sha256 = "sha256-FpUX+6cOZUhv2ZDHwqlwyl1413RJaekvBADZ4486YPU=";
    };
    date = "2024-07-04";
  };
  television = {
    pname = "television";
    version = "v0.4.20";
    src = fetchurl {
      url = "https://github.com/alexpasmantier/television/releases/download/v0.4.20/tv-v0.4.20-linux-x86_64.tar.gz";
      sha256 = "sha256-4TJEwCNcwTiky1iAj5PzDsI4GPB/6fCgTbIu2QAl5Ps=";
    };
  };
  templify = {
    pname = "templify";
    version = "1.0.0";
    src = fetchFromGitHub {
      owner = "cophilot";
      repo = "templify";
      rev = "1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-sIZuFxnBo7+oS9GW/1WbwVPik3EBj7zWWlQFNa0Qfr0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./templify-1.0.0/Cargo.lock;
      outputHashes = {

      };
    };
  };
  termsand = {
    pname = "termsand";
    version = "75a50ba82ed299047cd5d0cd53b6fce390cfc6e8";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "termsand";
      rev = "75a50ba82ed299047cd5d0cd53b6fce390cfc6e8";
      fetchSubmodules = false;
      sha256 = "sha256-tylzyjg3AJutwnrxjxzshEfuTD14VegCIMb/wroGpj0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./termsand-75a50ba82ed299047cd5d0cd53b6fce390cfc6e8/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2024-08-15";
  };
  tewi = {
    pname = "tewi";
    version = "v0.4.1";
    src = fetchFromGitHub {
      owner = "anlar";
      repo = "tewi";
      rev = "v0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-cfp3HGK7nIcDDPWqeDOjx95rnM79mrANNhgHs7+xzn0=";
    };
  };
  textimg = {
    pname = "textimg";
    version = "v3.1.10";
    src = fetchFromGitHub {
      owner = "jiro4989";
      repo = "textimg";
      rev = "v3.1.10";
      fetchSubmodules = false;
      sha256 = "sha256-6lmGuqXuK0ROf24wLEEeGIK0Etk1qMtsmT52LCnmWQc=";
    };
  };
  textpod = {
    pname = "textpod";
    version = "0.1.2";
    src = fetchFromGitHub {
      owner = "freetonik";
      repo = "textpod";
      rev = "0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-pTon0BXq/scjQtTwHzvzrcSpuPwuK+omWSJInvAnC3A=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./textpod-0.1.2/Cargo.lock;
      outputHashes = {

      };
    };
  };
  textual = {
    pname = "textual";
    version = "0.85.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/textual/textual-0.85.2.tar.gz";
      sha256 = "sha256-KkFplcSdU4GoHQpv0jklyw4/FLTyOe0F81+jyYG7HfI=";
    };
  };
  textual-autocomplete = {
    pname = "textual-autocomplete";
    version = "3.0.0a12";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/textual_autocomplete/textual_autocomplete-3.0.0a12.tar.gz";
      sha256 = "sha256-HSyeTSTH9XWryMYSy2q//0cG9qqrm5OVBrldroRUkwk=";
    };
  };
  tmux-auto-renumber-session = {
    pname = "tmux-auto-renumber-session";
    version = "19fead0395afdc36830d840249c0c7190ccd8bb9";
    src = fetchFromGitHub {
      owner = "T1erno";
      repo = "tmux-auto-renumber-session";
      rev = "19fead0395afdc36830d840249c0c7190ccd8bb9";
      fetchSubmodules = false;
      sha256 = "sha256-An92IORTC2aeKGkUcAEj8gLPd9t5V3FE4EaAHF4LDoA=";
    };
    date = "2023-03-01";
  };
  tmux-continuum = {
    pname = "tmux-continuum";
    version = "c7ae4f4f4a1c5b7a00718f71742eb3d3ebd9b82a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-continuum";
      rev = "c7ae4f4f4a1c5b7a00718f71742eb3d3ebd9b82a";
      fetchSubmodules = false;
      sha256 = "sha256-YqQvKWQ+nPxGJoA4LQVWAuRt9gzLsF7bi/KB4uofpe8=";
    };
    date = "2024-07-08";
  };
  tmux-edgelord = {
    pname = "tmux-edgelord";
    version = "a390528534bf8e0f050daa1776db555eba4fadd9";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-edgelord";
      rev = "a390528534bf8e0f050daa1776db555eba4fadd9";
      fetchSubmodules = false;
      sha256 = "sha256-jermraRckdUz3BQCJVKcF1DyuKhnUzfSBJcCicXC7Q4=";
    };
    date = "2024-07-08";
  };
  tmux-fzf-url = {
    pname = "tmux-fzf-url";
    version = "28ed7ce3c73a328d8463d4f4aaa6ccb851e520fa";
    src = fetchFromGitHub {
      owner = "wfxr";
      repo = "tmux-fzf-url";
      rev = "28ed7ce3c73a328d8463d4f4aaa6ccb851e520fa";
      fetchSubmodules = false;
      sha256 = "sha256-tl0SjG/CeolrN7OIHj6MgkB9lFmFgEuJevsSuwVs+78=";
    };
    date = "2024-04-14";
  };
  tmux-kanagawa = {
    pname = "tmux-kanagawa";
    version = "d177855dcc580e730b96690b56451b4f0431a85b";
    src = fetchFromGitHub {
      owner = "Nybkox";
      repo = "tmux-kanagawa";
      rev = "d177855dcc580e730b96690b56451b4f0431a85b";
      fetchSubmodules = false;
      sha256 = "sha256-u0btTdWd5b8Ad76nDt5BXFW35VUVrrP2R6FiwYPuzgQ=";
    };
    date = "2024-11-03";
  };
  tmux-loadavg = {
    pname = "tmux-loadavg";
    version = "91319eff74ee677efb77c882dcc8e3b8780dc3a2";
    src = fetchFromGitHub {
      owner = "jamesoff";
      repo = "tmux-loadavg";
      rev = "91319eff74ee677efb77c882dcc8e3b8780dc3a2";
      fetchSubmodules = false;
      sha256 = "sha256-JW/O/bVryDILlFCnWYRC+B7nrCIsGYEJDozzu0odX+U=";
    };
    date = "2018-05-30";
  };
  tmux-pane-focus = {
    pname = "tmux-pane-focus";
    version = "94adfd620bee88b9262fe28df6b07a23e82f3a5c";
    src = fetchFromGitHub {
      owner = "graemedavidson";
      repo = "tmux-pane-focus";
      rev = "94adfd620bee88b9262fe28df6b07a23e82f3a5c";
      fetchSubmodules = false;
      sha256 = "sha256-Aur7OkJ8De6BDtSJHSfO1LLpbCfjWsxXi8jh5HNlUbo=";
    };
    date = "2024-03-05";
  };
  tmux-power-zoom = {
    pname = "tmux-power-zoom";
    version = "30eb97c090ff07c8e957b2e761f25931c1d49133";
    src = fetchFromGitHub {
      owner = "jaclu";
      repo = "tmux-power-zoom";
      rev = "30eb97c090ff07c8e957b2e761f25931c1d49133";
      fetchSubmodules = false;
      sha256 = "sha256-FMzdN+xEejjZfmQ65q7sK9sRbSoK/bZYtcaEPgeDGBc=";
    };
    date = "2024-10-14";
  };
  tmux-tea = {
    pname = "tmux-tea";
    version = "345af747c36e94344cbb360310f1d746f1517b6a";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-tea";
      rev = "345af747c36e94344cbb360310f1d746f1517b6a";
      fetchSubmodules = false;
      sha256 = "sha256-CgPn+VZmaMm8lxJlgzQRLdhwHM/XA+KSIr/qwQdf5bs=";
    };
    date = "2024-09-10";
  };
  tmux-tome = {
    pname = "tmux-tome";
    version = "83fd5124d8770697093bd6f46eca5d0080b333e6";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "tome";
      rev = "83fd5124d8770697093bd6f46eca5d0080b333e6";
      fetchSubmodules = false;
      sha256 = "sha256-75zmN0XhsmYnqf8oVTI71yAmA62UVVnRSiUJrtIitw8=";
    };
    date = "2024-11-06";
  };
  tmux-transient-status = {
    pname = "tmux-transient-status";
    version = "c3fcd5180999a7afc075d2dd37d37d1b1b82f7e8";
    src = fetchFromGitHub {
      owner = "TheSast";
      repo = "tmux-transient-status";
      rev = "c3fcd5180999a7afc075d2dd37d37d1b1b82f7e8";
      fetchSubmodules = false;
      sha256 = "sha256-fOIn8hVVBDFVLwzmPZP+Bf3ccxy/hsAnKIXYD9yv3BE=";
    };
    date = "2023-12-26";
  };
  tmux-which-key = {
    pname = "tmux-which-key";
    version = "b7283f4ccece66dd4a49fd6badd55b43262c6ae6";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "tmux-which-key";
      rev = "b7283f4ccece66dd4a49fd6badd55b43262c6ae6";
      fetchSubmodules = false;
      sha256 = "sha256-zJlQ+3945xrfI5BpywpB5J79m5j2y3vtLUHsZgUaCJ0=";
    };
    date = "2024-09-09";
  };
  "tmux.fish" = {
    pname = "tmux.fish";
    version = "0e0fc8052c7523a96d3c12313a51ba9921c59406";
    src = fetchFromGitHub {
      owner = "budimanjojo";
      repo = "tmux.fish";
      rev = "0e0fc8052c7523a96d3c12313a51ba9921c59406";
      fetchSubmodules = false;
      sha256 = "sha256-HBu0SSFejZRSMIAK+5J8Ao8EPj4hpkIuWkI3gSJCn5c=";
    };
    date = "2024-10-21";
  };
  tmux2k = {
    pname = "tmux2k";
    version = "be70e2e352135f41f8665ddd8729f2ef47d60089";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "tmux2k";
      rev = "be70e2e352135f41f8665ddd8729f2ef47d60089";
      fetchSubmodules = false;
      sha256 = "sha256-UshHfSEvzJMK3G1bolwStdza9oiYWNFLC4xsKZlU/TI=";
    };
    date = "2024-11-04";
  };
  to-fish = {
    pname = "to-fish";
    version = "52b151cfe67c00cb64d80ccc6dae398f20364938";
    src = fetchFromGitHub {
      owner = "joehillen";
      repo = "to-fish";
      rev = "52b151cfe67c00cb64d80ccc6dae398f20364938";
      fetchSubmodules = false;
      sha256 = "sha256-DfDsU/qY2XdYlkLISIOv02ggHfKEpb+YompNWWjs5/A=";
    };
    date = "2023-04-24";
  };
  "todo-comments.fish" = {
    pname = "todo-comments.fish";
    version = "fb818507c2b95e498495fb73206eb101566d71ee";
    src = fetchFromGitHub {
      owner = "kpbaks";
      repo = "todo-comments.fish";
      rev = "fb818507c2b95e498495fb73206eb101566d71ee";
      fetchSubmodules = false;
      sha256 = "sha256-x6B1qm1sEODBus6Dd30iifcOMj/q+8DA3pKzKQ7zzlc=";
    };
    date = "2024-02-11";
  };
  tokyonight-vim = {
    pname = "tokyonight-vim";
    version = "4e82e0f0452a6ce8f387828ec71013015515035a";
    src = fetchFromGitHub {
      owner = "ghifarit53";
      repo = "tokyonight-vim";
      rev = "4e82e0f0452a6ce8f387828ec71013015515035a";
      fetchSubmodules = false;
      sha256 = "sha256-ui/6xv8PH6KuQ4hG1FNMf6EUdF2wfWPNgG/GMXYvn/8=";
    };
    date = "2021-04-23";
  };
  toolong = {
    pname = "toolong";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "Textualize";
      repo = "toolong";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-Zd6j1BIrsLJqptg7BXb67qY3DaeHRHieWJoYYCDHaoc=";
    };
  };
  toru = {
    pname = "toru";
    version = "v0.3.3";
    src = fetchFromGitHub {
      owner = "sweetbbak";
      repo = "toru";
      rev = "v0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-hFs/CJHWgfy/KCp7lC8u8YrclQk0RWhrSe4IXbsJL3I=";
    };
  };
  tp = {
    pname = "tp";
    version = "v1.0.0";
    src = fetchurl {
      url = "https://github.com/minefuto/tp/releases/download/v1.0.0/tp_Linux_x86_64.tar.gz";
      sha256 = "sha256-FqGZjD+IVSH97NQDE75s9+edGsLje2yCZRblN6qlvhM=";
    };
  };
  treegen = {
    pname = "treegen";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "bilbilak";
      repo = "treegen";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-z6CHr89fC9UVQgPmugOctB82XQ8yP6K5Ap2qsMLSnyk=";
    };
  };
  trzsz-go = {
    pname = "trzsz-go";
    version = "v1.1.8";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-go";
      rev = "v1.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-g1fbgKTFS9aPAmnTeFYoymrDEoZ6BtzUhA2Z9SNYbsU=";
    };
  };
  trzsz-ssh = {
    pname = "trzsz-ssh";
    version = "v0.1.22";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-ssh";
      rev = "v0.1.22";
      fetchSubmodules = false;
      sha256 = "sha256-VvPdWRP+lrhho+Bk5rT9pktEvKe01512WoDfAu5d868=";
    };
  };
  tuime = {
    pname = "tuime";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "nate-sys";
      repo = "tuime";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-9CGktRXx7IZ0yv/U78SWSifJ6YBIiV8cf5Dq60PPCcQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./tuime-v1.0.1/Cargo.lock;
      outputHashes = {

      };
    };
  };
  updo = {
    pname = "updo";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "Owloops";
      repo = "updo";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-AkzniJ58tcesLSsOaJW1n1z4cavo2O8DUD0+ImBBLgM=";
    };
  };
  v = {
    pname = "v";
    version = "353a0e7620294d840bdffcf0e7c5e287625a9709";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "v";
      rev = "353a0e7620294d840bdffcf0e7c5e287625a9709";
      fetchSubmodules = false;
      sha256 = "sha256-urXj1+UTwc6yFxThSm/05HQ2A+N9xuiZHfyDA2BhQ/w=";
    };
    date = "2024-11-03";
  };
  vim-auto-save = {
    pname = "vim-auto-save";
    version = "6697e84b25f6a56c36d0c5ae9004b8b9247662ea";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-auto-save";
      rev = "6697e84b25f6a56c36d0c5ae9004b8b9247662ea";
      fetchSubmodules = false;
      sha256 = "sha256-hP3s7iIfGjLMYF6lqnL6ORGqmPfM0d2BCdW4OSqg4ac=";
    };
    date = "2024-07-15";
  };
  vim-cycle = {
    pname = "vim-cycle";
    version = "a327a47e16cbc7f83a1427050c5878b165a53132";
    src = fetchFromGitHub {
      owner = "zef";
      repo = "vim-cycle";
      rev = "a327a47e16cbc7f83a1427050c5878b165a53132";
      fetchSubmodules = false;
      sha256 = "sha256-pSpqt5JUG26G0T1849z1lcFK4tpdJWPTgODPK5nW72M=";
    };
    date = "2022-02-17";
  };
  vim-floaterm = {
    pname = "vim-floaterm";
    version = "4e28c8dd0271e10a5f55142fb6fe9b1599ee6160";
    src = fetchFromGitHub {
      owner = "voldikss";
      repo = "vim-floaterm";
      rev = "4e28c8dd0271e10a5f55142fb6fe9b1599ee6160";
      fetchSubmodules = false;
      sha256 = "sha256-wIgcBcdxJsT+qrsC5Boj6hp0xpp5gFeQFhK7yyC5a1o=";
    };
    date = "2024-04-08";
  };
  vim-github-link = {
    pname = "vim-github-link";
    version = "9df238dbf150417772f2a1b7748750cfeda3d167";
    src = fetchFromGitHub {
      owner = "knsh14";
      repo = "vim-github-link";
      rev = "9df238dbf150417772f2a1b7748750cfeda3d167";
      fetchSubmodules = false;
      sha256 = "sha256-FGPtU+/sEULde5G2xwqVqf9kIWwUE426/Ot7uZoW8Pk=";
    };
    date = "2024-11-01";
  };
  vim-mkdir = {
    pname = "vim-mkdir";
    version = "f0ba7a7dc190a0cedf1d827958c99f3718109cf0";
    src = fetchFromGitHub {
      owner = "pbrisbin";
      repo = "vim-mkdir";
      rev = "f0ba7a7dc190a0cedf1d827958c99f3718109cf0";
      fetchSubmodules = false;
      sha256 = "sha256-3GZFp6Q6ZM48b4Qxy3BpsMGI9K9vmIsvZ53R6niw4k4=";
    };
    date = "2019-04-29";
  };
  vim-silicon = {
    pname = "vim-silicon";
    version = "4a93122ae2139a12e2a56f064d086c05160b6835";
    src = fetchFromGitHub {
      owner = "segeljakt";
      repo = "vim-silicon";
      rev = "4a93122ae2139a12e2a56f064d086c05160b6835";
      fetchSubmodules = false;
      sha256 = "sha256-8pCHtApD/xXav2UBVOVhkaHg3YS4aNCZ73mog04bYuA=";
    };
    date = "2020-12-01";
  };
  vim-snipewin = {
    pname = "vim-snipewin";
    version = "9616fd4564d61c78947e3dda53ef9ac61cce032c";
    src = fetchFromGitHub {
      owner = "4513ECHO";
      repo = "vim-snipewin";
      rev = "9616fd4564d61c78947e3dda53ef9ac61cce032c";
      fetchSubmodules = false;
      sha256 = "sha256-dUOP8/NBwAhie0DUdkjyCUuoQ9q1UD1PJm02zzz9BNg=";
    };
    date = "2024-03-28";
  };
  vim-templates = {
    pname = "vim-templates";
    version = "c4ce1903fc458688bc421f0cb4572af8a8977cdb";
    src = fetchFromGitHub {
      owner = "tibabit";
      repo = "vim-templates";
      rev = "c4ce1903fc458688bc421f0cb4572af8a8977cdb";
      fetchSubmodules = false;
      sha256 = "sha256-p0TEJr/2TBoOk48xgtrqwnAtQlYRkz/NEKcadLAJoCA=";
    };
    date = "2024-04-26";
  };
  vim-tome = {
    pname = "vim-tome";
    version = "83fd5124d8770697093bd6f46eca5d0080b333e6";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "tome";
      rev = "83fd5124d8770697093bd6f46eca5d0080b333e6";
      fetchSubmodules = false;
      sha256 = "sha256-75zmN0XhsmYnqf8oVTI71yAmA62UVVnRSiUJrtIitw8=";
    };
    date = "2024-11-06";
  };
  vim-toop = {
    pname = "vim-toop";
    version = "836c043756b57770068186886b72cbb2fef0d0eb";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-toop";
      rev = "836c043756b57770068186886b72cbb2fef0d0eb";
      fetchSubmodules = false;
      sha256 = "sha256-+z/4uAIUMqaoXxzqF9qVZsPIWh04zkfybZT+opeJOXg=";
    };
    date = "2024-10-16";
  };
  vim-visual-star-search = {
    pname = "vim-visual-star-search";
    version = "3ea07a973a8f3cb2b714c50ac0adca35da157631";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-visual-star-search";
      rev = "3ea07a973a8f3cb2b714c50ac0adca35da157631";
      fetchSubmodules = false;
      sha256 = "sha256-hiL9DuvQl4wUSZWCLJjGZYWLzIRXqbVCtZ1GLJTKFp4=";
    };
    date = "2024-07-16";
  };
  vim-workspace = {
    pname = "vim-workspace";
    version = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
    src = fetchFromGitHub {
      owner = "thaerkh";
      repo = "vim-workspace";
      rev = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
      fetchSubmodules = false;
      sha256 = "sha256-2Brx098dk5THiieBiW71FG9mUUwS1CSY9mpOPWA/Tq4=";
    };
    date = "2023-05-28";
  };
  vim-zoom = {
    pname = "vim-zoom";
    version = "65145acd49c62e042502e6f9a5b9b468006c768f";
    src = fetchFromGitHub {
      owner = "ourgal";
      repo = "vim-zoom";
      rev = "65145acd49c62e042502e6f9a5b9b468006c768f";
      fetchSubmodules = false;
      sha256 = "sha256-mTcqxP9mr9P14d7fCUWhIY7Zu4ehjwLJbjMrBsNBUHc=";
    };
    date = "2024-07-17";
  };
  vimsuggest = {
    pname = "vimsuggest";
    version = "187215190586296bf7641322cd0fb4333d70b44f";
    src = fetchFromGitHub {
      owner = "girishji";
      repo = "vimsuggest";
      rev = "187215190586296bf7641322cd0fb4333d70b44f";
      fetchSubmodules = false;
      sha256 = "sha256-L0EMdceByTAupyZBbVf72A5+Z3n2gFSUb7WsB0qoB4w=";
    };
    date = "2024-11-07";
  };
  visual-split-vim = {
    pname = "visual-split-vim";
    version = "423a25911b3e8da04a28d29f205e1059a06e6afa";
    src = fetchFromGitHub {
      owner = "wellle";
      repo = "visual-split.vim";
      rev = "423a25911b3e8da04a28d29f205e1059a06e6afa";
      fetchSubmodules = false;
      sha256 = "sha256-v0j6AExrOJIgde/Aphr7lvonZptMwYQLCB6E+2YsiVg=";
    };
    date = "2017-01-29";
  };
  vl = {
    pname = "vl";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "ellisonleao";
      repo = "vl";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-zmSwlZwbPNafe2PyvFHMeQuJNJvs/c3zsMfVagcVXlU=";
    };
  };
  vlime = {
    pname = "vlime";
    version = "f57518bf6ac1b6c5e10db6a9259016b84ff81d8b";
    src = fetchFromGitHub {
      owner = "vlime";
      repo = "vlime";
      rev = "f57518bf6ac1b6c5e10db6a9259016b84ff81d8b";
      fetchSubmodules = false;
      sha256 = "sha256-034h9L9k+X3b+Z1Kt6HGiteYbHajoo8wu5zgh7RIjv8=";
    };
    date = "2023-10-08";
  };
  vsc-fugitive = {
    pname = "vsc-fugitive";
    version = "0.0.21";
    src = fetchurl {
      url = "https://hnrk-str.gallery.vsassets.io/_apis/public/gallery/publisher/hnrk-str/extension/vscode-fugitive/0.0.21/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-fugitive-0.0.21.zip";
      sha256 = "sha256-DxnQUbmqVbWShJAWiF8IbWeMtvUvMtXRVBDzJAJ+l9c=";
    };
  };
  "web-search.fish" = {
    pname = "web-search.fish";
    version = "29d3027685cdc7f8ed857e3888733c6d5b5458fb";
    src = fetchFromGitHub {
      owner = "veirt";
      repo = "web-search.fish";
      rev = "29d3027685cdc7f8ed857e3888733c6d5b5458fb";
      fetchSubmodules = false;
      sha256 = "sha256-bGgdO3jS+kYaTQBhfw9bGke1S6egg9S4fmEe0buf684=";
    };
    date = "2024-10-14";
  };
  whitespace-format = {
    pname = "whitespace-format";
    version = "0.0.2";
    src = fetchFromGitHub {
      owner = "DavidPal";
      repo = "whitespace-format";
      rev = "0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-UscDx0cQ7YqZc6k42ww9Pi9g5nxJCRr+fcETneG0zHc=";
    };
  };
  wiper = {
    pname = "wiper";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "ikebastuz";
      repo = "wiper";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-IheSAPk1l6wJ2v4RLPIPvY/5XMfh+vJLyQ/Lc7RrCJQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wiper-v0.2.1/Cargo.lock;
      outputHashes = {

      };
    };
  };
  wush = {
    pname = "wush";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "coder";
      repo = "wush";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-2mFe1p15HRyy86pw5LoBtiW9lKrw/N9V81/jkiT4jo4=";
    };
  };
  x = {
    pname = "x";
    version = "v1.1.4";
    src = fetchFromGitHub {
      owner = "devhindo";
      repo = "x";
      rev = "v1.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-sAmyZFX9lZ6UXVCt7st187Ie6aVW0dSUlQQQmLiHUlM=";
    };
  };
  ytui = {
    pname = "ytui";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "Banh-Canh";
      repo = "ytui";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-M3BdfM/3iKe2b3aiOmClVWIgGOrYnRZZ6XpQQFmBNXA=";
    };
  };
  zfind = {
    pname = "zfind";
    version = "v0.4.6";
    src = fetchFromGitHub {
      owner = "laktak";
      repo = "zfind";
      rev = "v0.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-bbeS2x9HzrsOE5h1y07LoEBm9dinMCHX9GJftj5Md9s=";
    };
  };
}
