return {
  "windwp/nvim-ts-autotag",
  ft = {
    "astro",
    "glimmer",
    "handlebars",
    "html",
    "javascript",
    "jsx",
    "markdown",
    "php",
    "rescript",
    "svelte",
    "tsx",
    "typescript",
    "vue",
    "xml",
  },
  config = true,
  enabled = lvim.user_plugins.edit.treesitter.autotag,
}
