{ ... }@args:
args.module (
  args
  // {
    path = ./.;
    nixPkgs = [
      "acpi"
      "atool"
      "bluetuith"
      "btop"
      "charm-freeze"
      "chezmoi"
      "clifm"
      "clipboard-jh"
      "compsize"
      "coreutils-full"
      "cpu-x"
      "croc"
      "cyme"
      "deploy-rs"
      "dmidecode"
      "du-dust"
      "dua"
      "duc"
      "duf"
      "dufs"
      "fastfetch"
      "fd"
      "file"
      "gdu"
      "glances"
      "glxinfo"
      "kmon"
      "libva-utils"
      "mmv-go"
      "nfs-utils"
      "onefetch"
      "ouch"
      "p7zip"
      "pciutils"
      "poop"
      "procs"
      "progress"
      "qrcp"
      "ripgrep"
      "rm-improved"
      "rsync"
      "screenkey"
      "skim"
      "sshfs"
      "sshpass"
      "sshs"
      "nvtop"
      "superfile"
      "sysz"
      "termscp"
      "toolbox"
      "topgrade"
      "trash-cli"
      "ugrep"
      "unrar"
      "unzip"
      "usbutils"
      "ventoy-bin-full"
      "vulkan-tools"
      "wev"
      "wget"
      "xcp"
      "zenith"
    ];
    myPkgs = "advance-touch";
    pyPkgs = "qrcode";
    # nvtop = "full";
    xorgPkgs = "xev";
    enable = [
      "broot"
      "clipmenu"
      "eza"
      "htop"
      "lf"
      "mkcert"
      "nnn"
      "noti"
      "pbgopy"
      "ranger"
      "rclone"
      "ssh"
      "ssh-tpm-agent"
      "syncthing"
      "udiskie"
      "yazi"
    ];
  }
)
