---
name: Update nix hash
on:
  push:
    branches: [main]
  schedule:
    - cron: 0 16 * * *
jobs:
  nvfetcher:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: echo '[keys]' >> keyfile.toml
      - run: echo 'github = "${{ secrets.GITHUB_TOKEN }}"' >> keyfile.toml
      - run: nix run github:berberman/nvfetcher -- -k keyfile.toml
      - run: rm keyfile.toml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto update nix hash'
